### ISSUE TITLE
This is the basic structure...?

### ISSUE THREAD

**Issue by ansorre** [AntonOsika/gpt-engineer#101]
My execution ends with this sentence:

**This is the basic structure of the [my-app-name] app. The code provided here sets up the necessary classes, functions, and methods for the app. The actual implementation of the methods and functions is left as an exercise for the developer.**

where [my-app-name] is a placeholder for the name of my app.

Is this a Joke?
I want it to write it all, not just the structure.
How to do it?
Thanks

**Comment by noxiouscardiumdimidium** [comment]
copy and paste the contents of your all_output.txt to the bottom of the Main_prompt file; remove the "this is the basic structure of [...]" footer and any other redundant junk. modify the top of new main_prompt to include something along the lines of "prioritize completion of function implementations". go to [main]/indentity/ and edit "philosophy" and add a new top line like "ALWAYS Implements complete functions, and writes to file when coding classes and modules." - try again! x)

**Comment by clickbrain** [comment]
This is ChatGPT refusing to actually write or finish the code which happens quite a bit when interacting with it directly. I do not understand why OpenAI has not thought through or addressed this, but I suspect it is part of their deal with Microsoft to not be a full coding provider. 

I have had success with getting ChatGPT to complete applications by continuing the conversation and asking for each component 1 by 1 and I created Issue #119 to request similar functionality be added to gpt-engineer.

**Comment by hacklili** [comment]
how to

**Comment by hacklili** [comment]
use

**Comment by patillacode** [comment]
@hacklili please read the README file.

**Comment by cranyy** [comment]
> copy and paste the contents of your all_output.txt to the bottom of the Main_prompt file; remove the "this is the basic structure of [...]" footer and any other redundant junk. modify the top of new main_prompt to include something along the lines of "prioritize completion of function implementations". go to [main]/indentity/ and edit "philosophy" and add a new top line like "ALWAYS Implements complete functions, and writes to file when coding classes and modules." - try again!

Unfortunately, i tried your suggestions, and now he reached the point where he just rewrites the code over and over and over again, always new, always ignoring both the philosophy and the previous code, and he keeps giving "pass" to a looot of the functions, nearly most. weird stuff. maybe something with the way memory is logged.

**Comment by patillacode** [comment]
Hi @cranyy 

Please create a new issue with your problem explained in the most explicit way possible and we will try to help you.

Also, make sure you read the README and are using the latest stable version:
```
pip install --upgrade gpt-engineer
```
