### ISSUE TITLE
Would be possible to use with Chatgpt plus with a proxy API ?

### ISSUE THREAD

**Issue by madruga8** [AntonOsika/gpt-engineer#102]
Would be possible to use with Chatgpt plus with a proxy API ?

what library can work with it ?

**Comment by madruga8** [comment]
Its an issue a lot of people may have... i already pay 20 dollars on Chatgpt plus and im paying double to keep my plus idle and paying double on API calls (gpt-4 api calls are more expensive than plus subscription as far as i experienced)

**Comment by patillacode** [comment]
Hi @madruga8 

TL;DR: I am not sure, I am not a "Plus" user.

Ideas that come to mind: Can you generate an API Key for GPT Plus?

If so, then yes, but I am not sure what is the "business model" of ChatGPT Plus, meaning maybe it is just (this is my understanding) a way to always have access to ChatGPT and getting  responses a bit faster, but the API goes against the same model AFAIK.

![Screenshot 2023-06-17 at 15 02 43](https://github.com/AntonOsika/gpt-engineer/assets/10074977/39021e9f-acfe-4fc0-b9e3-386a7250deef)

**Comment by madruga8** [comment]
thanks for the anwser @patillacode 

no, they dont allow do generate an API for chatgpt plus... the only difference is that we can use 3.5 turbo unlimited and gpt-4 limited to 25 message every 4 hours (it varies, sometimes i can send much more in a hour)

theres a proxy api in node js called https://github.com/transitive-bullshit/chatgpt-api that uses the chatgpt web as endpoint and i use very often. may be theres something similar to python.

**Comment by patillacode** [comment]
Hi @madruga8 

> Its an issue a lot of people may have

I believe this is not as common you maybe think.

If you want to try adding this functionality please create a PR and we will review it, otherwise I think we have other more pressing issues at the moment.

Thanks though!

**Comment by jojo2massol** [comment]
@madruga8 
> theres a proxy api in node js called https://github.com/transitive-bullshit/chatgpt-api that uses the chatgpt web as endpoint and i use very often. may be theres something similar to python.

Yes, maybe this one :
https://github.com/acheong08/ChatGPT
