### ISSUE TITLE
Try make the `execute_workspace` step run in docker

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#104]

**Comment by AntonOsika** [comment]
Note:

We can do this in a way that we have just one docker that is built once, and we "mount" the workspace to docker

**Comment by AntonOsika** [comment]
Closed this for now since it becomes a mess to forward ports etc

**Comment by liusida** [comment]
I think docker is still a good idea. I just made a docker-based gym-like env for agents to play with (yes, I am thinking of RL w/ HF), maybe you can check this out: https://github.com/liusida/gym-codecraft

There are two key actions that an agent can take: command and write_file.
The agent uses command to interact with the virtual linux system and use write_file to write files to that system.

I feels much safer when all the executions are in docker containers. Hope this helps.

p.s. I don't know why you need to `forward ports`, what is it for?

**Comment by liusida** [comment]
However, installing docker for the first time is time consuming, so maybe it's good for advanced users, but many users won't like it.
