### ISSUE TITLE
ERROR: No matching distribution found for hatchling>=1.8.0

### ISSUE THREAD

**Issue by Snoup97** [AntonOsika/gpt-engineer#110]
im trying to commit changes however the process of commiting breaks due to a pip error, error stack is below:
help is greatly appreciated

    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
      error: subprocess-exited-with-error
      
      pip subprocess to install build dependencies did not run successfully.
      exit code: 1
      
      [9 lines of output]
      WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/hatchling/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/hatchling/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/hatchling/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/hatchling/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/hatchling/
      Could not fetch URL https://pypi.org/simple/hatchling/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/hatchling/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
      ERROR: Could not find a version that satisfies the requirement hatchling>=1.8.0 (from versions: none)
      ERROR: No matching distribution found for hatchling>=1.8.0
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    pip subprocess to install build dependencies did not run successfully.
    exit code: 1

**Comment by patillacode** [comment]
Hi @Snoup97 

could you explain a bit further?
what command are you trying to run?

**Comment by PriyanshNegi** [comment]
Hi @Snoup97,

It seems like you're encountering an issue with the SSL module in Python, which is causing the pip installation to fail. The SSL module is required for pip to connect to HTTPS URLs, such as the PyPI package repository.

To resolve this issue, you can try the following steps:

1. Make sure you have the SSL module installed for Python. You can check this by running the following command in your terminal or command prompt:

   ```
   python -m ssl
   ```

   If the SSL module is missing, you may need to reinstall Python and make sure to include the SSL module during installation.

2. If you're using a virtual environment, activate it before running the installation command.

3. Upgrade pip to the latest version by running the following command:

   ```
   python -m pip install --upgrade pip
   ```

4. Try installing the package again by running the following command:

   ```
   pip install hatchling>=1.8.0
   ```

   This will attempt to install the required package.

If the issue persists, it's possible that there may be an issue with your local environment or network configuration. In that case, you could try using a different network connection or consult with your system administrator for further assistance.

**Comment by Snoup97** [comment]
hi @patillacode @PriyanshNegi 
thanks for respoding so fast. i check the things listed by @PriyanshNegi unfortunately, i couldnt resolve it. however on a github codespace i was able to commit without problems therefore this is not an issue with the project and more with my local setup.
