### ISSUE TITLE
Add deployment instructions to output

### ISSUE THREAD

**Issue by clickbrain** [AntonOsika/gpt-engineer#113]
Let me preface this by saying I am not a developer, but I have a decent level of technical understanding and understand how code works. 

In my instructions for the code I was generating, I said that I wanted step by step instructions for deploying the application on a server. In my case, this is a Telegram bot. It added that request to the specification, but did not provide the instructions in the output. 

It might be good to have an instruction available to the user that does not generate code, but allows them to request instructions for installation or some other component of the app delivery.

**Comment by patillacode** [comment]
I believe this is a good idea, maybe we could add a specific identity and use that one in one of the steps (a new one)

Although maybe we should add that step as optional.

I'll leave this open, maybe someone has a better idea on how to implement, if not I'll revisit.

Thanks @clickbrain

**Comment by AntonOsika** [comment]
Recently fixed this, should print instructions in the end per default!

**Comment by clickbrain** [comment]
Thanks!
