### ISSUE TITLE
GPT Engineer will not save individual files when given specs that result in many files.

### ISSUE THREAD

**Issue by raychorn** [AntonOsika/gpt-engineer#117]
The generated code goes into the logfile however it would be more useful if the tool could make all those files automatically.

**Comment by AntonOsika** [comment]
It should always generate all files. This seems to happen sometimes, we should improve the prompt.

**Comment by AntonOsika** [comment]
Happy to take a well prompt engineered PR on the generate and run_clarified steps

**Comment by patillacode** [comment]
#94 should make sure the file creation works.

**Comment by goncalomoita** [comment]
I have solved these issues and made a [PR #120](https://github.com/AntonOsika/gpt-engineer/pull/120) with my improved parser.

**Comment by sugarbean777** [comment]
Files are not being written. Did the html prompt and it managed to write the html file and another file called python with part of the game code but missing all the rest

**Comment by sugarbean777** [comment]
> I have solved these issues and made a [PR #120](https://github.com/AntonOsika/gpt-engineer/pull/120) with my improved parser.

Do I modify the chat_to_file.py code with the green highlighted code? Also your gpt-engineer/test  test_chat_parser code does that need to be a new file in that directory with your written code?

**Comment by patillacode** [comment]
Many changes have been applied since you posted this, give the latest version a try.

If you wish to reopen the issue please do following the new issue template.
