### ISSUE TITLE
Prompt ChatGPT to finish code one by one

### ISSUE THREAD

**Issue by clickbrain** [AntonOsika/gpt-engineer#119]
As is often the case, ChatGPT refused to finish the project I was working on in gpt-engineer and just said "Implement the remaining methods in the `BotManager` class as described in the specification." It would be good to gather best practices for code delivery from ChatGPT to go back and get it to one by one create the code for the sections that are incomplete. 

For example, add instructions in the prompt to tell ChatGPT to list/tag unfinished components and then gptengineer could go back and request that ChatGPT create each individually and ask ChatGPT to then add them to the appropriate file in the code. I have had success with this in the past when using the primary ChatGPT interface.

**Comment by AntonOsika** [comment]
Feel free to try to submit a PR on this one @clickbrain! See #121

**Comment by clickbrain** [comment]
I'd be the last guy to try to write any code for this. That is why I am so excited about gpt-engineer. I understand it, but have never learned more than a cursory bit here and there.
