### ISSUE TITLE
constantly get  ModuleNotFoundError: No module named 'gpt_engineer'

### ISSUE THREAD

**Issue by panmaster** [AntonOsika/gpt-engineer#126]
ModuleNotFoundError: No module named 'gpt_engineer' , what is  the  issue?

**Comment by eliashanna9** [comment]
+1

**Comment by patillacode** [comment]
Hi,

Please pull the latest version and follow the README
```markdown
pip install -r requirements.txt
export OPENAI_API_KEY=[your api key]
python -m gpt_engineer.main my-new-project
```


Please try look for similar issues before you post one, to avoid noise for us maintainers/collaborators:

![Screenshot 2023-06-17 at 21 45 37](https://github.com/AntonOsika/gpt-engineer/assets/10074977/3534de69-a02f-493c-8f90-ff999aae42ad)

**Comment by PancakeSwapz** [comment]
i had the same error and moved the main.py script outside of the gpt_engineer folder and it worked
