### ISSUE TITLE
Resume?

### ISSUE THREAD

**Issue by mkammes** [AntonOsika/gpt-engineer#127]
This is fantastic!

When code (in this case, py scripts) that is generated is being tested and errors out in Terminal, is there a way to resume/continue from that point or a previous point?

Examples include: IsADirectoryError: [Errno 21] Is a directory, Traceback errors during testing, missing imports from Modules in generated code (e.g. _from **typing** import **Tuple**_).

I see the documentation mentions the code "resumable", but I'm obviously missing something.

Thanks!

**Comment by clickbrain** [comment]
There are a couple of issues for this already: #95 #79

**Comment by patillacode** [comment]
Closing to avoid duplication then!
