### ISSUE TITLE
all_output.txt doesn't include everything needed

### ISSUE THREAD

**Issue by mach7** [AntonOsika/gpt-engineer#137]
Didn't know for sure how to name the title of this post. 

I have the output of my project in all_output.txt as expected, but it seems like there is a limit to how long the file can be? It didn't produce everything that it said it would end up producing. Wondering if the ai could return the generated code and create multiple txt files if needed. That way if the AI hits what I'm assuming is the token limit then the person running the generator can get all of the intended code that the gpt-engineer is trying to output... hope that makes sense.

**Comment by diegodp-zz** [comment]
I was having the same problem, I would run the code and it just create  the file all_output.txt in the folder workspace. I find this solution in another issue that makes sure it create some files in .py, but sincerely I wasn't able to create anything useful yet..
This maybe help you:
"copy and paste the contents of your all_output.txt to the bottom of the Main_prompt file; remove the "this is the basic structure of [...]" footer and any other redundant junk. modify the top of new main_prompt to include something along the lines of "prioritize completion of function implementations". go to [main]/indentity/ and edit "philosophy" and add a new top line like "ALWAYS Implements complete functions, and writes to file when coding classes and modules." - try again!"

**Comment by patillacode** [comment]
Especially with `gpt-3.5-turbo` sometimes files are not properly generated, there are many issues about this matter already, please continue the discussion there.

**Comment by mach7** [comment]
> I was having the same problem, I would run the code and it just create the file all_output.txt in the folder workspace. I find this solution in another issue that makes sure it create some files in .py, but sincerely I wasn't able to create anything useful yet.. This maybe help you: "copy and paste the contents of your all_output.txt to the bottom of the Main_prompt file; remove the "this is the basic structure of [...]" footer and any other redundant junk. modify the top of new main_prompt to include something along the lines of "prioritize completion of function implementations". go to [main]/indentity/ and edit "philosophy" and add a new top line like "ALWAYS Implements complete functions, and writes to file when coding classes and modules." - try again!"

Which issue did you find this in?
