### ISSUE TITLE
I have tried the example snake game 

### ISSUE THREAD

**Issue by diegodp-zz** [AntonOsika/gpt-engineer#138]
I could not make it work 
I first tried exactly the instructions in the readme page, except that I don't have access to chatgpt 4
 _`pip install -r requirements.txt
export OPENAI_API_KEY=[your api key] with a key that has GPT4 access
Run:

Fill in the main_prompt in your new folder
Run python -m gpt_engineer.main example`_

It didnt work , it finishes in a error: ValueError: too many values to unpack (expected 1), and it just make the file all_output.txt. 
I find some kind of solution in another issue and tried this: "copy and paste the contents of your all_output.txt to the bottom of the Main_prompt file; remove the "this is the basic structure of [...]" footer and any other redundant junk. modify the top of new main_prompt to include something along the lines of "prioritize completion of function implementations". go to [main]/indentity/ and edit "philosophy" and add a new top line like "ALWAYS Implements complete functions, and writes to file when coding classes and modules." - try again!"

Ok, now it creates a bunch of files 
<img width="367" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/6379927/f5ff9df3-e00a-4ee0-a623-6e1310573787">

But I am still getting errors, and it do not create the file snake.py, or I couldn't find anywhere
<img width="1217" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/6379927/0c9ca2bb-3671-405b-96d4-543ff9203aae">

if someone can help me to make it work, I would appreciate it.

**Comment by eduzol** [comment]
> 

I tried it with gpt3 (SPECIFICALLY gpt-3.5-turbo-16k-0613 , you can follow similar approach as in https://github.com/AntonOsika/gpt-engineer/pull/92 ) and failed too. 

i think its because we are using a less capable GPT 3 API, will defer to the experts in this forum.

**Comment by w3bdesign** [comment]
> > 
> 
> I tried it with gpt3 (SPECIFICALLY gpt-3.5-turbo-16k-0613 , you can follow similar approach as in #92 ) and failed too.
> 
> i think its because we are using a less capable GPT 3 API, will defer to the experts in this forum.

I have gotten it to run without any errors with that specific model, so it is not the model to blame.

Can you provide more info on how you are running the command?

For example, what OS, where are you running it from, do you have admin rights in the terminal, etc?

To me it sounds like it could be a permission issue.

**Comment by w3bdesign** [comment]
@diegodp-zz

**Comment by patillacode** [comment]
Hi @diegodp-zz 

I believe the error is very explicit in this case, there is no `requirements.txt` file

We are working to fix an issue where sometimes files are not properly generated, that is the case here, you can see how your workspace doesn't have the expected files, such as `requirements.txt`

There are other issues with more context, like #35, please discuss there since the original problem you have is that.
