### ISSUE TITLE
exporting the api key to the environment doesn't work for me

### ISSUE THREAD

**Issue by Emilprivate** [AntonOsika/gpt-engineer#14]
I can't get the export command to work, so an alternative solution like using an extern file or hardcoding the api in the code would be a nice solution. I personally created an external json config file and parsed the api key from that to the python script. 

So a solution could be:

1) Make a json file named "config.json"
2) Inside of ai.py add:
```
import json

def get_api_key(file_name: str) -> str:
    with open(file_name, 'r') as f:
        config = json.load(f)
    return config['openai_api_key']
```
    
3) Inside of config.json add: 
```
{
    "openai_api_key": "your_api_key"
}
```

4) In the __init__ part of the AI class add:
```
class AI:
    def __init__(self, **kwargs):
        openai.api_key = get_api_key("config.json")
        self.kwargs = kwargs
```

**Comment by ScorchChamp** [comment]
I created a PR where this issue can be resolved using .env variables. Please leave a comment under there if you think that would resolve your issue.

https://github.com/AntonOsika/gpt-engineer/pull/22

**Comment by MathisTimo** [comment]
that solved my issue, thanks

**Comment by IrmaEdmund** [comment]
that solved my issue, thanks

**Comment by blue27831** [comment]
i fixed my problem by using 
set: OPENAI_API_KEY=
instead of export 
worked for me =)

**Comment by navyfighter12** [comment]
> I created a PR where this issue can be resolved using .env variables. Please leave a comment under there if you think that would resolve your issue.
> 
> #22

This worked for me

**Comment by patillacode** [comment]
Open discussion about this in #135

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
