### ISSUE TITLE
The model `gpt-3` does not exist

### ISSUE THREAD

**Issue by logant314159** [AntonOsika/gpt-engineer#15]
The program exits with this error:
openai.error.InvalidRequestError: The model `gpt-3` does not exist

I was previously getting the same error for gpt-4, but it made sense since I don't have access to GPT4. I changed the line in main.py from
`model: str = "gpt-4",`
to
`model: str = "gpt-3",`

Any ideas?

**Comment by KiranPranay** [comment]
https://github.com/AntonOsika/gpt-engineer/issues/9#issuecomment-1589686156

**Comment by logant314159** [comment]
> [#9 (comment)](https://github.com/AntonOsika/gpt-engineer/issues/9#issuecomment-1589686156)

gpt 3.5 works. Is GPT3 just not offered...? Or is it called something else?

**Comment by universidadeUFPR** [comment]
have you found anything? how did you write the gpt 3.5 line in the main.py file?
I tried this but did not work: model: str = "gpt-3.5",

**Comment by logant314159** [comment]
The line has to be:
`model: str = "gpt-3.5-turbo"`

**Comment by jojo259** [comment]
https://platform.openai.com/docs/models/gpt-3-5

**Comment by bdfsght345** [comment]
en

**Comment by lazyprogrammerP** [comment]
If you need to use gpt-3, the mode name should be `text-davinci-003`

**Comment by logant314159** [comment]
> If you need to use gpt-3, the mode name should be `text-davinci-003`

Gotcha, thanks mate.
