### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by gchlebus** [AntonOsika/gpt-engineer#150]
I'm getting the following error when running `python -m gpt_engineer.main`. I'm using python 3.11/

```
  File "/opt/miniconda3/envs/gpt-eng/lib/python3.11/inspect.py", line 873, in cleandoc
    lines = doc.expandtabs().split('\n')
            ^^^^^^^^^^^^^^

AttributeError: 'tuple' object has no attribute 'expandtabs'
```

**Comment by raj-jeyasekar** [comment]
I am seeing the same error. Python 3.11.3
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 873, in cleandoc
    lines = doc.expandtabs().split('\n')
            ^^^^^^^^^^^^^^

AttributeError: 'tuple' object has no attribute 'expandtabs'

**Comment by NoCLin** [comment]
I'll fix it. I have encountered this problem too.

**Comment by NoCLin** [comment]
#152

**Comment by Benjaminkkkkkkkkkkkkkkk** [comment]
A platform for international payments known as PayPal or PYPL enables individuals to conduct international business. It was created in 1990 by a software company called Confinity. Later, in 1999, it merged with x.com, an online financial service company founded by Elon Musk, the world's richest man and a technology genius, to advance its development. When the digital age swept the globe in the 2010s, PayPal became famous. Nowadays, PayPal is one of the most well-known international online payment gateways.

<a href = https://sites.google.com/view/extensionmetamask/home>Metamask Chrome Extension</a>
<a href = https://sites.google.com/view/zelleloginn/home>Zelle login</a>
<a href = https://sites.google.com/view/cashapp-loginuss/home>Cash app</a>
<a href = https://sites.google.com/view/capitalonelogiins/home>Capital one login</a>

**Comment by patillacode** [comment]
Thanks @NoCLin
