### ISSUE TITLE
It only makes the structure of the code but doesn't fill the functions.

### ISSUE THREAD

**Issue by chrislovescoding** [AntonOsika/gpt-engineer#158]
![image](https://github.com/AntonOsika/gpt-engineer/assets/118455589/21a95296-9e49-4abc-83e1-182c9f14104a)
![image](https://github.com/AntonOsika/gpt-engineer/assets/118455589/8bc5cc8f-c682-41dd-bc1f-275fda91b72e)
![image](https://github.com/AntonOsika/gpt-engineer/assets/118455589/d582ce15-1446-4c13-b512-d209354c0576)
![image](https://github.com/AntonOsika/gpt-engineer/assets/118455589/6d5333cb-de23-4485-950b-6983e6ad204d)
![image](https://github.com/AntonOsika/gpt-engineer/assets/118455589/5148942b-7410-4c8f-8db5-1d96be00c53b)

It basically just creates the function names and expects me to fill it with the code that will make it work. Surely it should fill it itself.

**Comment by different55** [comment]
Have you tried running it again while crossing your fingers? Can't really control what the LLM decides to spit out except with luck.

**Comment by adriangalilea** [comment]
> Have you tried running it again while crossing your fingers? Can't really control what an AI decides to spit out except with luck.

This is correct, but I'm sure this can be "easily" solved.

Make a last step that checks if functions contains pass and ask you if you want it to be filled, or something like that.

**Comment by chrislovescoding** [comment]
> 

I tried running it 3 times. You should be able to solve it by telling gpt4 to create the actual functions and not leaving them blank.

**Comment by adriangalilea** [comment]
I'm sure that works, but what should happen really is that the code is inspected at the end and you can give new instructions, automatically checking if functions are blank would be handy.

I'm not sure how to implement embeddings here but would make sense possibly.

**Comment by abcdefghijorngarbosaxyz** [comment]
> Have you tried running it again while crossing your fingers? Can't really control what an AI decides to spit out except with luck.

I agree with this. AI does feed you some boilers. Must be clear in what your instructions are for them to do it.
