### ISSUE TITLE
poetry support

### ISSUE THREAD

**Issue by Vandivier** [AntonOsika/gpt-engineer#163]
hey! can i submit a pr for poetry support? i don't like to install packages globally, the lock file is cool too

**Comment by Vandivier** [comment]
also going to PR .env support as well

**Comment by patillacode** [comment]
As you can see in other issues, we are not going to use `poetry` in the near future.

Related comments:
https://github.com/AntonOsika/gpt-engineer/pull/96#issuecomment-1595799955
https://github.com/AntonOsika/gpt-engineer/pull/38#issuecomment-1593529145

**Comment by patillacode** [comment]
> also going to PR .env support as well
this is being discussed in #135 

Please share your opinion in there
