### ISSUE TITLE
Error message on every run

### ISSUE THREAD

**Issue by biscuitboost** [AntonOsika/gpt-engineer#167]
Only just installed so might be something I;m doing but any project I try to create is ending in this error

AssertionError: Generated entrypoint command that was not bash

There is a traceback to go with it which I have pasted below - is this a bug or normal?

Thanks
Robert

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/robertbrewer/gpt-engineer/gpt_engineer/main.py:58 in chat                                  │
│                                                                                                  │
│   55 │   )                                                                                       │
│   56 │                                                                                           │
│   57 │   for step in STEPS[steps_config]:                                                        │
│ ❱ 58 │   │   messages = step(ai, dbs)                                                            │
│   59 │   │   dbs.logs[step.__name__] = json.dumps(messages)                                      │
│   60                                                                                             │
│   61                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              ai = <gpt_engineer.ai.AI object at 0x7e2f60fec280>                              │ │
│ │         app_dir = PosixPath('.')                                                             │ │
│ │             dbs = DBs(                                                                       │ │
│ │                   │   memory=<gpt_engineer.db.DB object at 0x7e2f60fec6d0>,                  │ │
│ │                   │   logs=<gpt_engineer.db.DB object at 0x7e2f60fecee0>,                    │ │
│ │                   │   identity=<gpt_engineer.db.DB object at 0x7e2f60fec730>,                │ │
│ │                   │   input=<gpt_engineer.db.DB object at 0x7e2f60fec550>,                   │ │
│ │                   │   workspace=<gpt_engineer.db.DB object at 0x7e2f60fec8e0>                │ │
│ │                   )                                                                          │ │
│ │ delete_existing = None                                                                       │ │
│ │      input_path = PosixPath('projects/mjhelper')                                             │ │
│ │     memory_path = PosixPath('projects/mjhelper/memory')                                      │ │
│ │        messages = [                                                                          │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'system',                                                  │ │
│ │                   │   │   'content': 'You will get instructions for code to write.\nYou will │ │
│ │                   write a very long answer. '+1574                                           │ │
│ │                   │   },                                                                     │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': 'Instructions: We are writing an AI app with streamlit  │ │
│ │                   in python. \nMVC components'+193                                           │ │
│ │                   │   },                                                                     │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': 'Specification:\n\nSpecification for the AI             │ │
│ │                   Text-to-Image App\n\n1. Overview\nThe AI T'+2538                           │ │
│ │                   │   },                                                                     │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': 'Unit                                                   │ │
│ │                   tests:\n\n[requirements.txt]\n```\nstreamlit==1.2.0\nopenai==0.27.0\nlang… │ │
│ │                   │   },                                                                     │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'user',                                                    │ │
│ │                   │   │   'content': 'Please now remember the steps:\n\nThink step by step   │ │
│ │                   and reason yourself to the ri'+965                                         │ │
│ │                   │   },                                                                     │ │
│ │                   │   {                                                                      │ │
│ │                   │   │   'role': 'assistant',                                               │ │
│ │                   │   │   'content': '[main.py]\n```python\nimport streamlit as st\nfrom     │ │
│ │                   controller import Controller\nfro'+2616                                    │ │
│ │                   │   }                                                                      │ │
│ │                   ]                                                                          │ │
│ │           model = 'gpt-4'                                                                    │ │
│ │    project_path = 'mjhelper'                                                                 │ │
│ │      run_prefix = ''                                                                         │ │
│ │            step = <function gen_entrypoint at 0x7e2f60ff1790>                                │ │
│ │    steps_config = 'default'                                                                  │ │
│ │     temperature = 0.1                                                                        │ │
│ │         verbose = False                                                                      │ │
│ │  workspace_path = PosixPath('projects/mjhelper/workspace')                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/robertbrewer/gpt-engineer/gpt_engineer/steps.py:174 in gen_entrypoint                      │
│                                                                                                  │
│   171 │                                                                                          │
│   172 │   blocks = parse_chat(messages[-1]["content"])                                           │
│   173 │   for lang, _ in blocks:                                                                 │
│ ❱ 174 │   │   assert lang in [                                                                   │
│   175 │   │   │   "",                                                                            │
│   176 │   │   │   "bash",                                                                        │
│   177 │   │   │   "sh",                                                                          │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        _ = 'No readme'                                                                       │ │
│ │       ai = <gpt_engineer.ai.AI object at 0x7e2f60fec280>                                     │ │
│ │   blocks = [('README.txt', 'No readme')]                                                     │ │
│ │      dbs = DBs(                                                                              │ │
│ │            │   memory=<gpt_engineer.db.DB object at 0x7e2f60fec6d0>,                         │ │
│ │            │   logs=<gpt_engineer.db.DB object at 0x7e2f60fecee0>,                           │ │
│ │            │   identity=<gpt_engineer.db.DB object at 0x7e2f60fec730>,                       │ │
│ │            │   input=<gpt_engineer.db.DB object at 0x7e2f60fec550>,                          │ │
│ │            │   workspace=<gpt_engineer.db.DB object at 0x7e2f60fec8e0>                       │ │
│ │            )                                                                                 │ │
│ │     lang = 'README.txt'                                                                      │ │
│ │ messages = [                                                                                 │ │
│ │            │   {                                                                             │ │
│ │            │   │   'role': 'system',                                                         │ │
│ │            │   │   'content': 'You will get information about a codebase that is currently   │ │
│ │            on disk in the curre'+299                                                         │ │
│ │            │   },                                                                            │ │
│ │            │   {                                                                             │ │
│ │            │   │   'role': 'user',                                                           │ │
│ │            │   │   'content': 'Information about the                                         │ │
│ │            codebase:\n\n[main.py]\n```python\nimport streamlit as st\nfrom'+2649             │ │
│ │            │   },                                                                            │ │
│ │            │   {                                                                             │ │
│ │            │   │   'role': 'assistant',                                                      │ │
│ │            │   │   'content': '```bash\npython3 -m venv venv\nsource venv/bin/activate\npip  │ │
│ │            install -r requirement'+46                                                        │ │
│ │            │   }                                                                             │ │
│ │            ]                                                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Generated entrypoint command that was not bash

**Comment by AntonOsika** [comment]
We merged a new way to let the AI provide instructions to write to disk, which was unreliable.

Fixed now!

Apologies for the inconvenience.
