### ISSUE TITLE
Issues with writing file names

### ISSUE THREAD

**Issue by ssl** [AntonOsika/gpt-engineer#169]
Hi, great tool!

I just starting trying it, and I'm running into some issues. 

Initially, I was encountering the same problem as detailed in this issue: https://github.com/AntonOsika/gpt-engineer/issues/167. Fortunately, I noticed you fixed this and after pulling the changes, that issue was resolved.

However, I'm now facing another issue related to file name generation. The program is formatting file names as '`filename`':
![image](https://github.com/AntonOsika/gpt-engineer/assets/25695071/6fe9db63-3b14-481d-8182-8c8ed5e9f75f)

At other (most) times, it's formatting them as '[filename]', which is resulting in file outputs like this:

![image](https://github.com/AntonOsika/gpt-engineer/assets/25695071/801f1da0-6968-4001-9bba-882d0db40c42)

I suspect this might have something to do with this commit: https://github.com/AntonOsika/gpt-engineer/commit/8180f0346c8a380637b72212432aa9abd5c04a9c#diff-945067bb601867dd64fd5ae92de9bf829da8545700835ac49744902ddec355fd

I'm using gpt-3.5-turbo since I don't have access to gpt-4 yet. Maybe the model is not as smart to understand this prompt?

**Comment by AntonOsika** [comment]
Hey!

We had some issues, but should be addressed, could you see if you can pull the latest release and try again?

**Comment by ssl** [comment]
Hey Anton,

I'm on the latest commit. I also tried about ten times to re-do it, but it keeps on doing it.

**Comment by ShiroDN** [comment]
Hi, I can also confirm that files are saved to disk in the prompt format like '[app.py]', '[myapp.py]'. I am using GPT-3.5-turbo too.

**Comment by Millali-Ilyas** [comment]
I just got the same issue well. 

![image](https://github.com/AntonOsika/gpt-engineer/assets/55471966/263f43dd-2956-4e51-99b0-de8578c8848e)

Will get the latest commit and try again.

**Comment by ShiroDN** [comment]
It seems that file name generation is still somewhat random, at least for gpt-3.5-turbo. I just tried four runs, and I got the following results:

```
- app.py
- `app.py`
- missing files
```

If nobody has any other ideas, it appears that we will need to wait for https://github.com/AntonOsika/gpt-engineer/pull/94.

**Comment by alistairwalsh** [comment]
inside the identity folder I added these lines and it seemed to stop this behaviour
---------------------------------
don't include the back-tick symbol in filenames for python scripts, remove all back-ticks in filenames for python scripts that already exist in the "workspace" folder 

incorrect:
FILENAME: `data_loader.py`

correct:
FILENAME: data_loader.py

------------------------------------

**Comment by alistairwalsh** [comment]
> ## inside the identity folder I added these lines and it seemed to stop this behaviour
> don't include the back-tick symbol in filenames for python scripts, remove all back-ticks in filenames for python scripts that already exist in the "workspace" folder
> 
> incorrect: FILENAME: `data_loader.py`
> 
> correct: FILENAME: data_loader.py

- Sorry, it reverted back to the backticks on the next run so this doesn't work
-
