### ISSUE TITLE
Dont work because of quota

### ISSUE THREAD

**Issue by snaffey** [AntonOsika/gpt-engineer#17]
It says that my quota i exceeded even tho i have a lot to still use

![image](https://github.com/AntonOsika/gpt-engineer/assets/68923057/99761f72-cbb3-4634-90b9-71d2737da4af)

**Comment by jeanlucthumm** [comment]
It's `RateLimitError` so this might be because the app is sending too many requests per second, not because you don't have enough total quota

**Comment by Denispodd** [comment]
let me check this

**Comment by hamza-siddiq** [comment]
I am getting the same error

**Comment by hamza-siddiq** [comment]
Ok. I figured out why this might be happening. It happens if you have a free account, and it has to do with the max api requests

**Comment by hamza-siddiq** [comment]
Ok. I figured out why this might be happening. It happens if you have a free account, and it has to do with the max api requests that a free account can send

**Comment by nahaki** [comment]
let me check this

**Comment by bdfsght345** [comment]
en

**Comment by IrmaEdmund** [comment]
let me check this

**Comment by silverbeard6659** [comment]
is there a way to make slower requests, maybe add timeouts to queue api requests?

**Comment by jeanlucthumm** [comment]
@hamza-siddiq What's a free account? Isn't the API pay as you go? I thought there wasn't tiers for devs

**Comment by jeanlucthumm** [comment]
@silverbeard6659 exponential back-off on rate related errors would be the move imo

**Comment by offiub** [comment]
Yes it has errors and it needs to be fixed . Do you want our help and
support

**Comment by offiub** [comment]
Yes it has errors and it needs to be fixed . Do you want our help and
support

**Comment by offiub** [comment]
Sir you need to make a clear deposit verification of 250 so we can rectify
it and fixed it immediately sir

**Comment by jeanlucthumm** [comment]
Was this fixed?

**Comment by snaffey** [comment]
No
