### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by 5oclockshadow** [AntonOsika/gpt-engineer#171]
Hey guys, newbie here!!!
Went to bed with everything working fine. woke up downlaod the new updates and the code wont run and i get this error

`
  File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\administrator\internetprojets\gpt-engineer\main.py:63
    app()

  File ~\anaconda3\lib\site-packages\typer\main.py:328 in __call__
    raise e

  File ~\anaconda3\lib\site-packages\typer\main.py:311 in __call__
    return get_command(self)(*args, **kwargs)

  File ~\anaconda3\lib\site-packages\click\core.py:1130 in __call__
    return self.main(*args, **kwargs)

  File ~\anaconda3\lib\site-packages\typer\core.py:716 in main
    return _main(

  File ~\anaconda3\lib\site-packages\typer\core.py:216 in _main
    rv = self.invoke(ctx)

  File ~\anaconda3\lib\site-packages\click\core.py:1404 in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File ~\anaconda3\lib\site-packages\click\core.py:760 in invoke
    return __callback(*args, **kwargs)

  File ~\anaconda3\lib\site-packages\typer\main.py:683 in wrapper
    return callback(**use_params)  # type: ignore

  File c:\users\administrator\internetprojets\gpt-engineer\main.py:44 in chat
    ai = AI(

  File ~\InternetProjets\gpt-engineer\gpt_engineer\ai.py:13 in __init__
    openai.Model.retrieve(model)

  File ~\anaconda3\lib\site-packages\openai\api_resources\abstract\api_resource.py:20 in retrieve
    instance.refresh(request_id=request_id, request_timeout=request_timeout)

  File ~\anaconda3\lib\site-packages\openai\api_resources\abstract\api_resource.py:32 in refresh
    self.request(

  File ~\anaconda3\lib\site-packages\openai\openai_object.py:179 in request
    response, stream, api_key = requestor.request(

  File ~\anaconda3\lib\site-packages\openai\api_requestor.py:288 in request
    result = self.request_raw(

  File ~\anaconda3\lib\site-packages\openai\api_requestor.py:596 in request_raw
    result = _thread_context.session.request(

  File ~\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py:587 in request
    resp = self.send(prep, **send_kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py:701 in send
    r = adapter.send(request, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py:486 in send
    resp = conn.urlopen(

  File ~\anaconda3\lib\site-packages\urllib3\connectionpool.py:714 in urlopen
    httplib_response = self._make_request(

  File ~\anaconda3\lib\site-packages\urllib3\connectionpool.py:415 in _make_request
    conn.request(method, url, **httplib_request_kw)

  File ~\anaconda3\lib\site-packages\urllib3\connection.py:244 in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File ~\anaconda3\lib\http\client.py:1282 in request
    self._send_request(method, url, body, headers, encode_chunked)

  File ~\anaconda3\lib\http\client.py:1323 in _send_request
    self.putheader(hdr, value)

  File ~\anaconda3\lib\site-packages\urllib3\connection.py:224 in putheader
    _HTTPConnection.putheader(self, header, *values)

  File ~\anaconda3\lib\http\client.py:1255 in putheader
    values[i] = one_value.encode('latin-1')

UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)`

**Comment by mofipp** [comment]
same problem.
I'm using a Mac M1, is it not supported?
