### ISSUE TITLE
Doesn't quite work right on windows: tries to run .sh file

### ISSUE THREAD

**Issue by YEM-1** [AntonOsika/gpt-engineer#182]
```
Do you want to execute this code?
If yes, press enter. Otherwise, type "no"


Executing the code...

run.sh: /mnt/c/Users/jeff/.pyenv/pyenv-win/shims/pip: /bin/sh^M: bad interpreter: No such file or directory
run.sh: line 2: $'\r': command not found
run.sh: line 3: syntax error near unexpected token `<'
'un.sh: line 3: `python main.py <file_path> <column_name> <output_file_path>
```

I even told it in the prompt: this is running on windows.  Do not give me shell commands that windows cannot execute.  Yet is still generated run.sh and tried to run it.

**Comment by YEM-1** [comment]
Also, all_output.txt is created with a lot of python code, but no .py files were created at all.

**Comment by augusto-rehfeldt** [comment]
+1

**Comment by softjuarez** [comment]
Same problem here!

**Comment by mach7** [comment]
| +-------------------------------------------------------------------------+ |
+-----------------------------------------------------------------------------+
AssertionError: Generated entrypoint command that was not bash


If this is the problem you guys are getting then I'm getting it too.

**Comment by jebarpg** [comment]
I made a proposal here: https://github.com/AntonOsika/gpt-engineer/pull/123#discussion_r1233150492
@AntonOsika @patillacode

**Comment by nospoon** [comment]
I'm having similar issues on macOS. The file generation seems to be completely broken, it creates files like `[controller.py]` or `[view.py]` which are not actual python files, then it tries to execute and fails.
