### ISSUE TITLE
How to set base URL?

### ISSUE THREAD

**Issue by thetechguy-cpu** [AntonOsika/gpt-engineer#183]
Hi,
I'm on windows on the stable version. Is there a way to set the Base URL for the OpenAI API?

**Comment by yhyu13** [comment]
Checkout my fork here https://github.com/yhyu13/gpt-engineer/tree/local_dev

**Comment by NoCLin** [comment]
set env `OPENAI_API_BASE` manually or add `os.environ["OPENAI_API_BASE"] = "https://xxx.com/v1"` before `import openai`

**Comment by mach7** [comment]
> Checkout my fork here https://github.com/yhyu13/gpt-engineer/tree/local_dev

Is this forked from version 0.0.1?

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
