### ISSUE TITLE
Documentation and API Reference Guide

### ISSUE THREAD

**Issue by amjadraza** [AntonOsika/gpt-engineer#184]
Feature: Enhancement 

Adding Documentation and API guide. I propose two frameworks 

A. Using Pythonic Sphnix Framework and deploying on the `readthedocs` server

1. Open Source, comes with many themes / templates
2. Extensively used for Python Packages e.g LangChain API is using the `readthedocs` template of Sphnix
3. Have support of `.rst` , `.mk` and much more formats

B. Using `mkdocs`  framework 
1. Light framework based on Python, Pandas-ai is using this
2. Support MarkDown files 
3. Comes with `material` and `readthedocs` templates. 

C. Using Vercel Documentations
1. https://nextra-docs-template.vercel.app/
2. API reference guide still using Sphnix
3. LangChain is using this platform too

DocString Styles: AMong many docstrings styles, Google Style is very famous and easy to implement. 

It is important to decide on Documentation Especially Docstrings early on to generate the API reference Guide professionally. Re-Factoring a huge code base with Docstring is a huge job. 

>I can contribute to this feature.

**Comment by amjadraza** [comment]
@AntonOsika please review. We require the docs for trying it out a bit better.

**Comment by amjadraza** [comment]
@AntonOsika , should we add this part of the Roadmap? I think we should keep following any feature/suggestion if that is part of Roadmap and let the community decide which features we should put our efforts on.

**Comment by amjadraza** [comment]
@AntonOsika following up on our discussion on adding docs, Please read above issue and comment. I cant make a PR with mutually decided pathway of adding docs.

**Comment by AntonOsika** [comment]
Would love to hear what people think would be the best alternative. What do you think?
