### ISSUE TITLE
A way to continue when it stops?

### ISSUE THREAD

**Issue by zerofill** [AntonOsika/gpt-engineer#19]
Is there a way to have it continue where it left off?
Using gpt3.5-turbo

But when it is creating the files, it will finish in the middle of creating a file.
Typically you can tell ChatGPT to continue. Is there a method to do that?

**Comment by NoahToby1** [comment]
oh

**Comment by IrmaEdmund** [comment]
good

**Comment by gartlans** [comment]
+1

**Comment by jebarpg** [comment]
+1

**Comment by deronkel82** [comment]
+1

**Comment by augusto-rehfeldt** [comment]
+1

**Comment by w3bdesign** [comment]
Try changing the model to gpt-3.5-turbo-16k as it can handle more than the regular gpt-3.5-turbo model.

**Comment by zerofill** [comment]
Yeah that is what I am trying now, to see what happens.

**Comment by manoocher** [comment]
+1

**Comment by alexk1919** [comment]
I have been testing your app with a complex prompt. ChatGPT returns only a few files saying that the app is too complex and will need to continue writing the app after it's initial results. 

That would require ChatGPT to see the files it has already written and continue writing the app, almost like a AutoGPT feature.

Is that something you can do?

**Comment by Ceilo** [comment]
you need to use the API to create multiple instance request to call back the last input message with a whole list of messages as a format.

Example: 

```py
 import openai

openai.api_key = 'YOUR_API_KEY'

def continue_chat(prompt, messages):
    response = openai.Completion.create(
        engine='davinci-codex',  # Use gpt3.5-turbo for shorter response times
        prompt=prompt,
        messages=messages,
        max_tokens=50  # Adjust the value as per your requirements for your GPT
    )
    return response.choices[0].text.strip()

prompt = "continue chat returns input to prompts/messages"
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "What happens next?"},
]

response = continue_chat(prompt, messages)
print(response


```

The `continue_chat` function now takes messages and prompts and messages as input values then returns them as a generated response .then for messages=messages, you can make a list of generated callbacks/answers/ to continue the conversation.


Now your GPT has the ability to continue  the conversation where its left off. ( Just don't be like me and try to give it ethical philosphies to take over the world..) - (TROLLING)

hope this helps all you though - if you have any questions feel free to ask. I have an updated GPT-engineer i'll be adding here soon which is a lot cleaner and has error handling with a few other features that were missing imo from most GPT-engineers I've seen on here so far from people. APPRECIATE ALL THE COOL STUFF EVERYONE DOES GOD BLESS YALL <3

**Comment by AntonOsika** [comment]
Feel free to add to ideas in discussions
