### ISSUE TITLE
Create a new "--steps-config" that runs a loop and asks for feedback in the end and feeds it back to GPT Engineer to fix

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#190]
I think the "catch KeyboardInterrupt" in scripts/benchmark.py is a good pattern for being able to shut down the run, so that it goes to the "ask for input" step

**Comment by hackpk** [comment]
@AntonOsika Can I work on this?

**Comment by AntonOsika** [comment]
@hackpk would love your help

Right now, you need an API key to run it

**Comment by AntonOsika** [comment]
Right now, you need an API key to run it

@hackpk would love your help, are you up for it?

**Comment by hackpk** [comment]
@AntonOsika I do love to work but I have 3.5 gpt API's Key which is not working for me. I'm getting below issue
when i run this
$ gpt-engineer projects/React_App

INFO:openai:error_code=model_not_found error_message="The model 'gpt-4' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Model gpt-4 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api

INFO:openai:error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
WARNING:langchain.callbacks.manager:Error in StreamingStdOutCallbackHandler.on_retry callback: 'StreamingStdOutCallbackHandler' object has no attribute 'on_retry'
INFO:openai:error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
