### ISSUE TITLE
Is this safe to use on macOS 14 beta?

### ISSUE THREAD

**Issue by transat** [AntonOsika/gpt-engineer#191]
I’m asking because my finder crashed after I tried to build/run the generated Swift files and have not been able to regain control (even in safe mode). Could be unrelated but thought I’d check!

**Comment by yhyu13** [comment]
What does it build?

**Comment by patillacode** [comment]
Hi @transat 

We are not responsible for:
1 -  the output generated by your prompt
2 - running "random files" in your computer

Having said that, what did you prompt? what did you run?

**Comment by transat** [comment]
Thanks. I’m aware of the risks and I just asked for a simple SpriteKit game. It’s most likely unrelated but thought I’d mention it just in case. I noticed the filenames that were output by gpt engineer started and ended with a bracket, which is rather unconventional. So I was wondering if some strange edge case like this could have messed with the finder.
