### ISSUE TITLE
Is there any way to run this with gpt3.5 api?

### ISSUE THREAD

**Issue by Edward7n15** [AntonOsika/gpt-engineer#193]
Just wondering if it is a gpt4-only tool.

**Comment by yhyu13** [comment]
just change the code from 'gpt-4' to 'gpt-3.5-turbo'

**Comment by Edward7n15** [comment]
> just change the code from 'gpt-4' to 'gpt-3.5-turbo'

Hi Yu. Could you tell me where is the config file? Thanks.

**Comment by Edward7n15** [comment]
> just change the code from 'gpt-4' to 'gpt-3.5-turbo'

nvm, thanks for reply!

**Comment by ScholliYT** [comment]
I guess you can also use the CLI flag `--model "gpt-3.5-turbo"` with the gpt-engineer command: `gpt-engineer --model "gpt-3.5-turbo" project/`
