### ISSUE TITLE
Missing a few module requirements

### ISSUE THREAD

**Issue by dumityty** [AntonOsika/gpt-engineer#195]
Not sure whether I've done something wrong at the beginning or some new modules have been added and the requirements file not updated?

I ran `pip install -r requirements.txt` and it installed all the packages without issues.

Then running `gpt-engineer` I got the following error 3 times for each module name - `ModuleNotFoundError: No module named X`:
- idna
- six
- certifi

Running `pip install idna` etc after each error fixed it and was able to finally run `gpt-engineer`. Do they need to be added to the requirements.txt file?

Python version: 3.10

**Comment by carlthome** [comment]
Which Python version are you using?

**Comment by dumityty** [comment]
Sorry should've mentioned - initially 3.8 but had some errors and following recommendation from someone in another issue i upgraded to 3.10

**Comment by carlthome** [comment]
As far as I understood this repo yesterday, it actually assumes 3.10 as its minimum version (type literals, for example) so that might be the best forward. If that resolves your issue, please ping and close this out!

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
