### ISSUE TITLE
SET OPENAI_API_KEY

### ISSUE THREAD

**Issue by hierro** [AntonOsika/gpt-engineer#196]
Im using windows and export command is not valid to set the apikey, i tried set, but it looks like it doesnt work either, any suggestions ?

**Comment by dineshtamang14** [comment]
setting environmental variable in windows through cmd

set OPENAI_API_KEY=asdkjfklsjf234348dsfkj

**Comment by subnwa** [comment]
I tried this but still getting `openai.error.AuthenticationError` error

**Comment by hierro** [comment]
set the variable as user variable in windows :
https://www.immersivelimit.com/tutorials/adding-your-openai-api-key-to-system-environment-variables

and make sure to restat windows

that worked for me

**Comment by hierro** [comment]
Set the variable as user variable:https://www.immersivelimit.com/tutorials/adding-your-openai-api-key-to-system-environment-variables, and restart windows.
Working for me but giving error in gtp3-5 fallback

**Comment by subnwa** [comment]
its worked, thanks!

**Comment by Cipher-08** [comment]
Me too

**Comment by optimaaa** [comment]
WSL-2 fixes this. Only GPT-4 seems to be working.

**Comment by subnwa** [comment]
> WSL-2 fixes this. Only GPT-4 seems to be working.

should i run it over wsl?

**Comment by subnwa** [comment]
For some reason, making a small change to the command block in the main.py file fixed the problem.

Before:
```python
if __name__ == "__main__":
    app()
```

After:
```python
if __name__ == "__main__":
    app.run()
```

really interesting 😸

**Comment by evilvolatile** [comment]
There are two steps to follow exactly  as mentioned by @subnwa 
making a small change to the command block in the main.py .

**FIRST:**

Before:
```
if __name__ == "__main__":
    app()
```

After:
```
if __name__ == "__main__":
    app.run()
```

**Second::**
Follow the instructions to add an environment variable in WINDOWS 
https://www.immersivelimit.com/tutorials/adding-your-openai-api-key-to-system-environment-variables
