### ISSUE TITLE
Pass a flag in run command to keep the generated code hidden

### ISSUE THREAD

**Issue by ayush-vibrant** [AntonOsika/gpt-engineer#20]
Hey, I was thinking that we should add an optional flag to the run command. This flag would allow us to hide the generated code on the terminal. By doing so, the terminal output would appear cleaner, and the reader could easily understand what is happening just by reading the output. Currently, with both the code and instructions displayed, it looks cluttered.

That being said, if someone wants the code to be printed, it can still be displayed based on the flag value.

**Comment by nahaki** [comment]
thank you

**Comment by ayush-vibrant** [comment]
Let me know if I can help in implementing this.

**Comment by bdfsght345** [comment]
good

**Comment by NoahToby1** [comment]
Let me know if I can help in implementing this.

**Comment by IrmaEdmund** [comment]
good

**Comment by marieudb** [comment]
thank you

**Comment by patillacode** [comment]
I believe this to be a good idea.

Please @ayush-vibrant fell free to provide a PR with this functionality.

I would suggest as inspiration something like `--v`/`--vv`/`--vvv` like many commands do to set the level of verbosity

If not that, maybe  approaching it from "the other side" with an option such as `--quiet`
Making the output very populated by default and if you provide this option then the output is fairly restricted.

cc @AntonOsika thoughts?

**Comment by VijayKalmath** [comment]
@patillacode  Looks like you removed yourself from this issue, Is this issue open to be picked up?

**Comment by patillacode** [comment]
Hello @VijayKalmath 

Please feel free to pick this up.

**Comment by ayush-vibrant** [comment]
@VijayKalmath Are you picking this up?

**Comment by patillacode** [comment]
I wish I had one!!!

Also, giving a key to a stranger would not be recommended 😉

**Comment by ayush-vibrant** [comment]
Hahah @patillacode that's true. A man can try though!

But I see that @VijayKalmath has raised a PR. That's so cool.

**Comment by AntonOsika** [comment]
Hm I definitely think logging the code is worth it. Otherwise it's just "not doing anything" for a very long time.

Happy to have this reopened if someone has a good argument. Do not agree with "clutter" being sufficiently strong!

**Comment by AntonOsika** [comment]
Closing for now 🏃
