### ISSUE TITLE
File name is not correct

### ISSUE THREAD

**Issue by jjhesk** [AntonOsika/gpt-engineer#211]
The generated py files is not named correct. 
It got the extra symbol `]` in the file extension name. 
<img width="483" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/629338/8e57a119-36bc-4c6a-baa5-7d6fac82bc72">

**Comment by hellin-eth** [comment]
I had the same issue,
i added `Be sure that the filenames are well formated using the name conventions best practice and include the right file extension.` promt at the end of 'generate' agent, located in gpt_engineer\identity\generate
