### ISSUE TITLE
No asking for clarification in qa agent

### ISSUE THREAD

**Issue by hellin-eth** [AntonOsika/gpt-engineer#213]
Maybe it is because i dont have openai api for the gpt4 model, 
but even changing the identity agent 'qa' to: 
`Then you will pick one clarifying question, and wait for an answer from the user.
Even if there is no need of clarification, wait for the answer from the user.`

there is no clarification asking. 
Maybe I am doing something wrong?

**Comment by AntonOsika** [comment]
Did you append `--steps-config clarify`?

**Comment by LeonardoIBO** [comment]
When i answer the clarification questions for some reason it just outputs a "No" back again and continues with the process. It's kinda funny but probably not expected behavior. Any idea why this is happening?

**Comment by hellin-eth** [comment]
> 

No, i haven't! 
I thought it was a feature, not a execution parameter.
Thanks a lot, this project is funny as f***!!

I'll close this issue, as a problem between keyboard and chair.

**Comment by flrivera** [comment]
> Did you append `--steps-config clarify`?

where do we append this, when running gpte projects/example gpt-3.5-turbo-0613 ?

**Comment by ATheorell** [comment]
@flrivera 

try gpte projects/example gpt-3.5-turbo-0613 -c

BUT, sometimes the LLM (in particular 3.5) decides that the instructions are clear enough and doesn't ask questions.
