### ISSUE TITLE
whats a good way to enable GPT-4 to use latest docs?

### ISSUE THREAD

**Issue by starascendin** [AntonOsika/gpt-engineer#216]
Hi friends,

As we all know, gpt's knowledge cutoff is in 2021 and it does not have all the latest docs of frameworks. Is there a way to mitigate this by updating it with custom docs?

**Comment by patillacode** [comment]
I would say that is out of the scope of this application.

You are describing a ChatGPT plugin that searches the internet basically or allows you to update documents.
Anyway, that would be on Open AI's side not ours if I correctly understand your comment.
