### ISSUE TITLE
No Implementation, empty skeletons

### ISSUE THREAD

**Issue by fblgit** [AntonOsika/gpt-engineer#218]
This aint producing code itself.
Full of sketches and skeletons with nearly no code.. no implementation.

Has anyone got an app build by this? I cant resume a project, and the benchmarks most of them are literally not working..

**Comment by patillacode** [comment]
Already discussed in #101 

Long story short, your prompt might be a bit weird, or your clarifications, I don't know. Anyway, Chat GPT isn't perfect, sometimes things don't get returned as you would expect.

Please create a new issue with your problem explained in the most explicit way possible, with example and we will try to help you.
