### ISSUE TITLE
FileNotFoundError on last clarrifying question by gpt-engineer

### ISSUE THREAD

**Issue by promptDeveloper** [AntonOsika/gpt-engineer#232]
I went through all of the clarifying questions and at the final step it just errored out with the following message. I also noticed that I don't possess the setup file/folder in the identities subfolder, that's what the last line of the error message states. 

What should I do here?
<img width="572" alt="Screen Shot 2023-06-19 at 5 13 13 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/f77b72ad-ba15-414e-ae0f-abf5c8a06de9">

**Comment by juarezjl** [comment]
try `pip install -e .` in the folder with the pyproject.toml

**Comment by promptDeveloper** [comment]
hey where can I find that .toml file? My error message states that I don't have the 'setup' file in the identity subfolder.
<img width="576" alt="Screen Shot 2023-06-19 at 5 36 50 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/086b8aad-09db-40c9-8dc6-881ebbaf45d5">

**Comment by promptDeveloper** [comment]
Actually I got gpt-engineer to write me an app.py file, but I am having trouble running it. Here is the error message I get. 
<img width="785" alt="Screen Shot 2023-06-19 at 5 50 34 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/68f95c73-fb5c-47c2-8a82-113bc851ca49">
Also, I wasn't able to run the pip install --user -r requirements.txt command because I got the following error message. Could these have been reason for python app.py not running?

**Comment by juarezjl** [comment]
you need to clone the project like in the instructions

```
Usage
Choose either stable or development.

For stable release:

pip install gpt-engineer
For development:

git clone git@github.com:AntonOsika/gpt-engineer.git
cd gpt-engineer
make install
source venv/bin/activate
Setup

With an api key that has GPT4 access run:

export OPENAI_API_KEY=[your api key]
Run:

Create an empty folder. If inside the repo, you can run:
cp -r projects/example/ projects/my-new-project
Fill in the main_prompt file in your new folder
Run: gpt-engineer projects/my-new-project
Results

Check the generated files in projects/my-new-project/workspace
```

**Comment by promptDeveloper** [comment]
I was able to get my music player interface up and running, and the Browse button lets me look for a local mp3 file, but doesn't let me actually select it, all of the files (including mp3) are greyed out, as the image shows. Is it possible for gpt-engineer to work on multiple iterations of the same product, improving it in every way possible with multiple prompts?

<img width="394" alt="Screen Shot 2023-06-19 at 7 59 28 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/a3cd32dc-8c22-4070-b49f-26ce32f49f81">
<img width="801" alt="Screen Shot 2023-06-19 at 7 59 57 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/acbd1910-e6e8-4276-b47f-86de5fa2c8f1">

**Comment by promptDeveloper** [comment]
I was able to fix the problem of the mp3 file not being selectable, but now once I select it, it returns me this error.
<img width="1139" alt="Screen Shot 2023-06-19 at 8 15 34 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/27a92cd3-1df1-4739-a81b-f9f580c099b4">
