### ISSUE TITLE
Unable to run app.py after gpt-engineer creates it

### ISSUE THREAD

**Issue by promptDeveloper** [AntonOsika/gpt-engineer#233]
I am getting the following error message when I try to run the app.py file gpt-engineer wrote, but I am having trouble running it. 
<img width="785" alt="Screen Shot 2023-06-19 at 5 50 34 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/68f95c73-fb5c-47c2-8a82-113bc851ca49">
Also, I wasn't able to run the pip install --user -r requirements.txt command because I got the following error message. Could these have been reason for python app.py not running?
<img width="568" alt="Screen Shot 2023-06-19 at 5 49 10 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/a48f1d0c-8b95-4362-b0ba-0b7ff1845ba1">

**Comment by juarezjl** [comment]
try this 

```
go to the folder you want the files to be. 

git clone https://github.com/AntonOsika/gpt-engineer.git

cd {your_project_folder}/gpt-engineer
pip install gpt-engineer
pip install -e .

export OPENAI_API_KEY=[your api key]

cp -r projects/example/ projects/my-new-project
Fill in the main_prompt file in your new folder

Make sure you are in {your_project_folder}/gpt-engineer folder
Run: gpt-engineer projects/my-new-project

Check the generated files in projects/my-new-project/workspace
```

**Comment by promptDeveloper** [comment]
There's a comment that says my Python may not be configured with Tk, which python version will be configured with Tk? 
<img width="582" alt="Screen Shot 2023-06-19 at 6 39 55 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/e53bb47b-7f8b-4500-9185-aa4df8de5bb8">

**Comment by juarezjl** [comment]
by any chance you are trying to run a game example using pygame ina vbox env ? Otherwise you are missing some dependecies need it to run your app.py (pygame)

**Comment by promptDeveloper** [comment]
no i'm trying to run the simple GUI that I hope gpt-engineer made for me that allows users to slow/speed up songs and add bass to them. What other dependencies should I have then? Here is the following error I'm running into as well
<img width="776" alt="Screen Shot 2023-06-19 at 6 54 33 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/4b8599b9-bc56-4c23-86b1-f2952b6b9e6c">

**Comment by promptDeveloper** [comment]
I'm also not sure if I'm in a vbox env, what env should I be in?

**Comment by promptDeveloper** [comment]
So there is a subdirectory called 'venv' under which my workspace directory is under. Also the error I am currently facing is this one, any thoughts?
<img width="580" alt="Screen Shot 2023-06-19 at 7 05 18 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/40a207e3-9edd-416e-b23f-43278b04a0ad">

**Comment by juarezjl** [comment]
again you are missing dependecies for your app.py is not gpt-engineer.
here is a post that might help https://github.com/jiaaro/pydub/issues/348
or you can try this based on your error : 
```
pip install ffmpeg-downloader
ffdl install --add-path
```

**Comment by promptDeveloper** [comment]
i wrote the two above commands you gave me, should I have written my own path where you listed add-path (would that be the path that app.py is in?). They both installed, and here is the error I am currently facing even after restarting my terminal 
<img width="569" alt="Screen Shot 2023-06-19 at 7 17 29 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/136762242/f69482dd-f541-4056-95ba-7f0d78ed5351">

**Comment by AntonOsika** [comment]
Should work now
