### ISSUE TITLE
openai key

### ISSUE THREAD

**Issue by ether8unny** [AntonOsika/gpt-engineer#237]
how do i manually edit my api key?

**Comment by jakubmatej** [comment]
Hi, possible workaround is by editing the <ai.py> file in gpt-engineer package library. Path of the package is shown in error message of no API key provided.
Add new line (e.g. 6): openai.api_key="YOUR-KEY"

**Comment by zvey** [comment]
I am getting this error openai.error.AuthenticationError: Incorrect API key provided: sk-90Ho5*************************************zf9J. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by jakubmatej** [comment]
@zvey
openai.api_key accepts only string. Put your API key in between quotes "..."

**Comment by rijfas** [comment]
May be add an option to load the key from .env on openai.error.AuthenticationError?, if assigned, i can work on that :wink:

**Comment by BoltR6** [comment]
> how do i manually edit my api key?

Insert the following code on line 6:
`openai.api_key="example-key-894710293870198234"`



> I am getting this error openai.error.AuthenticationError: Incorrect API key provided: sk-90Ho5*************************************zf9J. You can find your API key at https://platform.openai.com/account/api-keys.

Visit the provided [link](https://platform.openai.com/account/api-keys) and verify your key exists and that it's not expired. If you see no keys, create a new one.

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
