### ISSUE TITLE
 'bash' is not recognized 

### ISSUE THREAD

**Issue by Andree100** [AntonOsika/gpt-engineer#248]
I'm on Windows and just installed and run script. It created a "application plan" and asked if want to execute. Pressed Enter. I seems it has created the structure and files. But I haven't get any "clarification questions": And here's the result in console. 

If yes, press enter. Otherwise, type "no"

Executing the code...

'bash' is not recognized as an internal or external command,
operable program or batch file.
PS D:\GameDev\Pyton\gpt-engineer>

**Comment by patillacode** [comment]
steps are now optional, use the `--steps` parameter:
```
$ gpt-engineer --help
```
