### ISSUE TITLE
OPENAI_API_KEY

### ISSUE THREAD

**Issue by Niutonian** [AntonOsika/gpt-engineer#251]
Hello, I've been trying to use setup GptEngineer, but I can't get paste the openAI API KEY setup.
I have tried 
- SET OPENAI... trough command window
- import openai... key in main.py
- import openai... key in ai.py
none of it worked, I'm on a PC btw.
Here is the error I get:
-------------------------------------------------------------------------------------------------------------------

'''''┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gpt_engineer\main.py:44 │
│ in main                                                                                          │
│                                                                                                  │
│   41 │   │   shutil.rmtree(memory_path, ignore_errors=True)                                      │
│   42 │   │   shutil.rmtree(workspace_path, ignore_errors=True)                                   │
│   43 │                                                                                           │
│ > 44 │   ai = AI(                                                                                │
│   45 │   │   model=model,                                                                        │
│   46 │   │   temperature=temperature,                                                            │
│   47 │   )                                                                                       │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │ delete_existing = False                                                                      │ │
│ │      input_path = WindowsPath('C:/Users/Admin/AI/GptEngineer/gpt-engineer/projects/i2s_micr… │ │
│ │     memory_path = WindowsPath('C:/Users/Admin/AI/GptEngineer/gpt-engineer/projects/i2s_micr… │ │
│ │           model = 'gpt-4'                                                                    │ │
│ │    project_path = 'projects/i2s_microphone'                                                  │ │
│ │      run_prefix = ''                                                                         │ │
│ │    steps_config = 'default'                                                                  │ │
│ │     temperature = 0.1                                                                        │ │
│ │         verbose = False                                                                      │ │
│ │  workspace_path = WindowsPath('C:/Users/Admin/AI/GptEngineer/gpt-engineer/projects/i2s_micr… │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gpt_engineer\ai.py:13   │
│ in __init__                                                                                      │
│                                                                                                  │
│   10 │   │   self.temperature = temperature                                                      │
│   11 │   │                                                                                       │
│   12 │   │   try:                                                                                │
│ > 13 │   │   │   openai.Model.retrieve(model)                                                    │
│   14 │   │   │   self.model = model                                                              │
│   15 │   │   except openai.InvalidRequestError:                                                  │
│   16 │   │   │   print(                                                                          │
│                                                                                                  │
│ ┌──────────────────────────── locals ─────────────────────────────┐                              │
│ │       model = 'gpt-4'                                           │                              │
│ │        self = <gpt_engineer.ai.AI object at 0x0000024E2D000700> │                              │
│ │ temperature = 0.1                                               │                              │
│ └─────────────────────────────────────────────────────────────────┘                              │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\ab │
│ stract\api_resource.py:20 in retrieve                                                            │
│                                                                                                  │
│    17 │   │   cls, id, api_key=None, request_id=None, request_timeout=None, **params             │
│    18 │   ):                                                                                     │
│    19 │   │   instance = cls(id=id, api_key=api_key, **params)                                   │
│ >  20 │   │   instance.refresh(request_id=request_id, request_timeout=request_timeout)           │
│    21 │   │   return instance                                                                    │
│    22 │                                                                                          │
│    23 │   @classmethod                                                                           │
│                                                                                                  │
│ ┌─────────────────────────── locals ───────────────────────────┐                                 │
│ │         api_key = None                                       │                                 │
│ │             cls = <class 'openai.api_resources.model.Model'> │                                 │
│ │              id = 'gpt-4'                                    │                                 │
│ │        instance = <Model id=gpt-4 at 0x24e2cff7d80> JSON: {  │                                 │
│ │                     "id": "gpt-4"                            │                                 │
│ │                   }                                          │                                 │
│ │          params = {}                                         │                                 │
│ │      request_id = None                                       │                                 │
│ │ request_timeout = None                                       │                                 │
│ └──────────────────────────────────────────────────────────────┘                                 │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\ab │
│ stract\api_resource.py:32 in refresh                                                             │
│                                                                                                  │
│    29 │                                                                                          │
│    30 │   def refresh(self, request_id=None, request_timeout=None):                              │
│    31 │   │   self.refresh_from(                                                                 │
│ >  32 │   │   │   self.request(                                                                  │
│    33 │   │   │   │   "get",                                                                     │
│    34 │   │   │   │   self.instance_url(),                                                       │
│    35 │   │   │   │   request_id=request_id,                                                     │
│                                                                                                  │
│ ┌────────────────────────── locals ───────────────────────────┐                                  │
│ │      request_id = None                                      │                                  │
│ │ request_timeout = None                                      │                                  │
│ │            self = <Model id=gpt-4 at 0x24e2cff7d80> JSON: { │                                  │
│ │                     "id": "gpt-4"                           │                                  │
│ │                   }                                         │                                  │
│ └─────────────────────────────────────────────────────────────┘                                  │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\openai_object.py │
│ :172 in request                                                                                  │
│                                                                                                  │
│   169 │   ):                                                                                     │
│   170 │   │   if params is None:                                                                 │
│   171 │   │   │   params = self._retrieve_params                                                 │
│ > 172 │   │   requestor = api_requestor.APIRequestor(                                            │
│   173 │   │   │   key=self.api_key,                                                              │
│   174 │   │   │   api_base=self.api_base_override or self.api_base(),                            │
│   175 │   │   │   api_type=self.api_type,                                                        │
│                                                                                                  │
│ ┌────────────────────────── locals ───────────────────────────┐                                  │
│ │         headers = None                                      │                                  │
│ │          method = 'get'                                     │                                  │
│ │          params = {}                                        │                                  │
│ │  plain_old_data = False                                     │                                  │
│ │      request_id = None                                      │                                  │
│ │ request_timeout = None                                      │                                  │
│ │            self = <Model id=gpt-4 at 0x24e2cff7d80> JSON: { │                                  │
│ │                     "id": "gpt-4"                           │                                  │
│ │                   }                                         │                                  │
│ │          stream = False                                     │                                  │
│ │             url = '/models/gpt-4'                           │                                  │
│ └─────────────────────────────────────────────────────────────┘                                  │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py │
│ :138 in __init__                                                                                 │
│                                                                                                  │
│   135 │   │   organization=None,                                                                 │
│   136 │   ):                                                                                     │
│   137 │   │   self.api_base = api_base or openai.api_base                                        │
│ > 138 │   │   self.api_key = key or util.default_api_key()                                       │
│   139 │   │   self.api_type = (                                                                  │
│   140 │   │   │   ApiType.from_str(api_type)                                                     │
│   141 │   │   │   if api_type                                                                    │
│                                                                                                  │
│ ┌──────────────────────────────────── locals ─────────────────────────────────────┐              │
│ │     api_base = None                                                             │              │
│ │     api_type = None                                                             │              │
│ │  api_version = None                                                             │              │
│ │          key = None                                                             │              │
│ │ organization = None                                                             │              │
│ │         self = <openai.api_requestor.APIRequestor object at 0x0000024E2D000940> │              │
│ └─────────────────────────────────────────────────────────────────────────────────┘              │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\util.py:186 in   │
│ default_api_key                                                                                  │
│                                                                                                  │
│   183 │   elif openai.api_key is not None:                                                       │
│   184 │   │   return openai.api_key                                                              │
│   185 │   else:                                                                                  │
│ > 186 │   │   raise openai.error.AuthenticationError(                                            │
│   187 │   │   │   "No API key provided. You can set your API key in code using 'openai.api_key   │
│   188 │   │   )                                                                                  │
│   189                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you
can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the
openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See
https://platform.openai.com/account/api-keys for details.''''''

**Comment by EmporioConsulting** [comment]
$env:OPENAI_API_KEY="your_api_key_here"
**** inside your directory (if on windows) which it seems you may be

cheers 🍻

**Comment by noxiouscardiumdimidium** [comment]
"set" not "SET": 
`export OPENAI_API_KEY=[your api key]` for linux; 
 `set OPENAI_API_KEY=[your api key]` for windows.

 if youre doing something like using oobabooga textgen, or other local-LLM ui that requires a spoofed url/base/key to redirect api calls to a local port, you need to use @EmporioConsulting  answer, direct from command line sets it as a global system-wide variable, $OPENAI_API_KEY, that only holds a single value...whichever was set last.

**Comment by teknightstick** [comment]
I am also having this issue.  I am using set not SET.   i get no errors when running "set OPENAI_API_KEY=*****"   i am on windows using vscode.

**Comment by AleMaty78** [comment]
temperatura 0.1 non va bene, minimo 0.5

**Comment by Mercury888** [comment]
I am having this issue but I am on a Mac is the command for mac set or export?

**Comment by Alexinfotech** [comment]
Il mac in questione, ha il processore in silicon?

**Comment by Alexinfotech** [comment]
Ok, ci sono. Il problema sul mac e la cartella contente l'API KEY che non ha i permessi adeguati. 
I permessi alla cartella contenete  API va data da riga di comando tramite terminale. In poche parole è l'editor che non ha i permessi di lettura della cartella. Stai utilizzando PyCharm?

**Comment by patillacode** [comment]
Please @Alexinfotech  try write in English, even if it is through a translator.
