### ISSUE TITLE
issue running "gpt-engineer projects/my-new-project"

### ISSUE THREAD

**Issue by kido321** [AntonOsika/gpt-engineer#256]
when I run python3 -m gpt-engineer projects/my-new-project this issue comes up
<img width="726" alt="Screenshot 2023-06-20 at 1 02 48 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/59161624/01e8397a-7459-4928-9bfe-07898b41d23c">

**Comment by triggah61** [comment]
I get a simliar issue as well on a mac

**Comment by Sinma1** [comment]
Try to use python 3.9 or above as it's using [type hinting feature](https://peps.python.org/pep-0585/) that was introduced in that version.

**Comment by juarezjl** [comment]
Use python 3.11 or 3.10

**Comment by dareljohnson** [comment]
I have Python 3.10 and it's not working. I get an error when try to run gpt-engineer projects/my-new-project 

'gpt_engineer' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kigner** [comment]
> pip install gpt-engineer

**Comment by patillacode** [comment]
Closing, if you feel the need to re-open please do following the new issue template.
