### ISSUE TITLE
do create only python projects?

### ISSUE THREAD

**Issue by DanieleMar** [AntonOsika/gpt-engineer#26]
Is it supported only python as new project language, or others instead?

**Comment by IrmaEdmund** [comment]
enh

**Comment by DanieleMar** [comment]
With my question, I mean if this gpt-engineer project can generate projects that are not only in Python but also in other languages. I didn't mean if this specific gpt-engineer project will be done in other languages.

**Comment by yevg555** [comment]
> With my question, I mean if this gpt-engineer project can generate projects that are not only in Python but also in other languages. I didn't mean if this specific gpt-engineer project will be done in other languages.

It's using the GPT API so you could do probably any language, the program itself is written in python but that's it

**Comment by DanieleMar** [comment]
Thanks for the clarification. Congrats for the project, it's very useful.

Daniele Mariotto

Il mer 14 giu 2023, 4:47 PM Yevgeny Radchenko ***@***.***> ha
scritto:
