### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by kido321** [AntonOsika/gpt-engineer#261]
I am receiving incorrect api key when i am certain its the right one. 
<img width="682" alt="Screenshot 2023-06-20 at 4 29 13 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/59161624/321ae123-376f-469e-94fc-02eeb67b62f0">

**Comment by raygpt** [comment]
Does your key have GPT-4 access?

**Comment by patillacode** [comment]
It is OpenAI who is telling you that, not GPT Engineer.

I would recommend rotating the key.
