### ISSUE TITLE
Do. you want to execute this code? Yes. Ok, not executing the code

### ISSUE THREAD

**Issue by clickbrain** [AntonOsika/gpt-engineer#262]
Do you want to execute this code?

If you type yes instead of just hitting enter, the code does not execute. Might be nice to change this for folks that are used to giving an actual answer to these kinds of prompts.

**Comment by epireve** [comment]
Yes, that is true, whenever you click no. It seems to stop midway after TDD. The methods and functions have not yet been generated. I am still finding ways to work around this. At this point, I am not sure what to do to proceed.

**Comment by patillacode** [comment]
```
Do you want to execute this code?
If yes, press enter. Otherwise, type "no
```

If you press enter it will run, if you write ANYTHING and press enter it is not considered a "yes".

**Comment by clickbrain** [comment]
I understand how it functions, but it is not intuitive for how these prompts usually function. Why make it more difficult for the end user? Usually these CLI prompts have a Y/N or Yes/No or a ENTER or Y/N prompt. In this case, the prompt may cause someone that has waited for processing to type Yes and then exit out and have to figure out how to move forward from there or start over again. Just another thing for people to need help with and it isn't really necessary. As I said in my original issue, I think it would nice to change the behavior to standard behavior.

**Comment by patillacode** [comment]
Hi @clickbrain 

Fair enough.

FYI this has been addressed:

```python
print('If yes, press enter. Otherwise, type "no"')
    print()
    if input() not in ["", "y", "yes"]:
        print("Ok, not executing the code.")
        return []
    print("Executing the code...")
```

**Comment by clickbrain** [comment]
Thank you!
