### ISSUE TITLE
Scenarios where you would NOT be asked to clarify

### ISSUE THREAD

**Issue by mkammes** [AntonOsika/gpt-engineer#263]
Hello!

I've run many dozens of builds for 2 different projects, and not 1 time have I been prompted to clarify anything outlined in main_prompt.

My prompting can't be that good, can it? ;-)

**Comment by fredperes** [comment]
Same here.

**Comment by epireve** [comment]
I believe it should present us with the specs first before proceeding would be a better approach.

**Comment by AntonOsika** [comment]
We updated the default, see announcements!

Use it like: `gpt-engineer [project directory] --steps-config clarify`

Would you be able to add this to Q&A in discussions @mkammes ? 🙏

**Comment by mkammes** [comment]
Added. Thanks!

**Comment by mkammes** [comment]
> 

1 follow-up question - it appears "q" will skip the current question *and* subsequent questions. Is there an argument to only skip the current question?

**Comment by mkammes** [comment]
> We updated the default, see announcements!
> 
> Use it like: `gpt-engineer [project directory] --steps-config clarify`
> 

1 follow-up question - it appears "q" will skip the current question and subsequent questions. Is there an argument to only skip the current question?

**Comment by epireve** [comment]
It's updated now in the latest version. 

`--steps clarify` instead of `--steps-config clarify`
