### ISSUE TITLE
Unable to execute any commands

### ISSUE THREAD

**Issue by zenchantlive** [AntonOsika/gpt-engineer#275]
Hey team, I am unable to get GPTE to do any code execution when it stops to ask me fro input. This repeatedly happens:
" and finally, we will need to create a `.env` file to store our environment variables:

`.env`
```
MONGODB_URI=mongodb://localhost:27017
```
To install dependencies:
```
npm install
```

To run the codebase:
```
node server.js
```

Do you want to execute this code?

npm install

node server.js

If yes, press enter. Otherwise, type "no"

Executing the code...

Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:370: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:374: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:577: execvpe /bin/bash failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
(venv) PS C:\Users\Zenchant\Documents\gpt-engineer> "

**Comment by AntonOsika** [comment]
What does this have to do with .env files?

I don't understand the error but things fail quite often on windows

Please open a new issue with more clear debugging notes of what you tried so far!
