### ISSUE TITLE
How can I add new features to my code base？

### ISSUE THREAD

**Issue by suibber** [AntonOsika/gpt-engineer#284]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

# Issue Template

## Expected Behavior

How can I add new features to my code base？

**Comment by Milalych** [comment]
Send me massage fir help

**Comment by Milalych** [comment]
> **YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**
> 
> # Issue Template
> ## Expected Behavior
> How can I add new features to my code base？

I can help yoi
