### ISSUE TITLE
Entrypoint (run.sh) uses sudo even though told expressly not to

### ISSUE THREAD

**Issue by contentfree** [AntonOsika/gpt-engineer#295]
## Expected Behavior

The generated entrypoint runs without errors and with awareness of the type of system it's running within (macOS, in my case).

## Current Behavior

The generated entrypoint fails to run for various reasons (tries to download deb.nodesource.com/setup_14.x and run it, tries to use apt-get on macOS, tries to `cd` to the literal path `/path/to/codebase`). 

The first one to tackle is a line in run.sh that uses `sudo`:  `sudo apt-get install -y nodejs`

## Failure Information (for bugs)

I'm using the pip-installed version and I've copied the `identity` folder from the git repo (because the pip-installed version doesn't work out of the box on macOS – that's being tracked in another issue). After running, the file `memory/gen_entrypoint` contains the explicit text "Do not use sudo" which is ignored.

### Steps to Reproduce

I'm not quite sure how to reproduce it as I've run gpt-engineer with the same main prompt multiple times and have received vastly different results each time. My prompt states that a Rails app should be built and once a node.js app was built instead. Sometimes you just can't convince GPT to do what it's asked. :) 

### Failure Logs

The run.sh that was generated (on macOS):
```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
gem install rails -v 6.1.3.2

cd /path/to/codebase
bundle install

rails server
```

**Comment by liusida** [comment]
Sometimes, LLMs don't follow every order... 
I was using `gpt-3.5-turbo` and it did make some mistakes along the way. I guess using 'gpt-4' will be better, but the output of LLMs is not guaranteed.

**Comment by AntonOsika** [comment]
editing philosophy prompt might help here
