### ISSUE TITLE
New release not visible on sidebar

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#302]
# Issue Template

## Expected Behavior

Version 0.0.4 visible on https://github.com/AntonOsika/gpt-engineer right sidebar

## Current Behavior

Version 0.0.3 visible on https://github.com/AntonOsika/gpt-engineer right sidebar

## More info:

If one goes to [release](https://github.com/AntonOsika/gpt-engineer/releases), there is a 0.0.4 release.

@carlthome any thoughts 😬

**Comment by carlthome** [comment]
Did you mark 0.0.4 as the latest release?

![Screenshot_20230621_202457_GitHub.png](https://github.com/AntonOsika/gpt-engineer/assets/1595907/a64dea1c-865a-4963-8207-d3fc44b18f4b)

**Comment by abcdefghijorngarbosaxyz** [comment]
@AntonOsika you forgot to mark 0.0.6 as latest release again.
