### ISSUE TITLE
Typer library incompatibility

### ISSUE THREAD

**Issue by ligarius** [AntonOsika/gpt-engineer#309]
Run requirements.txt
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openapi-python-client 0.13.4 requires typer<0.8.0,>=0.6, but you have typer 0.9.0 which is incompatible.
spacy 3.5.2 requires typer<0.8.0,>=0.3.0, but you have typer 0.9.0 which is incompatible.

Downgrade typer to 0.7.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gpt-engineer 0.0.4 requires typer==0.9.0, but you have typer 0.7.0 which is incompatible.

Upgrade typer to 0.8.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gpt-engineer 0.0.4 requires typer==0.9.0, but you have typer 0.8.0 which is incompatible.
openapi-python-client 0.13.4 requires typer<0.8.0,>=0.6, but you have typer 0.8.0 which is incompatible.
spacy 3.5.2 requires typer<0.8.0,>=0.3.0, but you have typer 0.8.0 which is incompatible.

**Comment by mosk53** [comment]
You have a issue with Package versions.

Try:

1.  Create a Virtual environment:

- Windows
`python -m venv myenv`

- Mac
`python3.11 -m venv myenv`

3. Activate the virtual environment:

- Windows
`myenv\Scripts\activate`

- Mac
`source myenv/bin/activate`

4. Install Packages 
`pip install -r requirements.txt`

5. Run

**Comment by ligarius** [comment]
works!
