### ISSUE TITLE
Files are generated inside all_output.txt only

### ISSUE THREAD

**Issue by d4rkc0de** [AntonOsika/gpt-engineer#31]
I'm using `gpt-3.5-turbo` because `gpt-4` doesn't work

I asked for an angular project with a table that is generated from an API, however it generated all output in afile called all_output.txt, and file called HTML and a file called typescript,

What is expected to generate all files separately (app.component.ts, api.service.ts, table.component.ts app.component.html ...) with their corresponding content instead of generating it in the all_output.txt

[all_output.txt](https://github.com/AntonOsika/gpt-engineer/files/11746554/all_output.txt)

**Comment by iplayfast** [comment]
I had the same experience. Needed to use gtp-3.5-turbo, and ran the example. Used snake description genterated by chat.openai.com, and it talked about file1 `board.py` with code, and  so on, but the only files in the workspace was one called python (no extension) that appears to contain the code for the controller class.

**Comment by WizKid1968** [comment]
Same issue. The application ends after "Now let's proceed with the file contents.".

**Comment by patillacode** [comment]
Behaviour is different between `gpt-3.5-turbo` and `gpt-3.5-turbo-16k`

The former doesn't work very well (no files are created, except the `all_output.txt` and the latter indeed just keeps ending like you mention on #32  @WizKid1968

**Comment by WizKid1968** [comment]
> Behaviour is different between `gpt-3.5-turbo` and `gpt-3.5-turbo-16k`
> 
> The former doesn't work very well (no files are created, except the `all_output.txt` and the latter indeed just keeps ending like you mention on #32 @WizKid1968

You're absolutely right, I'm using gpt-3.5-turbo-16k.

**Comment by jebarpg** [comment]
Heres my solution:

import re
import os

save_dir = "results/"
f = open("example/workspace/all_output.txt", "r")
s = f.read()
pattern = re.compile(r'^\*\*(.*?\.py)\*\*\s+```python\s+.*?(^(?:.*\n)*?)^```\s', re.MULTILINE)
os.makedirs(save_dir, exist_ok=True)
for (file_name, file_text) in re.findall(pattern, s):
    write_file = open(save_dir + file_name, "w")
    write_file.write(file_text)
    write_file.close()
but sometimes you have to change the regex because the output isn't always the same.
so if you see **game.py** use the code above
if you see game.py: then use this:
pattern = re.compile(r'^(.*?\.py):\s+```python\s+.*?(^(?:.*\n)*?)^```\s', re.MULTILINE)

**Comment by jebarpg** [comment]
Heres my solution:
```python
import re
import os

save_dir = "results/"
f = open("example/workspace/all_output.txt", "r")
s = f.read()
pattern = re.compile(r'^\*\*(.*?\.py)\*\*\s+```python\s+.*?(^(?:.*\n)*?)^```\s', re.MULTILINE)
os.makedirs(save_dir, exist_ok=True)
for (file_name, file_text) in re.findall(pattern, s):
    write_file = open(save_dir + file_name, "w")
    write_file.write(file_text)
    write_file.close()
```
but sometimes you have to change the regex because the output isn't always the same.
so if you see \*\*game.py\*\* use the code above
if you see game.py\: then use this:
`pattern = re.compile(r'^(.*?\.py):\s+```python\s+.*?(^(?:.*\n)*?)^```\s', re.MULTILINE)`

**Comment by DrMemoryFish** [comment]
> 

where do we put this?

**Comment by offiub** [comment]
It is because of the errors and the issue . It Needs to be fixed . Text me
so I guide you and drop your Gmail address

**Comment by offiub** [comment]
Your mail sir

**Comment by jebarpg** [comment]
> > 
> 
> where do we put this?

I created a file called 'create_files.py' in the main repo directory. then ran python create_files.py

**Comment by offiub** [comment]
We couldn’t get your mail prop. Send your telegram number and indicate the
county + code so we can handle it immediately

**Comment by iplayfast** [comment]
Can that solution be made more generic, so c++, py etc all work. I think the line above the marker actually gives the proper filename (using 3.5-turbo)

**Comment by jebarpg** [comment]
@iplayfast Here yea go https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594148378

**Comment by jebarpg** [comment]
@DrMemoryFish check this comment out https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594148378

**Comment by jebarpg** [comment]
I did on my copy, but they are already working on having the project default to gpt-3.5-turbo if gpt-4 is not available. This did create the files for me too.

**Comment by jebarpg** [comment]
@RemkoDelsman https://github.com/AntonOsika/gpt-engineer/pull/40#issuecomment-1594579187

**Comment by jebarpg** [comment]
O geez sorry to spam you @RemkoDelsman I didn't realize you are the one in that comment lol... Just woke up so catching up with all the new issues and comments etc.

**Comment by JohnGomes** [comment]
Adjusting the identities was a small (2 line) change that seems to work for me - [see here](https://github.com/Significant-Gravitas/Auto-GPT/discussions/423#discussioncomment-6190646 )

**Comment by d4rkc0de** [comment]
I closed the issue because the problem don't exist in the latest version.
