### ISSUE TITLE
The execution code listed in the final stage does not seem to be suitable for Windows system operation

### ISSUE THREAD

**Issue by yang-lamb** [AntonOsika/gpt-engineer#314]

**Comment by Unessc0** [comment]
change export with set
and make sure to delete spaces before and after '='

**Comment by yang-lamb** [comment]
I'm a complete newbie to the point of not knowing how to do it, it always fails to execute code automatically, here is the original text of one task:
Do you want to execute this code?

sudo apt-get update
sudo apt-get install python3 python3-pip

pip3 install pygame

sudo apt-get install nginx

sudo nano /etc/nginx/sites-available/snakegame

server {
    listen 80;
    server_name your_domain;

    location / {
        root /path/to/codebase;
        index index.html;
    }
}

sudo ln -s /etc/nginx/sites-available/snakegame /etc/nginx/sites-enabled/
sudo systemctl restart nginx

cd /path/to/codebase
python3 game.py


If yes, press enter. Otherwise, type "no"


and when I press enter,this is the result:
Executing the code...

Note: If it does not work as expected, consider running the code in another way than above.

You can press ctrl+c *once* to stop the execution.

'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。



Then this mission is over

**Comment by AntonOsika** [comment]
Known issue
