### ISSUE TITLE
The default argument of project_path should change to 'projects/example'

### ISSUE THREAD

**Issue by liusida** [AntonOsika/gpt-engineer#315]
Since we have moved the project folders into `/projects`, we should also change the default argument for main.py

https://github.com/AntonOsika/gpt-engineer/blob/52ee3ed88e6c1753f0d38398d396f023ffe97346/gpt_engineer/main.py#L20

it should be ` project_path: str = typer.Argument("projects/example", help="path"), `, so that for people who don't use `make run`, the program still work properly.

**Comment by SumitKumarDev10** [comment]
Can this path be **customized** based on the **requirement**?
