### ISSUE TITLE
Add support for Azure OpenAI

### ISSUE THREAD

**Issue by herbutant** [AntonOsika/gpt-engineer#325]
I'd appreciate a configuration option to use our corporate instance of OpenAI in Azure instead of the standard openAI one.

**Comment by hannesdelbeke** [comment]
similar to 
- https://github.com/AntonOsika/gpt-engineer/issues/337

**Comment by Cytranics** [comment]
It uses the openai library dude, open up ai.py and add the openai.base, openai.versuon and change model to engine. 

Or write 6 python functions with different prompts because that's all this code is, calling an API 6 times

**Comment by herbutant** [comment]
@Cytranics that sounds straight forward. What's keeping you from making a pull request that does all that based on ENV variables?

**Comment by SebLz** [comment]
This can probably help https://github.com/AntonOsika/gpt-engineer/issues/530#issuecomment-1639759684

**Comment by AntonOsika** [comment]
Solved 🚀
