### ISSUE TITLE
I think this will enhance the experience of going through issues, thanks @aroramrinaal

### ISSUE THREAD

**Issue by Geeratipon** [AntonOsika/gpt-engineer#326]
I think this will enhance the experience of going through issues, thanks @aroramrinaal 

Since this is a change that affects how the project is presented to the users/contributors I'll wait for someone else to merge, but I have approved it.

Maybe @AntonOsika wants to re-word something or get rid a check or two.

cc @carlthome @FOLLGAD

_Originally posted by @patillacode in https://github.com/AntonOsika/gpt-engineer/issues/222#issuecomment-1597837755_

**Comment by carlthome** [comment]
Don't understand this issue. Seems like a copy/paste of a comment from a PR. Reopen if incorrect!
