### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SaiPanneerselvam** [AntonOsika/gpt-engineer#327]
Hi, I am a basic user who knows a few coding languages (e.g. Python, _UQWQU_), I would like to know how to run this AI Program and make a simple Python shell-based OS. I need help on loading the tool on the shell. Mainly, which bash/shell should I use?

**Comment by SaiPanneerselvam** [comment]
Its a question on which terminal i should use (windows)

**Comment by zerofill** [comment]
You can use bash if you want. Or you can use windows command prompt. It doesn't really matter.

**Comment by SaiPanneerselvam** [comment]
the `export [YOUR API KEY]` command doesn't work.

**Comment by SaiPanneerselvam** [comment]
> > the `export [YOUR API KEY]` command doesn't work.
> 
> @SaiPanneerselvam In windows, the `export` command is actually `set`. So it would be `set [YOUR API KEY]`

Thank you @mgrist that really helps.
