### ISSUE TITLE
[Suggestion] Add compatibility with gpt3.5-turbo

### ISSUE THREAD

**Issue by Explosion-Scratch** [AntonOsika/gpt-engineer#328]
This would likely be as simple as adding a setting/switch to select the model:

https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/scripts/rerun_edited_message_logs.py#L16
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/main.py#L21
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/ai.py#L11

It looks like this would just be adding an argument here:
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/main.py#L18-L34

**Comment by Explosion-Scratch** [comment]
See #329

**Comment by Ceilo** [comment]
> 

10/10

from there all you would do is update endpoints for API and update a few parameters to meet 3.5 turbo compatibility. Nice job btw :D
