### ISSUE TITLE
Working with existing codebase

### ISSUE THREAD

**Issue by WEBPerformace** [AntonOsika/gpt-engineer#33]
I hope to see the ability to work with an existing codebase in the near future as this will be the most common use case in the real world.

**Comment by obordea** [comment]
I agree and really looking forward to this feature. I do not think there is any AI code assistant out there that can do this efficiently yet.

**Comment by haberco** [comment]
This same functionality would also allow for alternations, changes, edits to the generated code base after the first pass.

**Comment by pascalandy** [comment]
I see the main_prompt as the core specs. You gotta make the project work like a badass MVP.

Then you write PR_prompt_001, PR_prompt_002, and all that jazz. Let the machine handle the code updates. Push that shiznit to git and create a sick PR.

That would be an epic flow :-p

**Comment by offiub** [comment]
I would like to fix your errors On Thu, Jun 15, 2023 at 1:41 AM Pascal Andy

**Comment by offiub** [comment]
Okay you have to make a deposit first sir so we can rectify it

**Comment by offiub** [comment]
Yes it has errors and it needs to be fixed . Do you want our help and
support On Thu, Jun 15, 2023 at 2:06 AM roy hub offi <

**Comment by wwzeng1** [comment]
We're building something for this: https://github.com/sweepai/sweep

**Comment by noxiouscardiumdimidium** [comment]
they should implement the ability to run the model local through the official gpt4all_UI.v2.4.8, you we can run replit-code-v1-3 locally, and utilize the built in localdocs of both end points, give users instructions to open gpt4all-ui , enable server-mode, download and mount replit-code through the ui. create and enable  "collections" folder filled with tech and coding manuals related to your current build, paste collections folder path into gptengineer so it knows it location, and every time it finishes a run, dump the all_output file into the gpt4all localdocs xP

**Comment by mach7** [comment]
> We're building something for this: https://github.com/sweepai/sweep

How has the experience been with it so far?

**Comment by mOrGaNCrYpTo** [comment]
> > We're building something for this: https://github.com/sweepai/sweep
> 
> How has the experience been with it so far?

Simply, amazing.

**Comment by AntonOsika** [comment]
There is a PR open for this 🏃

**Comment by AntonOsika** [comment]
Added in #465 🚀
