### ISSUE TITLE
EXITING TOO EARLY

### ISSUE THREAD

**Issue by JWB1111** [AntonOsika/gpt-engineer#330]
## Expected Behavior

Printing out the code + readme in c++

## Current Behavior

Gets about 80% done then stops printing out the code and saying the steps to execute the .py code for Linux. 

Looks like this:

File 10: mapio.h
```cpp
#ifndef MAPIO_H
#define MAPIO_H

#include "abstractmap.h"

class
To install dependencies:
```
sudo apt-get update
sudo apt-get install qt5-default
```

To run the codebase:
```
qmake -project
qmake
make
./<executable_name>
```

Do you want to execute this code?

sudo apt-get update
sudo apt-get install qt5-default

qmake -project
qmake
make
./<executable_name>

**Comment by manoocher** [comment]
I have a similar problem, but I'm using gpt-3.5-turbo model. It exits to running the code before even completely finishing the code on the first file.

**Comment by scottsuhy** [comment]
same problem on gpt-3.5-turbo (windows 11)

**Comment by irnb** [comment]
i have this issue on  gpt-3.5-turbo too

**Comment by wlc108** [comment]
This is impacting me as well. I tried earlier commits and the latest commits so it has not recently changed. I'm also on gpt-3.5-turbo as well since I don't have GPT4 yet.

**Comment by hvolpers** [comment]
In ChatGPT answering with "continue" fixes this issue, I assume this is the same issue. Perhaps asking the API to continue would be a fix (should let you know if there is nothing more to say :)), but I'm not sure if that is possible using the API.

**Comment by dougdaulton** [comment]
same problem on gpt-3.5-turbo on macOS 13.4.1 (Ventura).  

50% of the time, it lists CLI commands for installing packages it needs (even when they are already installed) then it asks if I want to execute this code.  If I do it exits gpt-engineer and runs the code.  If I say Yes it writes a few more lines and then ends and asks me to answer questions for the devs, then exits.

**Comment by AntonOsika** [comment]
I dont understand fully, will close
