### ISSUE TITLE
[SUGGESTION] Make a gui for this tool.

### ISSUE THREAD

**Issue by SaiPanneerselvam** [AntonOsika/gpt-engineer#332]
Maybe once in the future an exe app can be downloaded and used instead of running it from shell/NGUI.
I can help building the GUI app as I have a knowledge of VB.NET Visual Studio Programming and can make an open tool for this purpose. Just you can tell me which script goes where, etc. and I can try making a basic GUI. I use a Windows XP computer running Visual Studio 2022.
Here is an image of an example of the app:
![image](https://github.com/AntonOsika/gpt-engineer/assets/89541946/8cb7a303-05a0-4414-bec1-fa87d544cdbc)

**Comment by hannesdelbeke** [comment]
A GUI is a great idea. It does feel like it should live in a separate repo IMO.

**Comment by SumitKumarDev10** [comment]
Hey, I think a **Web Interface** is better.

**Comment by SaiPanneerselvam** [comment]
@SumitKumarDev10 Yeah, now I feel like there should be both. One for online  and the other app can be if you want to use it in a little more advanced. I too love the iden though.

**Comment by SaiPanneerselvam** [comment]
You should start a PR
-ஓம்

**Comment by SumitKumarDev10** [comment]
@SaiPanneerselvam Ok, I will fork the project and start working on the web interface which will be accessible from the Internet.

**Comment by SumitKumarDev10** [comment]
Someone else who is more experienced in making GUI apps can use the Tkinter library to make the app.

**Comment by SaiPanneerselvam** [comment]
hmm... you are probably right

**Comment by SaiPanneerselvam** [comment]
but windows forms and VB.NET is a little more tailored.
Sent on my galapi

**Comment by SaiPanneerselvam** [comment]
like tkinter is a design programme that you have to write line-by-line, whereas VB.NET Windows Forms can be customized easily, which makes it a little more simpler in both the frontend and backend.

**Comment by SumitKumarDev10** [comment]
Hmm... Looks like we need a VB.net coder to help us out.

**Comment by SumitKumarDev10** [comment]
I am not experienced in Tkinter but am good in web development

**Comment by SaiPanneerselvam** [comment]
OK i have found the project under your username and I have a good tool to make the website with. It is very nice in the development part. It is [Glitch](https://glitch.com), an Open Website Creator that is free and gives you the opportunity to make the website under a subdomain, instead of the subdomain being the username, and the repo is the folder. (GitHub vs glitch)

**Comment by SaiPanneerselvam** [comment]
I can create an shared project on it.

**Comment by SumitKumarDev10** [comment]
We have:-
- Glitch In Bio
- Website
- Node.js
- React
- Eleventy
- SQLite
Out of which I am comfortable with **NodeJS** and **React**. I think we should not use the **Website** option as it is static.
In my humble opinion, **NodeJS** will be great. You can take care of the **frontend** and use tools like **Bootstrap** while I design the **backend**.

**Comment by SumitKumarDev10** [comment]
I think [**Vercel**](https://vercel.com) is good for deploying the web application. To collaborate, we can use **Github Codespaces**.

**Comment by SumitKumarDev10** [comment]
I have added @SaiPanneerselvam to my collaborator's list of repository. If anyone else wants to get added, then please contact me.

**Comment by SumitKumarDev10** [comment]
Please refer to issue no. #456 for collaborating to the web interface of the repository.

**Comment by mach7** [comment]
Why not build it with an electron app? That way it would be easily cross platform compatible. It would also prevent the need for a gui/app to be coded in multiple languages.

**Comment by SumitKumarDev10** [comment]
@mach7 I don't know **electronjs** so I think an a developer who knows it can contribute.

**Comment by ATheorell** [comment]
Closing this, since the discussion is continued in #456
