### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by RedBeard678** [AntonOsika/gpt-engineer#333]
When I execute gpt-engineer projects/my-new-project, I expect it to start the process but I receive the following error:

  File "C:\..\GPT Engineer\gpt-engineer\gpt_engineer\steps.py", line 19, in <module>
    Step = TypeVar("Step", bound=Callable[[AI, DBs], list[dict]])
TypeError: 'type' object is not subscriptable

The process then ends.

I have not made any changes to the steps.py file, does anyone know what might cause this behavior?

**Comment by pinnnnnnz** [comment]
having the same issue here

**Comment by Knudn** [comment]
I managed to get it working after upgrading to Python 3.9

**Comment by pinnnnnnz** [comment]
> I managed to get it working after upgrading to Python 3.9

I am using 3.11 which I would assume should be backward compatible?

**Comment by RedBeard678** [comment]
That seems to have resolved it...thanks!

**Comment by kaspesi** [comment]
Still seeing this, claims to be compatible with >=3.8 though
