### ISSUE TITLE
General usage question: How to iterate?

### ISSUE THREAD

**Issue by ScottBeeson** [AntonOsika/gpt-engineer#338]
I filled out my main_prompt file and ran the program. It generated a lot of code that looks great, but when I run the generated program, I get a fairly straightforward error (code is expecting an integer, not a string). This might be simple enough to fix manually, but I'm curious how people iterate with GPT Engineer. Do I just add a new line to the main_prompt that says "don't pass a string to the sort_data method" and then run the whole thing again? Or is there a better way?

**Comment by shubham-attri** [comment]
This issue has been discussed in the [ROADMAP](https://github.com/AntonOsika/gpt-engineer/blob/main/ROADMAP.md) to ask for continuous evaluation : 
"Ask human for what is not working as expected in a loop, and feed it into GPT4 to fix the code, until the human is happy or gives up" 
@AntonOsika is working to bring the features in the roadmap to the project to the earliest.

**Comment by Ryan526** [comment]
You should be able to create a file named `feedback` in your project folder instead of adding it to the main_prompt and rerun with the `use_feedback` argument.

`gpt-engineer projects/yourproject --steps use_feedback`

**Comment by Joshfindit** [comment]
How about two approaches in tandem:

1. Ask a variation of “are you sure” before saving the code. This has been shown to significantly increase code quality for very little “effort”
2. Capture stderr/stdout and then run a continuous feedback loop until the app starts successfully. Functional errors could be captured as well. “I noticed there was an error in `filename.py`. Do you want me to try to fix it?”

**Comment by nafg** [comment]
It seems like iterating on a codebase is a much harder problem than creating a new one. Ideally there would be a tool that one could point at an existing codebase and give it a task (e.g. "make tests pass," "add user sign-up functionality," "DRY the user forms," etc.)

**Comment by AntonOsika** [comment]
@Joshfindit would you be interested in collaborating on this:

> Capture stderr/stdout and then run a continuous feedback loop

It's very promising

**Comment by ATheorell** [comment]
This issue is blocked by issue #650. When #650 is solved, this will be relatively easy to fix. Closing for now
