### ISSUE TITLE
No.

### ISSUE THREAD

**Issue by ScottBeeson** [AntonOsika/gpt-engineer#339]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

# Issue Template

## Expected Behavior

I expect it to say "Okay" or "Thanks" or nothing

## Current Behavior

It just says "No." then proceeds.

## Failure Information (for bugs)

Every time I run gpt-engineer on my prompt and it asks for clarification, after I type the clarification it says "No.". Here are a couple examples.

![image](https://github.com/AntonOsika/gpt-engineer/assets/108358/2eda214b-013c-4719-9a0a-b09c6e6fd423)
![image](https://github.com/AntonOsika/gpt-engineer/assets/108358/2a907196-ef2d-4f6f-b445-6c725f033df0)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enter prompt.
2. Run gpt-engineer
3. Enter response to clarification questions.
4. No.

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by AntonOsika** [comment]
Fixed this 🏃
