### ISSUE TITLE
Mounting error?

### ISSUE THREAD

**Issue by ScottColeSW** [AntonOsika/gpt-engineer#350]
Following the exact instructions, I get the error:
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

I'm in Windows 11 running in an Anaconda Powershell env.

dmesg isn't a command in windows. I'm not sure how to fix this. Changing permissions didn't help.

**Comment by ScottColeSW** [comment]
needed odd permission changes... my system... sigh...

**Comment by jtuck41** [comment]
Im having this same issue. How did you fix it?

**Comment by hhotham** [comment]
> Im having this same issue. How did you fix it?

Same here, any info would be good.

**Comment by ScottColeSW** [comment]
I solved it with permissions.
