### ISSUE TITLE
KeyError: 'main_prompt' problem with GPT Engineer

### ISSUE THREAD

**Issue by SMSaikatMondal** [AntonOsika/gpt-engineer#360]
I am getting the following error:

My Input: python -m gpt_engineer.main example
My OS: Windows11
Python version: 3.11.4
pip version: 23.1.2 

 File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\Saikat\gpt-engineer\gpt_engineer\main.py", line 65, in <module>
    app()

  File "C:\Users\Saikat\gpt-engineer\gpt_engineer\main.py", line 60, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\Saikat\gpt-engineer\gpt_engineer\steps.py", line 37, in clarify
    user = dbs.input["main_prompt"]
           ~~~~~~~~~^^^^^^^^^^^^^^^

  File "C:\Users\Saikat\gpt-engineer\gpt_engineer\db.py", line 21, in __getitem__
    raise KeyError(key)

KeyError: 'main_prompt'

**Comment by abcdefghijorngarbosaxyz** [comment]
The `example` folder should exist and in it should there be a `main_prompt` file. Its gives you that error when you feed it a file that does not exist.

**Comment by HulkAi** [comment]
I had the same problem trying to build the project also. What I did was move the project out of the projects folder as a temporary solution. I still can't get the built projects to run. any suggestions is welcomed.

**Comment by voulkon** [comment]
For some weird reason it works if you name the file 'main_prompt' instead of 'prompt'.

**Comment by IIEleven11** [comment]
I'm having the same issue. It worked 45 minutes ago. Something happened and where one used to say main_prompt it now looks like this (after execution of "cp -r projects/example/ projects/my-new-project"} 
![image](https://github.com/AntonOsika/gpt-engineer/assets/55998857/1ec429a1-fd12-4216-b23e-b9784bff7d6c)
. Changing the filename appears to work but the result ends up with an error. I forgot to make note of the name/contents of the error I will run it again and edit this post with those details.

**Comment by Bandit253** [comment]
I think I may have solved this problem and it comes down to an "s" on the end of "project".  The example has the singular yet the path to main_prompt is this plural, "projects"!

**Comment by ScaryFastca** [comment]
I am very new to all this stuff, but tonight I decided to check for gpt-engineer updates, pulled the latest, and suddenly started having this problem too. 

Looks like Installing gpt-engineer now results in /example/prompt being created instead of the former /example/main_prompt, so it fails to start. As said, manually correcting the file to main_prompt allows it to run.

**Comment by IIEleven11** [comment]
> I am very new to all this stuff, but tonight I decided to check for gpt-engineer updates, pulled the latest, and suddenly started having this problem too.
> 
> Looks like Installing gpt-engineer now results in /example/prompt being created instead of the former /example/main_prompt, so it fails to start. As said, manually correcting the file to main_prompt allows it to run, but obviously the real fix is somewhere deep in the code and way above my ability.

Were you able to complete a full run without error by changing it to main_prompt? Mine would start but eventually fail

**Comment by chaitanyanarukulla** [comment]
@Bandit253  > I think I may have solved this problem and it comes down to an "s" on the end of "project". The example has the singular yet the path to main_prompt is this plural, "projects"!
Where do you change this ?

**Comment by JungeWerther** [comment]
For me I obtained that error when I didn't create the virtual environment properly. Try running `source venv/bin/activate` after `make install`?

**Comment by AntonOsika** [comment]
There was a bug on main. Should not happen!

It's fixed now, let's make sure it doesn't happen again.

**Comment by AntonOsika** [comment]
Closing now, please immediately open a new issue if this is not fix still!
