### ISSUE TITLE
teach with your own data

### ISSUE THREAD

**Issue by ivan-vilches** [AntonOsika/gpt-engineer#365]
What languages can be used ? can i feed with my own data ? for example with a documentation of a framework?
thanks you

**Comment by SumitKumarDev10** [comment]
That's a great question. Seems like someone needs to clarify on this especially the **Code Owners**.

**Comment by ATheorell** [comment]
This stale issue is has too wide scope. Please refer to https://gpt-engineer.readthedocs.io
