### ISSUE TITLE
Adding matrix for python version and OS and auto-release notes

### ISSUE THREAD

**Issue by k1lgor** [AntonOsika/gpt-engineer#366]
## Issue Template

1. Do you need a matrix for the workflows about the Python version, e.g. 3.8, 3.9, 3.10, 3.11, and OSs, ubuntu-latest, windows-latest, and macOS-latest?
2. Do you need auto-releases with generated notes as well and release versions accordingly?

## Expected Behavior

1. This will check all the above-mentioned Python versions in all OSs
If older versions are failing due to dependencies we could just ignore/remove them from the workflow.
2. The release notes will be auto-generated when some PR is merged to the `main`
![image](https://github.com/AntonOsika/gpt-engineer/assets/65338982/25e2d41f-38c5-48f5-afda-31dce7555177)

**Comment by ATheorell** [comment]
Closing due to overdue triage label
