### ISSUE TITLE
CODEOWNERS file

### ISSUE THREAD

**Issue by k1lgor** [AntonOsika/gpt-engineer#367]
## Issue Template

A suggestion of creating a `CODEOWNERS` file where some people are mandatory to approve the PRs.
There is a way to put a specific person to be a reviewer for `*.py` or folder for example: 

```codeowners
*.py       @person1 @person2
*.toml     @person1
*.md       @person2 
.github/*  @person3
```

## Expected Behavior

Those people will be mandatory for every PR created with the above-mentioned files.
The branch protection option needs to be adjusted accordingly.
This is an example:
![image](https://github.com/AntonOsika/gpt-engineer/assets/65338982/91802952-d9fc-4eeb-a578-77ea1ebd1f5a)

**Comment by ATheorell** [comment]
Closing due to overdue triage label
