### ISSUE TITLE
ModuleNotFoundError: No module named 'pip' when installing gpt-engineer

### ISSUE THREAD

**Issue by Lucash2022** [AntonOsika/gpt-engineer#379]
Issue Description:
Steps to Reproduce:

Run the command pip install gpt-engineer in the directory "C:\Users\Lu-Cash\OneDrive\Documents\GitHub\Test".
Observe the error message.
Expected Behavior:
I expected the gpt-engineer package to be installed successfully without any errors.

Actual Behavior:
I encountered the following error message:

![image](https://github.com/AntonOsika/gpt-engineer/assets/41428579/79b177ce-97ca-4d99-90ee-f90151b104ad)

Environment:

Operating System: Windows 11 Home Single Language
Python Version: 3.11.3
Other relevant software versions: N/A
Attempted Solutions:
I have tried the following solutions, but none of them resolved the issue:

Ensured that Python and pip are installed and properly configured.
Verified that the pip executable is available in the Python installation directory.
Upgraded pip to the latest version using python -m pip install --upgrade pip.
I appreciate any assistance in resolving this issue. Thank you for your attention.

**Comment by AntonOsika** [comment]
Google for how to install pip
