### ISSUE TITLE
Dependency conflicts when trying to use gpt-engineer on Google Colab

### ISSUE THREAD

**Issue by Gazelle221B** [AntonOsika/gpt-engineer#385]
## Expected Behavior

`gpt-engineer` should be installable and runnable on Google Colab without any dependency conflicts.

## Current Behavior

When trying to install and run `gpt-engineer` on Google Colab, there are dependency conflicts with the `click` and `typer` packages.

## Failure Information

This issue arises when trying to install `gpt-engineer` on Google Colab. The specific error messages are:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.2.5 requires click>=8.0, but you have click 7.1.2 which is incompatible.
black 23.3.0 requires click>=8.0.0, but you have click 7.1.2 which is incompatible.
gpt-engineer 0.0.6 requires typer==0.9.0, but you have typer 0.3.2 which is incompatible.
pip-tools 6.13.0 requires click>=8, but you have click 7.1.2 which is incompatible.

### Steps to Reproduce

1. Open a new Python notebook in Google Colab.
2. Run `!pip install gpt-engineer` in a code cell.
3. Observe the error messages related to dependency conflicts.

### Failure Logs

The error messages are included in the "Failure Information" section above.

**Comment by AntonOsika** [comment]
Not sure how to solve. We don't want to use 0.3 if 0.9 is available.

If you could google for how others solve this and add proposed solution that would be great!
