### ISSUE TITLE
Remove "run_id" and "delete_existing" options: instead move old memory/workspace folder to "archive" by default

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#388]
The first step in the main file would be to check for memory folder and workspace, if they exist create a new folder in "archive" e.g. with the name "currentdate_currenttime", and move everything there.

This would make main.py much nicer, and make it clearly defined that all files, apart from `archive` folder, in the project directory are from the most recent run.

(It is also a prerequisite to later add handling of logging to separate files when there are "multiple of the same steps")

**Comment by AntonOsika** [comment]
I realize the better workflow is probably this:

Copy the entire project's folder to the new archive folder. Delete memory folder. Let the to_files function delete the workspace.

**Comment by AmanSal1** [comment]
Can I work on this ?

**Comment by AntonOsika** [comment]
@AmanSal1 it's yours!

Let's go 🏃

**Comment by azrv** [comment]
That's what I imagine tree to look like.  @AntonOsika  Please confirm
We'd need to store a timestamp when generating code to then put it as a folder's name
Is logs a right place for it? 

```
- projects/snake
  - archive/
    - 20230625_134611/
      - memory/
      - workspace/
      - prompt
    - 20230625_124807/
      - memory/
      - workspace/
      - prompt
   - memory/
   - workspace/
   - prompt
```

**Comment by AmanSal1** [comment]
@azrv Are you working on this ?

**Comment by azrv** [comment]
@AmanSal1 I can leave this one for you :)

**Comment by AmanSal1** [comment]
@azrv no no if you are doing it you can go ahead no issue :)

**Comment by AntonOsika** [comment]
Looks good @azrv!

Just a bit better to use isoformat for datetime. Like so: 2023-06-25_14:34:47

**Comment by piyushnags** [comment]
I'm assuming this is no longer an open issue since changes have been merged, but just wanted to check if I'm missing something since this issue is still open?

**Comment by AntonOsika** [comment]
Yup solved! Good job.
