### ISSUE TITLE
"requirements.txt" file missing

### ISSUE THREAD

**Issue by Madhav-MKNC** [AntonOsika/gpt-engineer#389]
In the root directory, no 'requirements.txt' file was found. Was there any update where it was removed intentionally or is something wrong here?

**Comment by ae-circuit** [comment]
I am also a newbie here but I think they removed it and instead, we have to use `pip install -e .` command

**Comment by ShivamKumar2002** [comment]
that's because it is a module now, the requirements are defined in pyproject.toml file

**Comment by AntonOsika** [comment]
Yup!

Let me know if there are any issues where you need it 👌
