### ISSUE TITLE
When benchmark.py creates multiple projects that need `npx http-server` to run, all of them start up the "first" project that used npx http-server

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#395]
## Steps to reproduce
- run benchmark.py
- Allow it to run the generated projects (press enter when prompted)
- wait for the second project that is run with `npx http-server`

## Expected Behavior

The project runs

## Current Behavior

The first `npx http-server` project runs

**Comment by wwzeng1** [comment]
@AntonOsika I'm taking a look at this

**Comment by wwzeng1** [comment]
I'm a bit confused, this repository doesn't seem to use npx. I will try prompting Sweep to run the benchmarks on 
subprocesses with separate ports.

**Comment by wwzeng1** [comment]
https://github.com/AntonOsika/gpt-engineer/pull/413 tested this but I'm not sure if it's what you wanted. Let me know if you have more feedback!

**Comment by AntonOsika** [comment]
Edited the title to address your confusion

Sweep-ai bot hasn't been useful thus far unfortunately

**Comment by wwzeng1** [comment]
Sorry to hear that, it's a lot worse in repositories which use LLMs, mostly due to the self referential nature of prompts, etc.

**Comment by wwzeng1** [comment]
Hope you are able to get value in the future! We're working on improving it :)

**Comment by AntonOsika** [comment]
Ah hey it's you Will. Thanks for jumping in and checking it out!

**Comment by AntonOsika** [comment]
Great work @azrv  🚀
