### ISSUE TITLE
Json issue when running it about half way through

### ISSUE THREAD

**Issue by walter-grace** [AntonOsika/gpt-engineer#4]
gpt-engineer-main/steps.py:45 in run_clarified           │
│                                                                                        │
│   42                                                                                   │
│   43 def run_clarified(ai: AI, dbs: DBs):                                              │
│   44 │   # get the messages from previous step                                         │
│ ❱ 45 │   messages = json.loads(dbs.logs[clarify.__name__])                             │
│   46 │                                                                                 │
│   47 │   messages = (                                                                  │
│   48 │   │   [                                                                         │
│                                                                                        │
│ ╭─────────────────────── locals ───────────────────────╮                               │
│ │  ai = <ai.AI object at 0x7f84091e5e80>               │                               │
│ │ dbs = DBs(                                           │                               │
│ │       │   memory=<db.DB object at 0x7f84091f90d0>,   │                               │
│ │       │   logs=<db.DB object at 0x7f84091f9220>,     │                               │
│ │       │   identity=<db.DB object at 0x7f84091f91c0>, │                               │
│ │       │   input=<db.DB object at 0x7f84091f9190>,    │                               │
│ │       │   workspace=<db.DB object at 0x7f84091f9130> │                               │
│ │       )                                              │                               │
│ ╰──────────────────────────────────────────────────────╯                               │
╰────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'json' is not defined

**Comment by walter-grace** [comment]
<img width="425" alt="Screenshot 2023-06-10 at 8 35 05 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/31444892/6e4951a9-36fd-4b9e-9d9b-bc07a7dae583">

**Comment by AntonOsika** [comment]
Apologies for a broken commit not adding all the diffs there, fixed :)
