### ISSUE TITLE
Where is the requirements.txt file?

### ISSUE THREAD

**Issue by sandorseely** [AntonOsika/gpt-engineer#402]
Where is the requirements.txt file? I have been looking everywhere and i cant find it. if someone could copy paste it it would be greatly appreciated

**Comment by xgbn** [comment]
This project is using pyproject.toml instead of requirements.txt
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

You can `make install` to install the dependencies in your venv. See https://github.com/AntonOsika/gpt-engineer/tree/main#usage

**Comment by DaBugg** [comment]
So how do you install the dependencies before i tried 
```python -m pip install -r requirements.txt``` 
how does the syntax change with pyproject.toml

**Comment by AntonOsika** [comment]
Does readme.md not work @DaBugg ?

**Comment by AntonOsika** [comment]
Please reopen if necessary

**Comment by SchlackBoles** [comment]
You could have helped him with one line but decided to be an ass about it. SMH.

**Comment by sandorseely** [comment]
> You could have helped him with one line but decided to be an ass about it. SMH.

True smh

**Comment by jenspacito** [comment]
Ok i will lock i can do, but im my first time on github and driving with the bus to kualalumpur.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
