### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by danieldanielecki** [AntonOsika/gpt-engineer#411]
The link under https://github.com/AntonOsika/gpt-engineer#contributing redirects to https://discord.com/invite/4t5vXHhu which shows an invalid invite. It looks like, the correct link is https://discord.com/invite/8tcDQ89Ej2, based on https://github.com/AntonOsika/gpt-engineer#gpt-engineer.

**Comment by AntonOsika** [comment]
Bummer, we had two links. Should be fixed.
