### ISSUE TITLE
Feature : Running without OpenAI API Key

### ISSUE THREAD

**Issue by iamshreeram** [AntonOsika/gpt-engineer#414]
## Feature Request

There are multiple [apps](https://github.com/xtekky/gpt4free), [app 2](//github.com/ramonvc/freegpt-webui) that lets us interact with Chat GPT without setting up Openai API Key. These application uses proxy servers for interacting with the GPT. 

This will allow anyone to,  just clone the repository and run the gpt-engineer without any other setup. 

Can this feature be included to provide minimalist version of gpt-engineer?

**Comment by AntonOsika** [comment]
Yes looking into this, but it costs money with the api :/
