### ISSUE TITLE
Adding browsing ability to work with  more up-to-date libs/frameworks

### ISSUE THREAD

**Issue by barshag** [AntonOsika/gpt-engineer#417]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

## Issue Template
when asking for a code- since using GPT3.5/4- the newer versions of next(13 example) are not reconginzed

## Expected Behavior
To be familiar with the latest tools/libs to used

Please describe the behavior you are expecting.

## Current Behavior

using only tools since 2021...

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
- just ask for a project and the tools will be not up to date..

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by AntonOsika** [comment]
Isn't this a problem with all GPT models?

**Comment by barshag** [comment]
@AntonOsika it's not about the GPT, it's about using external tooling along with it... Why did you closed the issue? This is very crucial part for the ultimate GPT-engineer.
