### ISSUE TITLE
 Failed to establish a new connection

### ISSUE THREAD

**Issue by adhb22** [AntonOsika/gpt-engineer#419]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

## Issue Template
Failed to establish a new connection
## Expected Behavior
GPT is blocked , no direct access, what should be done?

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models/gpt-4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF38777C10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by AntonOsika** [comment]
Connection to openai, you should try again or get a new API key
