### ISSUE TITLE
Pre - commands, example with Laravel

### ISSUE THREAD

**Issue by AyodejiO** [AntonOsika/gpt-engineer#437]
Hi,

I want to generate a Laravel API application, but before the generation, I want the program to run the Laravel boilerplate command `laravel new .`, and then proceed to replace specific files in the boilerplate with the generated code. Am I demanding too much? 🤔

**Comment by noxiouscardiumdimidium** [comment]
the one function to "execute" laravel, try showing a precise version of it to chatgpt first, and ask it to replace the the functions with the closest approximate ASSEMBLY-LANGUAGE xD then a new-line, then !EXECUTE LARAVEL NEW . ! then instructions on how to modify it... its pretty good at complex task lists written in PASCAL or ASSEMBLY

**Comment by ATheorell** [comment]
Closing this answered issue, since it has been stale for a long time.
