### ISSUE TITLE
Prompt doesn't seem to pass through

### ISSUE THREAD

**Issue by ITTICK** [AntonOsika/gpt-engineer#439]
Please describe the behavior you are expecting. 

Doing a test with the snake game, and it appears the prompt I provide is not being passed through.
I expect to be asked clarifying questions regarding the prompt I provided.

What is the current behavior?

Regardless of the prompt, the response I receive after running python -m gpt_engineer.main <name> is:
Areas that need clarification:
1. What specific instructions am I not supposed to carry out?
2. What is the purpose of seeking clarification?
3. How many clarifying questions am I allowed to ask?
etc...

I'm not sure if this is a bug, or I have corrupted my environment somehow.
I have tried deleting the entire gpt_engineer dir on windows PC, re-cloned, same issue.
Re-installed VS Code, Git, and Python in case there was some temp file causing this.

**Comment by MoreGreenForests** [comment]
Maybe add a suggestion here to have a method to just check prompt exists which I think is there but if we get a false positive there should be a flag to just get the prompt returned to test that the right path was sent and the right prompt is used as this seems like the boilerplate being fed back.

**Comment by ITTICK** [comment]
I'm not sure what it was that got corrupted or misconfigured, but it is working now, after un-installing VScode, Git, Python, deleting all related temp files (including temp install and config files), rebooting, and re-installing all the mentioned programs. 
Thanks for the help and suggestions, will definitely be adding a prompt check to ensure it's being seen and passed through properly.
