### ISSUE TITLE
command-"python -m gpt_engineer.main example" throwing error

### ISSUE THREAD

**Issue by vipulpapriwal** [AntonOsika/gpt-engineer#453]
I am trying to install gpt-engineer on windows with the below steps and got stuck. 

**Replication steps:**

1) mkdir test
2) cd test
3) git clone https://github.com/AntonOsika/gpt-engineer.git
4) cd gpt-engineer
5) cd projects
6) set OPENAI_API_KEY=<key starting with sk-#############>
7) rename prompt to main_prompt
8) set model = "gpt-3.5-turbo" 
9) set temperature = 0.9
10) pip install -e .
7) python -m gpt_engineer.main example

**Error:**
{
INFO:openai:error_code=model_not_found error_message="The model 'gpt-4' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Model gpt-4 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\Nice\testPrincy\gpt-engineer\gpt_engineer\main.py", line 71, in <module>
    app()

  File "C:\Users\Nice\testPrincy\gpt-engineer\gpt_engineer\main.py", line 64, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\Nice\testPrincy\gpt-engineer\gpt_engineer\steps.py", line 53, in clarify
    user_input = get_prompt(dbs)
                 ^^^^^^^^^^^^^^^

  File "C:\Users\Nice\testPrincy\gpt-engineer\gpt_engineer\steps.py", line 25, in get_prompt
    "prompt" in dbs.input or "main_prompt" in dbs.input
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError: Please put your prompt in the file `prompt` in the project directory
}

**Comment by cyberfag** [comment]
I followed almost the same steps, although using Anaconda. Anyway, I had the same problem by it was solved by changing your 11th step to the command recommended in README, namely, to 
`gpt-engineer projects/my-new-project`

Besides, if that's important, I executed this command from the root gpt-engineer folder, not from 'projects' as your 5th step implies

**Comment by SumitKumarDev10** [comment]
Same with me.

**Comment by jim0237** [comment]
I have tried all the suggestions above and still get the same error

**Comment by lukesb** [comment]
Try 

`cd ..`

`gpt-engineer projects/example`

This happened to me when I was a directory too deep

**Comment by skvs2005** [comment]
I got it working like below

c:\git\gpt-engineer-stuff\gpt-engineer(main -> origin)
(GPT_Engineer) λ python gpt_engineer\main.py projects\neural-network

**Comment by AntonOsika** [comment]
Stale
