### ISSUE TITLE
You should explicitly warn user you are collecting data

### ISSUE THREAD

**Issue by bhy** [AntonOsika/gpt-engineer#455]
This should be put in README,  instead of hidden inside Term of Use.

Also defining `COLLECT_LEARNINGS_OPT_OUT=true` has no effect since what the code actually check is `COLLECT_LEARNINGS_OPT_IN`.

**Comment by AntonOsika** [comment]
Yes totally, I've been aware – called for PRs ASAP on this since #415 but didn't get any time to code outside my ordinary job.

Fixed now in #471 🏃 🏃
