### ISSUE TITLE
[SUGGESTION] Web Interface for GPT-Engineer

### ISSUE THREAD

**Issue by SumitKumarDev10** [AntonOsika/gpt-engineer#456]
This idea of **GPT-Engineer** is great. If we make a web interface for this project, we might even be able to gather up even more contributers.
Coding will be made easier, more efficient than ever. Showing off our idea on the website will be great.

**Comment by SumitKumarDev10** [comment]
I will be working on the web interface and will be using Flask, HTML, CSS, Bootstrap. If anybody has any other idea, then they can help me out.

**Comment by SumitKumarDev10** [comment]
I need help in designing the website, what webpages it will have and functionality it will exhibit. I have a few ideas as follows:-

- Index Page
- About Us Page
- Getting Started Page
- Documentation Page
- Blog Page
- Community Page
I am taking [Pandas Website](https://pandas.pydata.org/) as an inspiration.

**Comment by SumitKumarDev10** [comment]
Should a new repository be started or we should continue with the current repo from the folder `gpt-engineer/web`(This folder is not created yet.)**?**

**Comment by SaiPanneerselvam** [comment]
> I need help in designing the website, what webpages it will have and functionality it will exhibit. I have a few ideas as follows:-
> 
> * Index Page
> * About Us Page
> * Getting Started Page
> * Documentation Page
> * Blog Page
> * Community Page
>   I am taking [Pandas Website](https://pandas.pydata.org/) as an inspiration.

i use html as main.

**Comment by hannesdelbeke** [comment]
> Should a new repository be started or we should continue with the current repo from the folder `gpt-engineer/web`(This folder is not created yet.)**?**

I'd suggest to close this issue, and start a new repo where you use GPT-engineer as a dependency.
I look forward to testing it ou 💪

**Comment by jenspacito** [comment]
Hears good. I will do the same.
This time at the moment ate so creazy. All is changing, all comes new. Disruption 100%.
In 5 year look every back, an say: why i not see this.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SumitKumarDev10** [comment]
@hannesdelbeke I don't have a paid account to OpenAI API

**Comment by SumitKumarDev10** [comment]
I have done my **Initial Commit** of the **website**.
To see the website run the command `python3 web/web_main.py` while in the **_gpt-engineer directory_**.

**Comment by AntonOsika** [comment]
Great idea. I know two friends working on this also.

Do you want to move this convo to GH discussions / Discord to make issues cleaner though?

**Comment by SumitKumarDev10** [comment]
Yeah! That's a great idea.

**Comment by SumitKumarDev10** [comment]
> Great idea. I know two friends working on this also.
> 
> Do you want to move this convo to GH discussions / Discord to make issues cleaner though?
I think GH discussions is good.

**Comment by SumitKumarDev10** [comment]
> Great idea. I know two friends working on this also.
> 
> Do you want to move this convo to GH discussions / Discord to make issues cleaner though?

I think Github Discussions is great.

**Comment by SumitKumarDev10** [comment]
Opened discussions on [Web Interface for GPT-Engineer](https://github.com/AntonOsika/gpt-engineer/discussions/481)

**Comment by mindwellsolutions** [comment]
This would be an incredible feature. The ability to pre-define specific requirements and best routes of development and save presets of those setting environments would be great. That way people can build dev workflows by loading preset of specific dev details before giving GPT-Egineer it's prompt. It would also help guide gpt-engineer to have a better context for its pre-dev questions. Knowing in advance more contextual detail of what the user is looking for. 

Can't wait to try this out. thanks everyone.

**Comment by ATheorell** [comment]
Housekeeping here: I see that this issue has been stale for a while and its not totally clear to me whether:

1. This is being developed as part of gpt-engineer
2. This is being developed as a separate repo with gpt-engineer as a dependency
3. Anything at all is still being developed

Adding the triage flag.

**Comment by ATheorell** [comment]
Closing due to overdue triage label
