### ISSUE TITLE
The python files that gpt-engineer generated are named incorrectly.

### ISSUE THREAD

**Issue by TilakMaddy** [AntonOsika/gpt-engineer#460]
So my prompt was the following . . 

```
We are creating a tool that can talk to Chat GPT using openai-python . It reads log files that are generated during software builds. When it comes across any messages that indicate failure due to missing libraries, etc., it will suggest a Linux command for the user to execute in his terminal. That should fix the whole software build process
```
Keep in mind I know that cut-off date for gpt's knowledge is 2021.  However, I wanted to experiment with it.

Although it couldn't really complete the project for us, it generated some neat class-based abstractions. But the filenames are invalid and it appears to me that it is an easy problem to fix. IDK...I'm yet to dive into the codebase 

Here's a screenshot

![image](https://github.com/AntonOsika/gpt-engineer/assets/11134428/0105a38b-f648-4040-8c25-203c21ab27d8)

**Comment by TilakMaddy** [comment]
Why can't the regex remove backticks

**Comment by AntonOsika** [comment]
Yes. Please add a regex to remove backticks from the filename, to the function chat_to_files. Leave everything else the same.

**Comment by Mark2Mark** [comment]
Please note that this is not only happening with python files. I also see this happening with .js files

**Comment by AntonOsika** [comment]
I think we already had this check. Surprised you got this error, maybe you weren’t on the latest release.

**Comment by KelvinMW** [comment]
With the latest release 0.0.7. PHP files generated have same naming issue:
![image](https://github.com/AntonOsika/gpt-engineer/assets/14296120/e97ede8a-9b69-4dac-bf64-78245717af92)
