### ISSUE TITLE
My db.py file doesn't contain an archive definition

### ISSUE THREAD

**Issue by pestikoko11** [AntonOsika/gpt-engineer#487]
My db.py file doesn't contain an archive definition.
What should I do?

This is the error:
<img width="930" alt="Képernyőfotó 2023-07-03 - 20 43 33" src="https://github.com/AntonOsika/gpt-engineer/assets/138319244/ffca5eff-aa3c-4af1-9c5c-15ad7ce352c7">

And this is my db.py file:
<img width="756" alt="Képernyőfotó 2023-07-03 - 20 44 19" src="https://github.com/AntonOsika/gpt-engineer/assets/138319244/a13adf84-2378-4cb1-94d5-1f7cae8ca8a9">

**Comment by Ceilo** [comment]
> My db.py file doesn't contain an archive definition. What should I do?

> check all module names for any errors that they are correct and verify all modules are properly installed with the packages dependencies necessary for your project.

> make sure there is no extra "PLUGINS/requirements/INSTRUMENTS/TOOLS etc that may be required for importing the `archive` module

> fixed a few typos you had in there but now this should run correctly


`from dataclasses import dataclass
from pathlib import Path

# This class represents a simple database that stores its data as files in a directory.
class DB:
    """A simple key-value store, where keys are filenames and values are file contents"""

    def __init__(self, path):
        self.path = Path(path).absolute()
        self.path.mkdir(parents=True, exist_ok=True)

    def __contains__(self, key):
        return (self.path / key).is_file()

    def __getitem__(self, key):
        full_path = self.path / key
        if full_path.is_file():
            with full_path.open("r", encoding="utf-8") as f:
                return f.read()
        raise KeyError(key)

    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default

    def __setitem__(self, key, val):
        full_path = self.path / key
        full_path.parent.mkdir(parents=True, exist_ok=True)

        if isinstance(val, str):
            full_path.write_text(val, encoding="utf-8")
        else:
            # if val is neither a string nor bytes, raise an error.
            raise TypeError("val must be either a str or bytes")

# dataclass for all dbs:
@dataclass
class DBs:
    memory: DB
    logs: DB
    preprompts: DB
    input: DB 
    workspace: DB
`

**Comment by AntonOsika** [comment]
Thanks @uthpala1000
