### ISSUE TITLE
How can I use autocomplete mode? do not input some info from user

### ISSUE THREAD

**Issue by beckchou** [AntonOsika/gpt-engineer#490]
I try a web html project,when I run "gpt-engineer projects/example", it will output the log and need I to input some action,but I do not 
want to give some prompt. Beacuse my project is running in a web.  I need a autocomplate mode, only run "gpt-engineer projects/example",it will give me code directly. Thanks

**Comment by Ceilo** [comment]
--interaction-mode continuous 

This adds a more lined up manner for engineer to have conversations with users so you can keep following up with questions or building to prior information submitted for inputs so it will always give you a return of some sort just depending what you are trying to get as an return. 

Hope that helps
