### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by Sukkle** [AntonOsika/gpt-engineer#493]
I have followed every step of the readme file and other guides.
but i keep getting the following error when i try to run the main.py

\main.py", line 10, in <module>
    from gpt_engineer.db import DB, DBs, archive
ImportError: cannot import name 'archive' from 'gpt_engineer.db'

i have also tried deleting it and doing everything over.

**Comment by abrStan** [comment]
same trouble here, I checked content  of this DB.py file at the environment folder, my path was: C:\ProgramData\anaconda3\envs\gpt-engineer\Lib\site-packages\gpt_engineer\db.py

It did not have this part of code:

`def archive(dbs: DBs):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    shutil.move(
        str(dbs.memory.path), str(dbs.archive.path / timestamp / dbs.memory.path.name)
    )
    shutil.move(
        str(dbs.workspace.path),
        str(dbs.archive.path / timestamp / dbs.workspace.path.name),
    )
    return []` 
    maybe that is the issue? 
Although after adding that definition, same error persists.

**Comment by o-abdalqader** [comment]
Same issue here. I was using version 0.0.3 before and it was working. The issue occurred only when I pull the latest repository (V 0.0.7)

**Comment by KalinYorgov** [comment]
Same issue!

**Comment by Heaford** [comment]
Same too

**Comment by 3090goBRRR** [comment]
#MeToo

**Comment by kpkpkp** [comment]
Came to say the same!

**Comment by AntonOsika** [comment]
Can you please try `pip uninstall gpt-engineer` and then install again and let me know if it helps? (to install, either `pip install gpt-engineer` or `pip install -e .`)

**Comment by AntonOsika** [comment]
See #487

**Comment by Sukkle** [comment]
Just fix the damn program and update the files...

**Comment by Sukkle** [comment]
> Just fix the damn program and update the files...
