### ISSUE TITLE
I am having an issue running gpt-engineer. Everytime I either gpt-engineer command or python main.py my-newproject command I get the issue below.

### ISSUE THREAD

**Issue by cardoza1991** [AntonOsika/gpt-engineer#495]
(gpt-eng) abc@underground-nexus:~/gpt-engineer$ gpt-engineer my-new-project
Traceback (most recent call last):
  File "/home/abc/anaconda3/envs/gpt-eng/bin/gpt-engineer", line 5, in <module>
    from gpt_engineer.main import app
  File "/home/abc/gpt-engineer/gpt_engineer/main.py", line 12, in <module>
    from gpt_engineer.db.archive import archive
ModuleNotFoundError: No module named 'gpt_engineer.db.archive'; 'gpt_engineer.db' is not a package

**Comment by cardoza1991** [comment]
(gpt-eng) abc@underground-nexus:~/gpt-engineer$  pip install -e .
Obtaining file:///home/abc/gpt-engineer
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: black==23.3.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (23.3.0)
Requirement already satisfied: click>=8.0.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (8.1.3)
Requirement already satisfied: mypy==1.3.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (1.3.0)
Requirement already satisfied: openai==0.27.8 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.27.8)
Requirement already satisfied: pre-commit==3.3.3 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (3.3.3)
Requirement already satisfied: pytest==7.3.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (7.3.1)
Requirement already satisfied: ruff==0.0.272 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.0.272)
Requirement already satisfied: termcolor==2.3.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (2.3.0)
Requirement already satisfied: typer>=0.3.2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.9.0)
Requirement already satisfied: rudder-sdk-python==2.0.2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (2.0.2)
Requirement already satisfied: dataclasses-json==0.5.7 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.5.7)
Requirement already satisfied: tiktoken in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.4.0)
Requirement already satisfied: tabulate==0.9.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from gpt-engineer==0.0.7) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from black==23.3.0->gpt-engineer==0.0.7) (1.0.0)
Requirement already satisfied: packaging>=22.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from black==23.3.0->gpt-engineer==0.0.7) (23.1)
Requirement already satisfied: pathspec>=0.9.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from black==23.3.0->gpt-engineer==0.0.7) (0.11.1)
Requirement already satisfied: platformdirs>=2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from black==23.3.0->gpt-engineer==0.0.7) (3.8.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from dataclasses-json==0.5.7->gpt-engineer==0.0.7) (3.19.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from dataclasses-json==0.5.7->gpt-engineer==0.0.7) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from dataclasses-json==0.5.7->gpt-engineer==0.0.7) (0.9.0)
Requirement already satisfied: typing-extensions>=3.10 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from mypy==1.3.0->gpt-engineer==0.0.7) (4.7.1)
Requirement already satisfied: requests>=2.20 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from openai==0.27.8->gpt-engineer==0.0.7) (2.31.0)
Requirement already satisfied: tqdm in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from openai==0.27.8->gpt-engineer==0.0.7) (4.65.0)
Requirement already satisfied: aiohttp in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from openai==0.27.8->gpt-engineer==0.0.7) (3.8.4)
Requirement already satisfied: cfgv>=2.0.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pre-commit==3.3.3->gpt-engineer==0.0.7) (3.3.1)
Requirement already satisfied: identify>=1.0.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pre-commit==3.3.3->gpt-engineer==0.0.7) (2.5.24)
Requirement already satisfied: nodeenv>=0.11.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pre-commit==3.3.3->gpt-engineer==0.0.7) (1.8.0)
Requirement already satisfied: pyyaml>=5.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pre-commit==3.3.3->gpt-engineer==0.0.7) (6.0)
Requirement already satisfied: virtualenv>=20.10.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pre-commit==3.3.3->gpt-engineer==0.0.7) (20.23.1)
Requirement already satisfied: iniconfig in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pytest==7.3.1->gpt-engineer==0.0.7) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from pytest==7.3.1->gpt-engineer==0.0.7) (1.2.0)
Requirement already satisfied: monotonic~=1.5 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (1.6)
Requirement already satisfied: backoff~=2.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (2.2.1)
Requirement already satisfied: python-dateutil~=2.2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (2.8.2)
Requirement already satisfied: python-dotenv~=0.21.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (0.21.1)
Requirement already satisfied: deprecation~=2.0.6 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (2.0.7)
Requirement already satisfied: regex>=2022.1.18 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from tiktoken->gpt-engineer==0.0.7) (2023.6.3)
Requirement already satisfied: setuptools in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from nodeenv>=0.11.1->pre-commit==3.3.3->gpt-engineer==0.0.7) (67.8.0)
Requirement already satisfied: six>=1.5 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from python-dateutil~=2.2->rudder-sdk-python==2.0.2->gpt-engineer==0.0.7) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from requests>=2.20->openai==0.27.8->gpt-engineer==0.0.7) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from requests>=2.20->openai==0.27.8->gpt-engineer==0.0.7) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from requests>=2.20->openai==0.27.8->gpt-engineer==0.0.7) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from requests>=2.20->openai==0.27.8->gpt-engineer==0.0.7) (2023.5.7)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from virtualenv>=20.10.0->pre-commit==3.3.3->gpt-engineer==0.0.7) (0.3.6)
Requirement already satisfied: filelock<4,>=3.12 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from virtualenv>=20.10.0->pre-commit==3.3.3->gpt-engineer==0.0.7) (3.12.2)
Requirement already satisfied: attrs>=17.3.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/abc/anaconda3/envs/gpt-eng/lib/python3.11/site-packages (from aiohttp->openai==0.27.8->gpt-engineer==0.0.7) (1.3.1)
Building wheels for collected packages: gpt-engineer
  Building editable for gpt-engineer (pyproject.toml) ... done
  Created wheel for gpt-engineer: filename=gpt_engineer-0.0.7-0.editable-py3-none-any.whl size=5575 sha256=392ae51e5e771df25db93f36f5ea77856f08b0ac02f939b5ed15b0a184cd872d
  Stored in directory: /tmp/pip-ephem-wheel-cache-exa159l8/wheels/98/7c/ea/7c00a200dfa058a0225a59abe3c799560fbb051f448857c2df
Successfully built gpt-engineer
Installing collected packages: gpt-engineer
  Attempting uninstall: gpt-engineer
    Found existing installation: gpt-engineer 0.0.7
    Uninstalling gpt-engineer-0.0.7:
      Successfully uninstalled gpt-engineer-0.0.7
Successfully installed gpt-engineer-0.0.7
(gpt-eng) abc@underground-nexus:~/gpt-engineer$

**Comment by georgebrianb** [comment]
Same here!

**Comment by AntonOsika** [comment]
I think you might need to reinstall
