### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by ahmadawais** [AntonOsika/gpt-engineer#5]
Thanks for your work.

Steps I took,

- Cloned the repo
- Used the example/main_prompt and filled with instructions
- Ran `pip install -r requirements.txt`
- I'm using `python3` so ran `python3 main.py example`
- and go this error

```sh
Traceback (most recent call last):
  File "/Users//Documents//gpt-engineer/./main.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

Not a py coder, what could I be doing wrong?

**Comment by AntonOsika** [comment]
I think your default pip is not attached to your default python

`pip3 install ...` might work
Or:
`python3 -m pip install ...`
