### ISSUE TITLE
Script can't create templates folder under workspace automatically 

### ISSUE THREAD

**Issue by navyfighter12** [AntonOsika/gpt-engineer#50]
It seems to not be able to create a folder called templates in the workspace. I was able to create one manually and then restart the whole process. 

│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  key = 'templates/index.html'                                                                │ │
│ │ self = <db.DB object at 0x0000020342D50850>                                                  │ │
│ │  val = '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta     │ │
│ │        nam'+2029                                                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\navy\\Desktop\\gpt-engineer\\my-new-project\\workspace\\templates\\index.html'

**Comment by w3bdesign** [comment]
Try running it outside of the \Desktop folder, like C:\gpt-engineer\my-new-project and ensure you run the shell (or cmd) as an Administrator to ensure you have the proper write permissions.

**Comment by patillacode** [comment]
Many changes have been applied since you posted this, give the latest version a try.

If you wish to reopen the issue please do following the new issue template.
