### ISSUE TITLE
No_NewLine  between feedback commands And Traceback error while exiting

### ISSUE THREAD

**Issue by mdabir1203** [AntonOsika/gpt-engineer#501]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

## Issue Template
While giving feedback its giving traceback errors 

## Expected Behavior
It should exit normally
## Current Behavior

![image](https://github.com/AntonOsika/gpt-engineer/assets/66947064/7992c65e-2187-49cb-bd32-2be8595c0db4)
![image](https://github.com/AntonOsika/gpt-engineer/assets/66947064/e6d01887-7830-4e96-ae65-6719242b1a57)

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 > generate your codebase
2. step 2 > it asks to give feedback on learning and unlearning
3. step 3 > Also no newline between them

**Comment by AntonOsika** [comment]
Should be fixed on main branch
