### ISSUE TITLE
Can't get Requirements Nor Insert API Key

### ISSUE THREAD

**Issue by sephdm** [AntonOsika/gpt-engineer#508]
I'm running in a conda environment. I don't know why I'm having such a difficult time but but you've changed things and it's not straightforward to run the requirements anymore i'm not even sure if they're necessary if that's why you've taken out the text file. And I'm getting an error that I need to install my api key but I can't seem to find where to put it.

I feel like I must be missing something straightforward here but can someone please explain.

**Comment by sephdm** [comment]
Okay I was able to get requirements going using pip install -e .

I didn't realize the period at the end was required :)

**Comment by sephdm** [comment]
export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ export OPENAI_API_KEY=[sk-w2J4G9uXjEUYsUnNr2bvT3BlbkFJBhexm5wWZ0jfpXP ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

This is the error message I'm getting when I try to use export OPENAI_API_KEY=[your api key]
Of course having replaced between the square brackets with my own API key

**Comment by sephdm** [comment]
$env:OPENAI_API_KEY="[your api key]" on powershell

OK I'm not sure but I think this one might have worked because it immediately went back to the main folder address prompt. I guess I'll try running a project now and see if it doesn't give me the api error

**Comment by LeeStevens318** [comment]
As specified in the README:

> Alternative for Windows
>
>    set OPENAI_API_KEY=[your api key] on cmd
>    $env:OPENAI_API_KEY="[your api key]" on powershell

You also don't need to include the '[' and ']'.

**Comment by AntonOsika** [comment]
Cool closing
