### ISSUE TITLE
Error with Promtfile

### ISSUE THREAD

**Issue by Katus4** [AntonOsika/gpt-engineer#509]
When I try to run the example file I get this error even though there is something in the prompt file, which you can see from the screenshots is in the example folder. Does anyone know how I can solve this problem?

![Screenshot_Error](https://github.com/AntonOsika/gpt-engineer/assets/62028361/cf8c7992-eca9-4bed-b258-bc1bf279082b)

![Screenshot_of_promt](https://github.com/AntonOsika/gpt-engineer/assets/62028361/a3d573b1-b9da-4201-9980-709c543dadde)

![image](https://github.com/AntonOsika/gpt-engineer/assets/62028361/dd8edc0d-3248-4d1c-9813-c388f4b81fb5)

**Comment by mindwellsolutions** [comment]
I get the same error on Ubuntu 22.04

**Comment by Katus4** [comment]
This didn't worked, the terminal command gpt-egineer /projects/snake-game/ is a  unknown command in the Terminal and the error looks the same. But I have crated the new folder with the coppied prompt as seen in the new screenshot,

![image](https://github.com/AntonOsika/gpt-engineer/assets/62028361/c14e2ff2-388a-4efb-bb20-d5d656384720)

This is the command i tried to run:
C:\Users\user\gpt-engineer\gpt_engineer>python main.py snake-game

> The issue is that you don't have a prompt file within the project folder you are running with the gpt-engineer command:
> 
> Solution:
> 
> 1. create a new folder within the GPT-ENGINEER /projects/ folder you have loaded in VS code called: **snake-game**
> 2. copy the "prompt" file from /example/ into the /snake-game/ folder you created
> 3. run this terminal command: gpt-egineer /projects/snake-game/
> 4. If you want to create other projects, repeat the process but create a different folder name than snake-name and update the terminal command to point to that new folder instead.
> 
> ![image](https://user-images.githubusercontent.com/38707551/251570570-a2b6114b-d39a-42d2-83dd-191cc1d45d6c.png)

**Comment by mindwellsolutions** [comment]
You are actually really close to getting this to work. This should get you past the final steps:

1) cd C:\Users\user\gpt-engineer\gpt_engineer\projects\
2) gpt-engineer snake-game

You may need to first activate your conda or virtual environment before running these commands, but this should work. 

You just need to CD (Change directory) to folder C:\Users\user\gpt-engineer\gpt_engineer\projects\. Then run the main.py :

**Comment by Katus4** [comment]
Thank you for your help, this worked perfectly for me.

**Comment by 3090goBRRR** [comment]
> You are actually really close to getting this to work. This should get you past the final steps:
> 
> 1. cd C:\Users\user\gpt-engineer\gpt_engineer\projects\
> 2. Make sure prompt file is in C:\Users\user\gpt-engineer\gpt_engineer\projects\snake-game\
> 3. gpt-engineer snake-game
> 
> If you used a virtual environment you may need to first activate your conda or virtual environment before running these commands, but this should work.
> 
> You just need to CD (Change directory) to folder C:\Users\user\gpt-engineer\gpt_engineer\projects. Then run: gpt-engineer [folder name]: (gpt-engineer snake-game)

But... There is no projects folder in GPT_Engineer. I cannot get any of this to work correctly. :(

**Comment by Katus4** [comment]
> > You are actually really close to getting this to work. This should get you past the final steps:
> > 
> > 1. cd C:\Users\user\gpt-engineer\gpt_engineer\projects\
> > 2. Make sure prompt file is in C:\Users\user\gpt-engineer\gpt_engineer\projects\snake-game\
> > 3. gpt-engineer snake-game
> > 
> > If you used a virtual environment you may need to first activate your conda or virtual environment before running these commands, but this should work.
> > You just need to CD (Change directory) to folder C:\Users\user\gpt-engineer\gpt_engineer\projects. Then run: gpt-engineer [folder name]: (gpt-engineer snake-game)
> 
> But... There is no projects folder in GPT_Engineer. I cannot get any of this to work correctly. :(

Yes this ist the new problem  I faced after trying the above steps.

**Comment by AntonOsika** [comment]
Seems like this is solved!
