### ISSUE TITLE
Docker Compose Support

### ISSUE THREAD

**Issue by karlderkaefer** [AntonOsika/gpt-engineer#524]
GPT engineer does make some system calls: writing files, executing script, reading environment variables. For our own security can you provide a docker image and docker-compose file so that it can in an isolated context? For example as in [LocalAI](https://github.com/go-skynet/LocalAI/blob/master/docker-compose.yaml)

**Comment by yanisywd** [comment]
Hey @karlderkaefer,

Great suggestion about Docker! I totally agree, it would make running gpt-engineer a lot more secure and hassle-free. I can't whip up a Dockerfile and docker-compose.yml file for you right now, but I can give you a rough idea of what they might look like:

Dockerfile:
-----------------------------------
FROM python:3.8

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

CMD ["python", "main.py"]
-----------------------------------
docker-compose.yml:
----------------------------------
version: '3'
services:
  gpt-engineer:
    build: .
    volumes:
      - .:/app
----------------------------------

After you've got those files, you can build and run with docker-compose up --build. This is pretty basic, so you'll likely need to tweak it to fit your needs.

Hope this helps, and if you end up getting it to work, I'm sure the community would love to see your Docker setup!

**Comment by karlderkaefer** [comment]
@yanisywd sure I will prepare a pull request

**Comment by karlderkaefer** [comment]
Wanted to start to working on docker support, just noticed somebody already did a PR #529, added my comments there. I believe docker is enough since we have no other dependency to run
