### ISSUE TITLE
Unable to Install requirements.txt

### ISSUE THREAD

**Issue by KobyNoguchi** [AntonOsika/gpt-engineer#525]
Unable to find requirements.txt to download from. As a result typer module, AI, Fallback module dependencies are throwing errors. Apologies if this is just a simple misconfiguration mistake. I've git cloned the repo 3 times in different directories, following the same steps in the README file with the same results. any and all help is appreciated.

**Comment by ayoubfletcher** [comment]
The dependencies exists in pyproject.toml to install them run "pip install -e ." in the folder where pyproject.toml exists.

**Comment by KobyNoguchi** [comment]
Thank you! Worked like a charm

**Comment by BinarySwami-10** [comment]
@AntonOsika please mark issue closed, seems like many people have difficulty with this, add NOTE in readme.md.

**Comment by siddhijain47** [comment]
> The dependencies exists in pyproject.toml to install them run "pip install -e ." in the folder where pyproject.toml exists.
Hi @ayoubfletcher 
I am running from there only but facing error file setup.py not found
![image](https://github.com/AntonOsika/gpt-engineer/assets/62420535/4c03cb7a-544d-4411-9ee6-10ca430ab53c)

**Comment by ayoubfletcher** [comment]
@siddhijain47 The error you are having is related to the pip version, and make sure to use python3 if you are not using already.
Run to this command to upgrade pip: python3 -m pip install --upgrade pip

**Comment by ayoubfletcher** [comment]
@siddhijain47 If you still having issues installing it, you could install via `pip install gpt-engineer`

**Comment by yanisywd** [comment]
Hey @siddhijain47,

Just to double-check, did you manage to upgrade pip and use python3 like @ayoubfletcher suggested? If you're still encountering issues, please make sure you're running these commands in the correct project directory, where the pyproject.toml file is located. If all else fails, try installing gpt-engineer directly using pip install gpt-engineer.
