### ISSUE TITLE
Prompt in project directory but still get AssertionError

### ISSUE THREAD

**Issue by thatgenericguy** [AntonOsika/gpt-engineer#528]
I installed the stable release using pip. When I try to run: `gpt-engineer projects/example` I get "AssertionError: Please put your prompt in the file `prompt` in the project directory"
I have tried: 
-Creating a text file 'prompt' with the prompt inside of "example"
-Creating a folder called 'prompt' where I have the same text file within
-Using powershell within Visual Studio as a project
-Using powershell externally
-Using cmd
-Renaming the prompt file as 'main_prompt'

Nothing seems to work. Please help.

Steps to Reproduce:

1. In cmd run `pip install gpt-engineer`
2. Create main folder "gpt-test" on desktop
3. Create folders: "projects/example" within "gpt-test"
4. Create prompt.txt within "example" with a prompt
5. In cmd run `cd desktop/gpt-test`
6. Then run `set OPENAI_API_KEY=[your api key]`
7. Then run `gpt-engineer projects/example`

**Comment by ayoubfletcher** [comment]
The prompt file should be named prompt without extension.

**Comment by petrk94** [comment]
I have the same problem, identical behavior, prompt file, without extension, on windows cmd with admin rights. Its seems to not detect that there is a text inside.

![image](https://github.com/AntonOsika/gpt-engineer/assets/19719052/0458c2e6-ef48-42a0-9e4d-1b0a5be8d994)

**Comment by ayoubfletcher** [comment]
> I have the same problem, identical behavior, prompt file, without extension, on windows cmd with admin rights. Its seems to not detect that there is a text inside.
> 
> ![image](https://user-images.githubusercontent.com/19719052/254054299-0458c2e6-ef48-42a0-9e4d-1b0a5be8d994.png)

I'll try to make a pull request to include the .txt files also. Would you please list the files in the folder? Currently, how it works you should create a prompt file without an extension inside a folder and pass that folder to the "gpt-engineer your-folder"

**Comment by ioanfesteu** [comment]
A workaround for this problem is to open the prompt file in Notepad++ save it as "Unix script file". The new file will be saved with the ".bash" extension. Edit the file name and delete the .bash extension. Then run your command. It seems is the problem is the formatting of the file.
