### ISSUE TITLE
Only python and other languages are also supported?

### ISSUE THREAD

**Issue by urbanmichal** [AntonOsika/gpt-engineer#53]
Is the gpt-engineer capable of generating python code only? If yes, is there a chance to generalize it, so we can generate e.g. C# code?

**Comment by psirdev** [comment]
Regarding to your answer, I think that the identity would have to be modified to provide accuracy and match the programming language used. Python gives a lot of freedom, but if you try for example to do a front end using C++, the AI will probably would have a lot of questions.

You have opened a door that I would love to know how far GPT can go.

I guess it's limited to the confines and limits that the model itself is capable of creating, but... Imagine you wanted to create a game, would he make a graphics engine himself? Or simply would use frameworks he has observed already on Internet.

**Comment by w3bdesign** [comment]
I have used it to generate code both for Laravel and React, and it managed to do it.

It all depends on what you tell it to develop in the prompt. 

It would be fun to do something like "Develop a website in Assembler" and see what it comes up with.

**Comment by patillacode** [comment]
To clarify, any code you are trying to generate is written by chat-gpt, not gpt-engineer.
Meaning you can generate anything that chat-gpt can generate.

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
