### ISSUE TITLE
Using gpt-engineer with Azure OpenAI

### ISSUE THREAD

**Issue by RenukaMane** [AntonOsika/gpt-engineer#530]
Hi, I am trying to test gpt-engineer by using Azure OpenAI but I am getting authentication error. I have added all the additional details that are required for the Azure OpenAI like api_base url,  model, etc. in the python file ai.py in the gpt_engineer folder. Am I missing out something can you please help me out with this issue. 

Have set the openAI API key as the windows environmnet variable. Rest all the steps have followed according to the readme file. 

<img width="946" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/53396422/d3657e3b-1e49-4f6c-adac-18125ee1f29f">

**Comment by yanisywd** [comment]
Hey @RenukaMane,

Sorry to hear you're having a tough time. Can you double-check your Azure OpenAI API key and make sure your app is picking it up correctly from the environment variable? Also, just to be sure, please confirm the endpoint URL is right. Lastly, keep in mind gpt-engineer might not work seamlessly with Azure OpenAI out of the box. It could be helpful to share more info about the error you're seeing, but remember not to post sensitive stuff like your actual API key

**Comment by izikeros** [comment]
Perhaps you need to set `openai.api_type = "azure"` either via env var or in the code?

**Comment by SebLz** [comment]
I got it working by editing a few lines in ai.py:

![image](https://github.com/AntonOsika/gpt-engineer/assets/190146/5992a061-47bd-4573-84b0-34576e37f9e9)
```
import os

....


# set up azure openai
        if not os.getenv("AZURE_OPENAI_ENDPOINT"):
            raise ValueError("To use Azure OpenAI models please set a "
                            "AZURE_OPENAI_ENDPOINT enviroment variable.") 
        if not os.getenv("AZURE_OPENAI_KEY"):
            raise ValueError("To use Azure OpenAI models please set a "
                            "AZURE_OPENAI_KEY enviroment variable.") 

        openai.api_type = "azure"
        openai.api_base = os.getenv("AZURE_OPENAI_ENDPOINT") 
        openai.api_version = os.getenv("AZURE_OPENAI_API_VERSION")
        openai.api_key = os.getenv("AZURE_OPENAI_KEY")
```

+

![image](https://github.com/AntonOsika/gpt-engineer/assets/190146/27f7eac3-6fd9-4aae-a782-c0e3e6f3a7bf)

+

![image](https://github.com/AntonOsika/gpt-engineer/assets/190146/089ba4c2-bcfc-4386-b64a-f552e9bca1a9)

Then before running GPT-Engineer, I'm setting env variables with a powershell script:

```
$env:OPENAI_API_KEY="xxx"
$env:AZURE_OPENAI_KEY="xxx"
$env:AZURE_OPENAI_API_VERSION="2023-03-15-preview"
$env:AZURE_OPENAI_ENDPOINT="https://xxx.openai.azure.com/"
```

**Comment by Rock910** [comment]
For some reason, this still doesn't work for me.
I've modified ai.py as mentioned earlier in this thread, but I get the error: 
Traceback (most recent call last):

  File "C:\Users\\AppData\Local\anaconda3\lib\site-packages\openai\api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]

KeyError: 'error'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "\gpt-engineer\gpt_engineer\main.py", line 69, in <module>
    app()

  gpt-engineer\gpt_engineer\main.py", line 59, in main
    messages = step(ai, dbs)

  File "\gpt-engineer\gpt_engineer\steps.py", line 61, in clarify
    messages = ai.next(messages, user_input, step_name=curr_fn())

  File "\gpt-engineer\gpt_engineer\ai.py", line 153, in next
    response = openai.ChatCompletion.create(

  File "Local\anaconda3\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)

  File "AppData\Local\anaconda3\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(

  File "AppData\Local\anaconda3\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)

  File "\AppData\Local\anaconda3\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(

  File "\AppData\Local\anaconda3\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(

  File "\AppData\Local\anaconda3\lib\site-packages\openai\api_requestor.py", line 405, in handle_error_response
    raise error.APIError(

openai.error.APIError: Invalid response object from API: '{ "statusCode": 404, "message": "Resource not found" }' (HTTP response code was 404)

My API key requires me to use headers, so my next function looks like this:
`def next(self, messages: List[Dict[str, str]], prompt=None, *, step_name=None):
        if prompt:
            messages += [{"role": "user", "content": prompt}]

        logger.debug(f"Creating a new chat completion: {messages}")
        response = openai.ChatCompletion.create(
            messages=messages,
            stream=True,
            #model=self.model,
            deployment_id = self.model,
          #  model = "gpt-3.5-turbo",
            #deployment_id = "gpt-35-turbo-v0301-base",
            #model = "gpt-3.5-turbo",
            temperature=self.temperature,
          #  deployment_id=self.model, 
            #deployment_id= "text-davinci-003-v1-base",
            headers = {"Ocp-Apim-Subscription-Key": api_key}
        )

        chat = []
        for chunk in response:
            delta = chunk["choices"][0]["delta"]  # type: ignore
            msg = delta.get("content", "")
            print(msg, end="")
            chat.append(msg)
        print()
        messages += [{"role": "assistant", "content": "".join(chat)}]
        logger.debug(f"Chat completion finished: {messages}")

        self.update_token_usage_log(
            messages=messages, answer="".join(chat), step_name=step_name
        )

        return messages`
        
        Not sure why this occurs.

**Comment by AntonOsika** [comment]
Solved 🚀

**Comment by sanjuadlakha** [comment]
@AntonOsika @izikeros @SebLz Followed all your suggested changes for using azure gpt-4 deployment but getting error "IndexError: list index out of range" at ai.py 50
