### ISSUE TITLE
H20.ai

### ISSUE THREAD

**Issue by hatman121** [AntonOsika/gpt-engineer#531]
Is it possible to make this work with H20.ai

**Comment by yanisywd** [comment]
Hey @hatman121,

As far as I know, gpt-engineer is set up for OpenAI's GPT models, so getting it to work with H2O.ai would probably take some heavy lifting. But who knows, maybe in the future!

**Comment by ATheorell** [comment]
Closing this answered issue, since it has been stale for a long time. Also see  #476
