### ISSUE TITLE
Problem with termcolor module

### ISSUE THREAD

**Issue by remeizo** [AntonOsika/gpt-engineer#542]
I have installed gpt-engineer and just tried running the sample program.  This is what happens when I run the command.  I have pip installed termcolor, even tried to install it directly into the python scrips folder.  It will still nor run even though the termcolor module is installed

  PS C:\Users\remei\gpt-engineer> python -m gpt_engineer.main example
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\remei\gpt-engineer\gpt_engineer\main.py", line 9, in <module>
    from gpt_engineer.collect import collect_learnings
  File "C:\Users\remei\gpt-engineer\gpt_engineer\collect.py", line 5, in <module>
    from gpt_engineer import steps
  File "C:\Users\remei\gpt-engineer\gpt_engineer\steps.py", line 9, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'
PS C:\Users\remei\gpt-engineer> where python
PS C:\Users\remei\gpt-engineer> cd..
PS C:\Users\remei> where python
PS C:\Users\remei> cd C:\Users\remei\AppData\Local\Programs\Python\Python311\Scripts
PS C:\Users\remei\AppData\Local\Programs\Python\Python311\Scripts> pip install termcolor
Requirement already satisfied: termcolor in c:\users\remei\appdata\local\programs\python\python310\lib\site-packages (2.3.0)

I have no clue what I am missing here...

**Comment by Zaloog** [comment]
it looks like your pip is from your python 3.10 version and with `python -m gpt_engineer.main example` you are using your python 3.11 version, which has no `termcolor` installed.

try `python -m pip install termcolor` this should install it for the same python version, when you execute the command like above.
In general Id recommend using the py-launcher

That way you can use
`py --version` to check which version py-launcher is using
`py -0` gives you a list of installed versions
`py -3.11` will use version 3.11 for example
so `py -3.11 -m pip install termcolor` should instal the package to your right python version
then `py -3.11 -m gpt_engineer.main example`
