### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by scheung38** [AntonOsika/gpt-engineer#544]
Could someone comment, what is the workflow here.

If after the initial code generation, if user needs to modify or add new features to existing prompt text, next run of the command gpt-engineer <folder_name> will do what?

1. Completely remove existing code?
2. Append code with new changes?
3. Or something else?

docker-compose.yml is generated but it is looking for a local.yml file? So I renamed docker-compose.yml -> local.yml and docker-compose up seems to work, but why?

**Comment by AntonOsika** [comment]
The workflow is:

1. gpt-engineer <folder that contains prompt file>
2. gpt-engineer <folder that contains feedback file> --steps feedback

Would love to get a PR that makes the docs clearer by updating the docs md files!

**Comment by AntonOsika** [comment]
Can yuo check if you think readme is clearer now @scheung38 ?
