### ISSUE TITLE
Unable to use gpt-engineer with API from a free account with OpenAI

### ISSUE THREAD

**Issue by AnkiBhatia** [AntonOsika/gpt-engineer#547]
Hi, I am using a MacOS and a free OpenAI account. 
After following the readme and setting the API key, when I run the "gpt-engineer first_auto" command, I get the following info:
 
```openai:error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False```

The execution then fails with the following error:
```openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.```

I am new to this, could you please help me understand what is happening?

**Comment by myan-ish** [comment]
`You exceeded your current quota, please check your plan and billing details.`
 
 There is a limit for how many times you can call the API in free tier.

**Comment by AnkiBhatia** [comment]
Yes, I was surprised since I have not used the API before and this was the first time I called it using apt-engineer. So whatever quota I had should have been available.
Curious to know, how many calls does gpt-engineer make to the API? (Is it a single call or multiple calls)

**Comment by 2cscsc0** [comment]
The rate limit with free tier is capped at 3 Request-Per-Minute, so maybe it uses more, a cool feature would be to choose how many requests gpt-engineer makes, not only for free-tier but also to see how results vary based on requests-count.

The other two limits are problably not the reason this error occurs because, one is the rate limit of 200 Requests-Per-Day and the other one is 40,000 Tokens-Per-Minute, which are well past 3 Requests-Per-Day

**Comment by AnkiBhatia** [comment]
Interesting.Agree the proposed feature would be useful.  It could help people like me decide if we want to upgrade to the paid version to use get-enginner or why I am not getting the results I expect.

**Comment by 2cscsc0** [comment]
After some testing the limit thing is probably not the only reason this doesn't work, because after some testing and changes to the code it seems like I always get this error even when it should be the first requests of the program. Maybe there is still hope to use this tool without paying for every try

**Comment by 2cscsc0** [comment]
I even tried it on a brand new account that has never interacted with the api before, and It still didn't fetch a single correct response without raising the error

**Comment by Sohampatra1** [comment]
Even after creating a new account that had never accessed the API previously, I was still unable to receive a single correct response from the API without also receiving an error. Is it happening in all the countries or only in my place india?

**Comment by dabbinavo** [comment]
Same error here.
Created my OpenAI account a year ago but only used ChatGPT till now. Just created an API key, checked out the `main` branch and installed it via `pip install -e .`. Running `gpt-engineer /projects/my-cool-project` leads to `INFO:openai:error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False`

**Comment by 2cscsc0** [comment]
I tested something and it seems like you will need a paid account to make api requests unless you have an account that is not older than 3 months. If it's not older than 3 months it still has free api credits and thus can also make api requests. That's unlucky ig

**Comment by toxyy** [comment]
Also getting this issue, saw on a video that you could use it in the free tier with 3.5 turbo but I'm experiencing the same issue, same graph as @dabbinavo above as well.

**Comment by 2cscsc0** [comment]
Free tier is only the first 3 (iirc) months of an OpenAI account, when it still has free tier credits left. If your account is too old, the credits are expired and you have to set up a paid account to use the API.

**Comment by GsHeri** [comment]
i'm having the same problem, and i DO have a paid ChatGPT Plus account.
but it seems that doesn't work as well?

so there's no way to get ANY api response for:
- Free Users
- ChatGPT Plus users
???

what more do i have to pay to be able to use the api? and why isn't my Plus plan accepted in any way? which subscription do i need? this feels wrong

**Comment by 2cscsc0** [comment]
No, ChatGPT Plus doesn't give you access to the openai-api, only if you have a paid plan for the openai-api you can make requests. So its a completely different thing, you would have to pay for the api seperately.

**Comment by GsHeri** [comment]
ok got it, thanks!

**Comment by danyeah** [comment]
I'm using it with a paid openAi account and i'am getting this error as well.

**Comment by AntonOsika** [comment]
Solution for now is to create a paid account

Happy to get suggestions in discussions/discord or as a PR!
