### ISSUE TITLE
Wrong Patreon link

### ISSUE THREAD

**Issue by andreymillion** [AntonOsika/gpt-engineer#548]
In the Sponsor this project the Patreon url is wrong.

It didn't work - https://www.patreon.com/gpt-engineer
Is this correct url? 
https://www.patreon.com/gpt_engineer

**Comment by AntonOsika** [comment]
Thanks, fixed this now

**Comment by AntonOsika** [comment]
The correct url is https://www.patreon.com/user?u=2497970
