### ISSUE TITLE
what is rudderstack? why is analytics being sent out in an OSS package with a baked in key?

### ISSUE THREAD

**Issue by 3p3r** [AntonOsika/gpt-engineer#557]
related to https://github.com/AntonOsika/gpt-engineer/issues/511

why is this package sending analytics out? what's the purpose of it and how is user warned before it sends them out?

specifically here: https://github.com/AntonOsika/gpt-engineer/blob/19a4c10b6e61bf431e5ca7f6cd68a892b3fee122/gpt_engineer/main.py#L61
where is the opt-out option?

**Comment by joeytwiddle** [comment]
https://github.com/AntonOsika/gpt-engineer/blob/main/TERMS_OF_USE.md?plain=1#L12

**Comment by joeytwiddle** [comment]
I think #415 is addressing this same concern.

**Comment by 3p3r** [comment]
That's fair. It's been mentioned. I'd say that, the documentation about telemetry should be mentioned in the master README. I was following a blog article that just used `pip install gpt-engineer` and if you go that route, non of the terms and conditions are presented to you before you use this software.

I would include that in the main README.
