### ISSUE TITLE
Answering Clarifications one by one?

### ISSUE THREAD

**Issue by GsHeri** [AntonOsika/gpt-engineer#558]
In the Demo Video (Snake), the clarification questions are asked one after the other. 
I just installed gpt-engineer and tried my first prompt, and i noticed it asking all of them at once.
what is the expected format for my answers? do i just separate them by numbers? like:
`1. yes 
2. no 
4. blue `
?
**is there an option toggle to get the "one by one" behavior?** i would much rather have this, because when getting 10 questions, there's a chance of pressing enter by accident when typing "shift+enter", and it's just more convenient to have them separate. 
i just had the exact problem, thought i was being asked one by one, so i answered the first question and then pressed enter, and it instantly proceeded with the rest of the program, skipping all of the other clarifications

**Comment by AntonOsika** [comment]
Should work with gpt4
