### ISSUE TITLE
GUI for the project

### ISSUE THREAD

**Issue by lordpiki** [AntonOsika/gpt-engineer#56]
The project is a bit hard to use through a command line, maybe you can add a GUI (Client). If you're planning to add it, and if you're planning to use WPF, I'll be more than happy to try to contribute to the project!

**Comment by patillacode** [comment]
Thanks for the suggestion and the offering @lordpiki 

I think it would be faster and easier to start with a web UI before going into native apps but if you want to try, be my guest, although it is maybe a bit early in the project for the GUI, I'd wait a bit.

Thanks!

**Comment by PierrunoYT** [comment]
I agree it would be cool
