### ISSUE TITLE
Let us give feedback to the AI

### ISSUE THREAD

**Issue by joeytwiddle** [AntonOsika/gpt-engineer#560]
## Problem

I gave `gtp-engineer` a simple task. It asked me some questions, and then generated a lot of Python code. Which was fine. Except I had forgotten to specify that I wanted JavaScript code!

(There may be similar situations when the code it generates differs from what I wanted. For example, one time I gave it a complex task, and it generated a skeleton project with no actual code inside the methods. I would have liked to feedback to it: "Please generate implementations for each method.")

## Solution

At the stage when it shows me the code which would be generated, I wish I could give it more information, before it actually writes the files.

For example, I might say things like:

```
Minor correction: Please generate the code in C++ instead of Python
or
Please document each function with docstrings.
or
Correction: We should use Z, not Y, for the vertical axis.
```

This would essentially let me add a new clarification, _after_ seeing the code, and then rerun `gpt-engineer`'s code-generation stage. (Or perhaps check whether `gpt-engineer` now needs to ask some more questions before proceeding.)

I think this would be very useful, if the developer notices that something is not how they wanted it.

This question to provide corrections/clarifications should be offered on repeat, in case multiple refinements are needed. (But perhaps with a warning that it costs a lot of API tokens!)

This wouldn't really need to be an extra prompt. For example, AutoGPT combines everything into one prompt.

```
Enter 'y' to proceed, 'n' to quit, or enter feedback?
```

**Comment by AntonOsika** [comment]
> Enter 'y' to proceed, 'n' to quit, or enter feedback?

Is a good idea but it would require a new architecture for things.

And sometimes you def. just want it to run.

Adding label to revisit this!
