### ISSUE TITLE
It's only using python...

### ISSUE THREAD

**Issue by GsHeri** [AntonOsika/gpt-engineer#563]
## Expected Behavior

I've seen 3 or 4 issues here asking if gpt-engineer could use languages other than python. the answer was always something like "yes, of course, it's chatgpt writing the code, so you can use everything"

## Current Behavior

no matter what i do, it is always using python. even if i explicitly forbid it to use python, and stress it in the clarifications
why?

![image](https://github.com/AntonOsika/gpt-engineer/assets/21007980/be4ad96f-4ae8-4495-be03-a7152c4f7618)

![image](https://github.com/AntonOsika/gpt-engineer/assets/21007980/a7984e8c-92d1-4584-b318-e5f43df9f92b)

**Comment by cosmopolitan033** [comment]
i encountered same problem using many kinds of gpt project on github

**Comment by Notloc** [comment]
Two things I can think of to reduce this issue, as I was experiencing this as well.

1. Do NOT tell the AI "don't use Python", don't even mention Python to it. Repeated mentions tend to make it more likely to use Python, regardless of the fact that you are telling it not to. Instead, request the desired language multiple times in your prompt.
2. Edit the preprompts in your local install. The `philosophy` file in particular, has a lot of python specific instructions, removing those should help the AI stop thinking about Python.

**Comment by AntonOsika** [comment]
✅

**Comment by AntonOsika** [comment]
PR should to philosophy should fix this
