### ISSUE TITLE
This architecture covers the core classes and functions required to build...Each class is responsible for a specific task and can be further expanded and implemented with the necessary methods and logic.  Please note that the code provided is just a skeleton and needs to be implemented with the appropriate logic and functionality.

### ISSUE THREAD

**Issue by lukehowlett97** [AntonOsika/gpt-engineer#564]
Is there any particular reason this tool only generates skeleton functions for me?  I got chatGPT to generate me a very detailed prompt for it however each time I get the codebase structure but no working code.

Tips appreciated.

**Comment by AntonOsika** [comment]
Please share exact prompt and generated code

**Comment by lukehowlett97** [comment]
Im sorry I never responded I have been busy.

Here was my prompt that I got gpt - 4 to create:

Using the historical data located at 'C:\Projects\FPL\data', build a machine learning model in python that predicts the highest scoring team for the 2023/24 Fantasy Premier League season. The data includes per season and per player statistics, along with current season's information such as game settings, PL teams info, players info, and game stats. Your task includes:

Perform exploratory data analysis to understand patterns and trends in the data.
Engineer features that capture the impact of various factors like player form, opposition strength, match location, etc.
Use time series analysis methods to forecast player performance based on past statistics.
Build predictive models using ensemble learning techniques such as Random Forests, Gradient Boosting, etc., and consider deep learning methods like LSTM.
Predict the top scoring players across the entire season. Make sure to consider the 100 million budget and the fact that you need to choose 15 players at the start of the season. Also, keep in mind that there is a possibility for one substitution per week for the first 10 weeks.
Along with the top scoring players, also predict 'value for money' players who might not score the highest points, but provide good returns based on their cost.
Evaluate the effect of home and away games on player performance and incorporate this into your model.
Analyze the influence of player's position on the scores and decide how much budget to allocate to each category (defender, midfielder, striker).
Predict the optimal times to use the various 'chips' based on patterns in the data and the model's predictions.
Perform hyperparameter tuning and model selection to choose the best model and configuration for our predictions.
Validate your model using appropriate methods like cross-validation and ensure it generalizes well on unseen data.
Finally, provide an interface or tool that allows users to input the current state of their team and receive suggestions for optimal substitutions and chip usage.
Ensure that your solution is robust, scalable, and easy to use. The final goal is to build a tool that maximizes the total points scored in the Fantasy Premier League while adhering to the budget and player selection constraints.

The data for past seasons is structured as follows:

season/cleaned_players.csv: The overview stats for the season
season/gws/gw_number.csv: GW-specific stats for the particular season
season/gws/merged_gws.csv: GW-by-GW stats for each player in a single file
season/players/player_name/gws.csv: GW-by-GW stats for that specific player
season/players/player_name/history.csv: Prior seasons history stats for that specific player
The data for the current season includes:

'C:\Projects\FPL\data\bootstrap_static.json': Contains summary of all 38 gameweeks, game’s settings, basic information on all 20 PL teams, total number of FPL Users and overall chip usage, basic information on all Premier League players, list of stats that FPL keeps track of, the different FPL positions
'C:\Projects\FPL\data\fixtures.json': Contains per match stats such as goals, assists, cards, saves, pens missed, bonus points, own goals, pens saved
'C:\Projects\FPL\data\master_team_list.csv': Contains team id for each season
'C:\Projects\FPL\data\scoring_rules.txt' contains the rules on scoring points.


Here is a copy of the content file in the memory/logs directory:

class UserInterface:
    def __init__(self):
        pass
    
    def get_user_input(self):
        # Get user input for team state
        pass
    
    def display_suggestions(self, substitutions, chip_usage):
        # Display suggestions for optimal substitutions and chip usage
        pass
This architecture covers the core classes and functions required to build the machine learning model and provide the user interface. Each class is responsible for a specific task and can be further expanded and implemented with the necessary methods and logic.

Please note that the code provided is just a skeleton and needs to be implemented with the appropriate logic.
