### ISSUE TITLE
Use mindmap instead of prompt file

### ISSUE THREAD

**Issue by sam5epi0l** [AntonOsika/gpt-engineer#565]
I am not sure if its practical but it would be great to export a mindmap (created in apps like use MindMeister, SimpleMind, Freemind, or XMind) to a text file (md, json, yml whichever works the best) and use that instead of `prompt` file.

Of course, The visual structure of mindmap will be lost when exporting mindmap to text file.

**Comment by AntonOsika** [comment]
Would be cool have had similar ideas, I think a UI is the firs step so closing

Feel free to raise in discord etc!
