### ISSUE TITLE
Support Petals as a second LLM backend

### ISSUE THREAD

**Issue by Sharpz7** [AntonOsika/gpt-engineer#570]
Users should have the option to use https://petals.dev/ as a backend instead of OpenAI to democratise access to services like this.

Specifically it should use https://github.com/petals-infra/chat.petals.dev, which provides nice API's to interact with it.

Yes, you will get a drop in performance, but long term I hope to see this removed. Especially if petals can expand to use more LLMs like https://gorilla.cs.berkeley.edu/.

**Comment by ATheorell** [comment]
Thank you for the suggestion. I will close this stale issue for good housekeeping. 
We are actively integrating more LLMs for reasons that you mentions. Exactly which ones to integrate is being discussed.
