### ISSUE TITLE
question: why are you collecting user's prompts?

### ISSUE THREAD

**Issue by Jovonni** [AntonOsika/gpt-engineer#572]
What is the reason for this? if a user wants to user this, they have to by default comment this out, or change it. Thats an interesting choice to make. You should at least be able to disable it, or better yet, its disabled by default, and you have to enable it.

https://github.com/AntonOsika/gpt-engineer/blob/12eed66dd23b6279b7a6ed643ba6edbe2fcaf99a/gpt_engineer/collect.py#L15

**Comment by b0r1sp** [comment]
Consider this as a major privacy issue.

**Comment by mwmdev** [comment]
This has been previously adressed in #415, data collection is opt-in now.

**Comment by AntonOsika** [comment]
It's only collected if consent is given. This has been explained multiple times.

See:

https://github.com/AntonOsika/gpt-engineer/pull/471
![image](https://github.com/AntonOsika/gpt-engineer/assets/4467025/688e2ce4-4409-4870-9870-ed54fadc34db)

Appreciate if we, as the community, do our research to understand what's collected, how consent works, and _why_ it's collected before jumping to conclusions that it's evil or meant to be used maliciously.

What we're trying to do, similiarly to what almost all software, openai, others does, is making gpt-engineer better by simply letting those who feel comfortable with sharing their user experience, what is working well, and what can be improved, for us to know how to make gpt-engineer great.

**Comment by b0r1sp** [comment]
I’d propose to add some clearfying comments just before the lines of code in question e.g a link to documentation which highlights your intent for collecting user data why you’d use it and how it helps to enhance your product. I’m sure this leads to a transparent situation everybody can see what’s going on and can decide upon their choice. 

Beside that, I’d propose renaming the env variable from OPT_OUT_xyz to something like OPT_IN_xyz with default to 0. 

From reading the discussions briefly I believe the whole thing happened accidentally. From my experience, coding for OSS/the community is not the whole job, it’s a lot about communication as well, so don’t take all comments personal.

**Comment by AntonOsika** [comment]
Thanks @b0r1sp 

Also to be clear:

It always asks for consent. The line you saw in the code says that one can set OPT_OUT=true so that it doesn't ask -> becomes less annoying for those that don't want to share data.
