### ISSUE TITLE
implement new feature - function calling

### ISSUE THREAD

**Issue by smoking-caterpillar** [AntonOsika/gpt-engineer#58]
With the release of gpt-3.5-turbo-0613 and gpt-4-0613, OpenAI implemented function calling which now makes it possible to call python functions via chat responses.
It can also work with GPT 3.5 for anyone not on the GPT-4 beta.
More info - https://platform.openai.com/docs/guides/gpt/function-calling

**Comment by smoking-caterpillar** [comment]
This could be used to save files to the filesystem

**Comment by Meathelix1** [comment]
> This could be used to save files to the filesystem

You can do anything with just function calling now. I would say one of the best things OpenAI has done.
