### ISSUE TITLE
No.

### ISSUE THREAD

**Issue by Mattang-Tim** [AntonOsika/gpt-engineer#59]
During the clarification of creating a chatbot like ChatGPT, I get to: "No."

![image](https://github.com/AntonOsika/gpt-engineer/assets/104371306/f7f29993-829f-43f6-ac89-54b00d76a66d)

**Comment by augusto-rehfeldt** [comment]
+1, I have the same issue (using 3.5)

**Comment by LebToki** [comment]
+1

**Comment by M-Gonzalo** [comment]
Me too :hand:

**Comment by DenizMOz** [comment]
lmao, i like how its so matter of fact about it. "No."
But yeah, same issue..

**Comment by juarezjl** [comment]
I have the same issue

**Comment by zerofill** [comment]
What exactly is it having a problem with when it just spits out No? lol I get this often as well. Anyone able to explain what causes it?

**Comment by LebToki** [comment]
Probably having a bad day :)

**Comment by brandonbothell** [comment]
It seems like here on line 46 is where the model is being asked to respond with "No.":
https://github.com/AntonOsika/gpt-engineer/blob/25a6c31d4f7b550b2efccce8a260dbe43778ea4a/gpt_engineer/steps.py#L41-L47
If you just enter 'q', it should continue. The AI is just telling you that the task is now sufficiently clear.

**Comment by patillacode** [comment]
I have seen this or something very similar in a lot of other issues, I have also seen it myself when running the app.

It might need a bit of digging imo.
Maybe correction of the prompts and/or better handling of the outcome.

**Comment by FOLLGAD** [comment]
Fixed in commit [6a3f7eb](https://github.com/AntonOsika/gpt-engineer/commit/6a3f7eb9de07922c6b2bc2b18e194bdeae2d158f)
