### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by C0FF33P4G3** [AntonOsika/gpt-engineer#590]
I recently tried using it by following the steps in the README.md file and it does not work, please update the file.

I keep getting this error when i try to export/set the API key

openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = ', or you can set the environment variable OPENAI_API_KEY=). If your API key is stored
in a file, you can point the openai module at it with 'openai.api_key_path = '. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

**Comment by pbharrin** [comment]
Thanks, this may have a similar root cause as #589 I will look into that.

**Comment by redocdm** [comment]
experiencing same issue.

**Comment by pbharrin** [comment]
I reproduced this, even with my API key set in .env (following the README) I get this error.  

I will look into getting a fix out.

**Comment by pbharrin** [comment]
If you are still getting the error after my fix, perhaps there is a problem with how you are setting your API key.  
1. are you using the .env file or the env variable?  
2. Can you show exactly how you are setting the API key in 1 without posting your exact key, perhaps replace your key with random keystrokes.

**Comment by ragazzo-br** [comment]
I'm receiving an similar error, but in my case i can put the api keys:
"INFO:openai:error_code=invalid_api_key error_message='Incorrect API key provided: [sk-PSSF*****************************************UYc]. You can find your API key at https://platform.openai.com/account/api-keys.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False"

**Comment by redocdm** [comment]
> If you are still getting the error after my fix, perhaps there is a problem with how you are setting your API key.
> 
> 1. are you using the .env file or the env variable?
> 2. Can you show exactly how you are setting the API key in 1 without posting your exact key, perhaps replace your key with random keystrokes.

I am using powershell. Still get same error.
$env:OPENAI_API_KEY = "[my key]"

error: openai.error.AuthenticationError: Incorrect API key provided: [*****************************************]. You can find your API key at https://platform.openai.com/account/api-keys.

I also updated main.py and set the api key directly in there; same error but slightly different message:

pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by AntonOsika** [comment]
Housekeeping: Closing stale issues.

Feel free to reopen if you're still having this problem!
