### ISSUE TITLE
Run benchmark for `--steps tdd` and compare to "default" benchmark results

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#596]
If --steps tdd doesn't work well, we should remove it.

If we see obvious ways to improve it, we can of course first consider fixing and see if it helps as part of the investigation.

**Comment by AntonOsika** [comment]
This is the benchmark, how to run should be self explanatory:

https://github.com/AntonOsika/gpt-engineer/blob/main/scripts/benchmark.py

**Comment by alvaromat** [comment]
I've first run the benchmarks for gpt3.5 with default steps (I don't have gpt-4). [I've open a PR to add it to the `benchmark/RESULTS.md`](https://github.com/AntonOsika/gpt-engineer/pull/625)
Now there is a reference to compare to tdd.

As a comment, running the benchmarks and checking the results manually is a very time-consuming and not enjoyable task. Also executing benchmarks multiple times would give different results. I think ideally the benchmark result collection should be performed automatically and included in the CI. For the web-based benchmarks this could be done with a cypress environment. No idea for the ones based on python cli. Would something like this be in the scope of the project?

**Comment by AntonOsika** [comment]
He @alvaromat 

Do you see a way to going end to end in automating it?

Appreciate someone taking leadership in making the flow better!

**Comment by tristmegistux** [comment]
nope

**Comment by ATheorell** [comment]
I'm closing this issue in favor of the more recent and comprehensive issue #656
