### ISSUE TITLE
GPT should be able to run command before create or edit

### ISSUE THREAD

**Issue by thammachet** [AntonOsika/gpt-engineer#598]
In some scenarios such as creating react application. GPT should be able to run npx create-react-app to init the project instead of writing the dependency by itself. 
Thank you

**Comment by AntonOsika** [comment]
Good input, will put this in the backlog since we are focusing on our [roadmap](https://github.com/AntonOsika/gpt-engineer/blob/main/ROADMAP.md)

For now a human can do this, and then ask the program to improve the created project
