### ISSUE TITLE
[Enhancement] Add multi-line support to improve prompt from existing code mode

### ISSUE THREAD

**Issue by pbharrin** [AntonOsika/gpt-engineer#599]
Some users would like to cut and paste files with multiple lines to the input prompt for improvement.  They may have an error to communicate or some other documentation.  Currently there is no way to get multiple lines with Python's `input()`.

A possible solution read multiple lines of input with a terminating delimiter.  

Here are some potential options for the terminating delimiter: 
- EOF: Ctrl-D or Ctrl-Z (Windows)
- a single blank line
- a single line with only a period
- a special sequence like: END on a single line

**Comment by AntonOsika** [comment]
I think it's better to say "answer with a single absolute file path, or relative to .gpt_eng folder, to use a prompt stored as a file" or similar. WDYT?

Also just FYI:

There is a step where the program asks for confirmation and says "you can go ahead and edit these files before confirming" that can be used to edit the prompt file and add multiline input.

**Comment by AntonOsika** [comment]
Do you know how e.g. Mentat does it?

**Comment by ATheorell** [comment]
Closing due to overdue triage label
