### ISSUE TITLE
Github action for more automation. Issues management etc

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#601]
It would be great with github actions that automate things like issue + PR management and more.

Specifically marking issues as stale after X amount of time. I imagine there are other good actions we could use. (some inspiration might exist [here](https://github.com/sdras/awesome-actions))

<details>
<summary>Checklist</summary>

- [X] `.github/workflows/automation.yml`
> * Create a new file named `automation.yml` in the `.github/workflows` directory.
> • At the top of the file, define the name of the workflow and the events that will trigger the workflow. For example, you can trigger the workflow on a schedule or when an issue or PR is created or updated.
> • Define a job for marking stale issues. Use the `actions/stale` action for this job. Specify the parameters for the action such as the days of inactivity after which an issue is considered stale, the message to be displayed when an issue is marked as stale, etc.
> • Define other jobs as needed for other tasks such as labeling issues, managing PRs, etc. Use the appropriate actions for these jobs.

</details>

**Comment by kevinlu1248** [comment]
Hey I'm taking a look a this. @AntonOsika

**Comment by kevinlu1248** [comment]
Hey Anton, Sweep works better when given specific instructions. I made a new issue to tackle this, just fixing the newline issue with pre-commits right now.

We'll have Sweep auto-run pre-commits released today to make this a lot better.
