### ISSUE TITLE
Sweep: When specifying dependencies, use the packaging tool rather than generating the files

### ISSUE THREAD

**Issue by spullara** [AntonOsika/gpt-engineer#608]
### Details

For python the tool should create a new virtual environment and install the dependencies into it then pip freeze >requirements.txt to generate it.

For NPM the tool should "npm init" the "npm install" each of the dependencies to create the package.json.

Today, versions are often hallucinated and the packages specified do not exist.

<details>
<summary>Checklist</summary>

- [X] `Makefile`
> • Replace the `install-dependencies` target with the following commands to create a new virtual environment, install the dependencies, and generate the requirements.txt file:
> ```bash
> install-dependencies:
> 	@echo -e "$(COLOR_CYAN)Creating virtual environment...$(COLOR_RESET)" && \
> 	python -m venv venv && \
> 	source venv/bin/activate && \
> 	pip install -e . >> /dev/null && \
> 	pip freeze > requirements.txt
> ```

- [X] `scripts/create_package_json.sh`
> • Add the following script to initialize a new Node.js project and install the dependencies:
> ```bash
> #!/bin/bash
> npm init -y
> for dep in $@; do
>   npm install $dep
> done
> ```
> • This script takes a list of dependencies as arguments and installs each one using `npm install`.

</details>

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by AntonOsika** [comment]
I like this idea. Happy to see a PR for it.

Do you want to edit the gen_entrypoint prompt so that it achieves this @spullara ?

sweep (and other humans I think...) is confused since you're talking about the generated code, not the gpt-engineer codebase

**Comment by spullara** [comment]
Yeah, I will take a look at it and see if I can figure out the couple of places this would need to go.

**Comment by ATheorell** [comment]
Any progress on this @spullara ? If not, I will close this issue as stale

**Comment by spullara** [comment]
I'll close it for now and if I come up with a PR I'll reference this issue.
