### ISSUE TITLE
Add numpy doc strings 

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#613]
Add numpy style doc strings to all functions apart from the main.py file. 

<details>
<summary>Checklist</summary>

- [X] `gpt_engineer/ai.py`
> • For each function in this file, add or replace the existing docstring with a numpy-style docstring. The docstring should include a brief description of the function, a list of parameters with their types and descriptions, and a description of the return value.

- [X] `gpt_engineer/chat_to_files.py`
> • For each function in this file, add or replace the existing docstring with a numpy-style docstring. The docstring should include a brief description of the function, a list of parameters with their types and descriptions, and a description of the return value.

- [X] `gpt_engineer/collect.py`
> • For each function in this file, add or replace the existing docstring with a numpy-style docstring. The docstring should include a brief description of the function, a list of parameters with their types and descriptions, and a description of the return value.

- [X] `gpt_engineer/db.py`
> • For each function in this file, add or replace the existing docstring with a numpy-style docstring. The docstring should include a brief description of the function, a list of parameters with their types and descriptions, and a description of the return value.

- [X] `gpt_engineer/learning.py`
> • For each function in this file, add or replace the existing docstring with a numpy-style docstring. The docstring should include a brief description of the function, a list of parameters with their types and descriptions, and a description of the return value.

</details>

**Comment by kevinlu1248** [comment]
Looks like a small matching error we have: we'll fix it soon.

**Comment by kevinlu1248** [comment]
Never mind, it just looks like GPT-4's lack of common sense, even with CoT prompting, let me fix this.

**Comment by kevinlu1248** [comment]
sweep: Replace the old docstring if it already exists, otherwise, add new docstrings.

**Comment by kevinlu1248** [comment]
@AntonOsika Re-ran this and looks a lot better now. We're implementing pre-commit currently to solve all the `black` issues.

**Comment by yashosp** [comment]
is this issue is solved or should i help!

**Comment by AntonOsika** [comment]
Thanks @kevinlu1248 – great to have you here!
