### ISSUE TITLE
Improve or modify existing code

### ISSUE THREAD

**Issue by coolrazor007** [AntonOsika/gpt-engineer#62]
I've tried using a prompt to improve existing code, but it doesn't seem to work.  Has anyone else gotten this to work?
Something like "edit main.py in workspace to write console output to a logfile named log.txt".  I tried that as a test and it will not read the simple main.py in there.

I tried something very similar to what this guy did (~9:30 mark) for referencing: https://www.youtube.com/watch?v=gWy-pJ2ofEM

**Comment by liusida** [comment]
I think the current agent doesn't have the ability to read existing code, because I only see `chat_to_files.py` (convert GPT's message and store them as files) but I don't see `files_to_chat.py`. Maybe this feature will be added in the future version.

**Comment by AntonOsika** [comment]
We're working on it 🚀
