### ISSUE TITLE
Sweep: Adding support to run without API_KEY.

### ISSUE THREAD

**Issue by haseeb-heaven** [AntonOsika/gpt-engineer#626]
### Details

Try adding support to run this application without the API key.
There is term called with `ChatGPT` its called web mode it uses _ongoing_ session of Chatgpt to query all queries and get **response** as it was getting **response** from `GPT` try to add that because not everyone is willing to pay for the **API_KEY** and free accounts are always limited.

Thanks

<details>
<summary>Checklist</summary>

- [X] `gpt_engineer/ai.py`
> • Add a new method to the AI class to interact with the ongoing session of ChatGPT and get responses. This method should take the same arguments as the existing methods for interacting with the GPT-4 model.
> • Modify the existing methods to check if the API key is None. If it is, they should call the new method to interact with the ongoing session of ChatGPT instead of using the GPT-4 model via the API.

- [X] `gpt_engineer/main.py`
> • Modify the command-line interface to add a new option for the user to choose between using the API key or the web mode of ChatGPT. This option should be passed to the AI class when it is instantiated.
> • Modify the environment loading function to check if the API key is None. If it is, it should skip the loading of the environment variables.

</details>

**Comment by AntonOsika** [comment]
If you have seen other projects that do this please share @haseeb-heaven 🙏
