### ISSUE TITLE
Default docker container error

### ISSUE THREAD

**Issue by gnovelli** [AntonOsika/gpt-engineer#630]
## Command provided 
docker-compose up 

## Expected Behavior
Should pull images and run in a docker container
Should read projects/example/prompt and use it as an example of usage of gpt-engineer on an example prompt

## Current Behavior

There is an error

### Failure Logs

/app/entrypoint.sh: line 3: $'\r': command not found
INFO:openai:error_code=model_not_found error_message="The model '\r' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api

Traceback (most recent call last):

  File "/usr/local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())

  File "/app/gpt_engineer/main.py", line 83, in main
    messages = step(ai, dbs)

  File "/app/gpt_engineer/steps.py", line 93, in clarify
    user_input = get_prompt(dbs)

  File "/app/gpt_engineer/steps.py", line 54, in get_prompt
    assert (

AssertionError: Please put your prompt in the file `prompt` in the project directory

/app/entrypoint.sh: line 6: $'\r': command not found
/app/entrypoint.sh: line 8: syntax error near unexpected token `$'do\r''
'app/entrypoint.sh: line 8: `for item in "$project_dir"/*; do
/app/entrypoint.sh: line 3: $'\r': command not found
INFO:openai:error_code=model_not_found error_message="The model '\r' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api

Traceback (most recent call last):

  File "/usr/local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())

  File "/app/gpt_engineer/main.py", line 83, in main
    messages = step(ai, dbs)

  File "/app/gpt_engineer/steps.py", line 93, in clarify
    user_input = get_prompt(dbs)

  File "/app/gpt_engineer/steps.py", line 54, in get_prompt
    assert (

AssertionError: Please put your prompt in the file `prompt` in the project directory

/app/entrypoint.sh: line 6: $'\r': command not found
/app/entrypoint.sh: line 8: syntax error near unexpected token `$'do\r''
'app/entrypoint.sh: line 8: `for item in "$project_dir"/*; do

**Comment by ATheorell** [comment]
General question to this issue, what is the rational of supporting docker yet? gpt-engineer is still under rapid development (no versions seem really "stable") and the environment used so far is very simple to install manually. If we want to have docker, we should add some entries to the documentation. I'm probably not the person to do this call, because I have very basic understanding of docker... @gnovelli @FancyKat @pbharrin

**Comment by AntonOsika** [comment]
I think this is solved, happy to get PRs to improve the Docker workflow though!

**Comment by FancyKat** [comment]
> General question to this issue, what is the rational of supporting docker yet? gpt-engineer is still under rapid development (no versions seem really "stable") and the environment used so far is very simple to install manually. If we want to have docker, we should add some entries to the documentation. I'm probably not the person to do this call, because I have very basic understanding of docker... @gnovelli @FancyKat @pbharrin

I actually use it as a different purpose since it is used in my cluster I wanted to do experiments with it to talk to another LLM

**Comment by vumg-z** [comment]
"The model '\r' does not exist" 

still getting the same message using docker-compose
```

Attaching to gpt-engineer-gpt-engineer-1
gpt-engineer-gpt-engineer-1  | /app/entrypoint.sh: line 3: $'\r': command not found
gpt-engineer-gpt-engineer-1  | INFO:openai:error_code=model_not_found error_message="The model '\r' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api
```
