### ISSUE TITLE
Sweep: add langchain module to dependencies

### ISSUE THREAD

**Issue by PrenSJ2** [AntonOsika/gpt-engineer#633]
### Details

langchain[all] is missing from the dependencies

<details>
<summary>Checklist</summary>

- [ ] `pyproject.toml`
> • Add a new line under the `[tool.poetry.dependencies]` section with the content `langchain = "*"`

</details>

<details>
<summary>Checklist</summary>

- [X] `pyproject.toml`
> • Add a new line under the 'dependencies' section with the content 'langchain = "*"'.

</details>

**Comment by pbharrin** [comment]
@PrenSJ2 can you tell us what was failing?  
Should a fix have the following line: langchain[all]>0.X.X?  
The fix given by sweep-ai is a little suspicious, it doesn't have a [all] and it just changes the version number.

**Comment by pbharrin** [comment]
@PrenSJ2  last call, can you elaborate on why we should have `langchain[all]` in dependencies? If not I'm going to close this issue.
