### ISSUE TITLE
Only the last file generated is being saved, and by the wrong name.

### ISSUE THREAD

**Issue by DenizMOz** [AntonOsika/gpt-engineer#64]
Running the example (python main.py example), produces only one file in workspace.
The file is just called 'python', (no extension), and only contains whatever file it generated last.
I should mention I'm also got an incompatibility error on pip install for having typer 0.9.0, when the project asked for 0.8.0, but I dont know if thats the problem.

**Comment by jebarpg** [comment]
@DenizMOz check this out https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594148378

**Comment by patillacode** [comment]
Many changes have been applied since you posted this, give the latest version a try.

If you wish to reopen the issue please do following the new issue template.
