### ISSUE TITLE
Sweep: I was trying the -i option to improve existing code , instead of the ai modifying it I got a rate limit error

### ISSUE THREAD

**Issue by cloudbow** [AntonOsika/gpt-engineer#648]
### Details

INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..

<details open>
<summary>Checklist</summary>

- [ ] `gpt_engineer/ai.py`
> • Identify the part of the code that is responsible for making API calls to the OpenAI API. This is likely where the `completion_with_retry` method is implemented.
> • Understand how the `completion_with_retry` method works. This will help us understand why the current retry mechanism is not preventing the rate limit error.
> • Investigate the retry mechanism. If the delay before retrying is too short, it might not be enough to prevent the rate limit error.
> • Consider whether the rate limit could be increased. If the `-i` option requires more tokens than the current rate limit allows, it might be necessary to request a higher rate limit from OpenAI.
> • If increasing the rate limit is not possible or does not solve the problem, consider whether the code could be optimized to use fewer tokens. This could involve making fewer API calls, making smaller API calls, or caching the results of API calls.

</details>

**Comment by AntonOsika** [comment]
Housekeeping: Closing stale issues.
