### ISSUE TITLE
Use the path .gpteng for storing logs etc per default

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#649]
### Details

Change the workflow of gpt-engineer to be like so:

- Always set `memory` and `archive` folders paths to be to the .gpteng folder (which will create it per default if it doesn't exist)
- Always set `workspace` and `input` folder paths to be directly in the `project path`

<details open>
<summary>Checklist</summary>

- [X] `gpt_engineer/db.py`
> • Modify the `__init__` method of the DB class to set the default paths for the `memory` and `archive` folders to be in the `.gpteng` folder.
> • Modify the `__init__` method of the DB class to set the default paths for the `workspace` and `input` folders to be in the `project path`.
> • Modify the `__init__` method of the DB class to create the `.gpteng` folder if it does not exist.

- [X] `tests/test_db.py`
> • Update any tests related to the default paths of the `memory`, `archive`, `workspace`, and `input` folders to reflect the changes in the DB class's `__init__` method.
> • Add a test to verify that the `.gpteng` folder is created if it does not exist.

- [X] `docs/intro/db_class.md`
> • Document the changes to the default paths of the `memory`, `archive`, `workspace`, and `input` folders.
> • Document the creation of the `.gpteng` folder if it does not exist.

</details>

**Comment by ATheorell** [comment]
Closing this in favor of #669  and #665
