### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by juarezjl** [AntonOsika/gpt-engineer#65]
Getting this error in ai.py when try to run the example:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from ai import AI
  File "/workspace/AI/gpt-engineer/ai.py", line 4, in <module>
    class AI:
  File "/workspace/AI/gpt-engineer/ai.py", line 30, in AI
    def next(self, messages: list[dict[str, str]], prompt=None):
TypeError: 'type' object is not subscriptable

Line 30:
```
def next(self, messages: list[dict[str, str]], prompt=None):
        if prompt:
            messages = messages + [{"role": "user", "content": prompt}]

        response = openai.ChatCompletion.create(
            messages=messages, stream=True, **self.kwargs
        )

        chat = []
        for chunk in response:
            delta = chunk['choices'][0]['delta']
            msg = delta.get('content', '')
            print(msg, end="")
            chat.append(msg)
        return messages + [{"role": "assistant", "content": "".join(chat)}]
```

I'm using python 3.9

**Comment by juarezjl** [comment]
works with python 3.10

**Comment by puniith09** [comment]
For python3.8🥲 people 

Install typing, 
pip install typing

In file import these two
from typing import List, Dist

And replace like this
def next(self, messages: List[Dict[str, str]], prompt=None):

**Comment by anthony-gray47** [comment]
Just a small update from puniitho09:

from typing import List, Dict

Dist -> Dict
