### ISSUE TITLE
subreddit /r/gptengineer/ support

### ISSUE THREAD

**Issue by jebarpg** [AntonOsika/gpt-engineer#66]
To help bring more people on board and get more eyes to further the development of gpt-engineer I have started a subreddit for people to ask questions, post help, announce advancements, and start to participate in more discussions on a friendly platform (for the average joe) outside of github.

Let me know what type of flare topics would be of interest for people. I'll add them as we go.

**Comment by HariAcharya80** [comment]
Why not have a discussion section over here too ?

**Comment by jebarpg** [comment]
+1

**Comment by jebarpg** [comment]
Made a quick logo for the project on the subreddit page, any feedback is more than welcome. I'm not an artist so I am not ego bonded on criticism or critic. Looking for to ideas and changed. Let me know if you need the file for anything.

**Comment by flexchar** [comment]
Due to the recent Reddit API changes, I'd also highly vote to have the discussion here. When it's closer to the code, it's far more helpful. Especially with the idea in mind that we will be mainly focusing on developers.

**Comment by jebarpg** [comment]
Part of the main appeal of a subreddit is greater exposure of the project. I have a post with the repo link in it. I can also have the post invite people to come chat on GitHub as well.

**Comment by backpackkat** [comment]
is anyone else having issues with their API key?

**Comment by patillacode** [comment]
Maybe this should be a discussion rather than an issue, feel free to start one if you are still interested.
