### ISSUE TITLE
Add `project_metadata` the DBs class. Instantiate it in main.py and let its path be `.gpteng`

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#665]
Add a field called `project_metadata` in the DBs class, that is of type DB.

Set project_metadata_path `.gpteng`

Use it when instantiating DBs

Move: memory, archive, file_list.txt, to project_metadata

(Also, separate PR: start writing all_output.txt to memory)

<details open>
<summary>Checklist</summary>

- [X] `gpt_engineer/project_metadata.py` ✅ Commit [`eec2cae`](https://github.com/AntonOsika/gpt-engineer/commit/eec2cae9b893a2bd7b72c99d3cde96e358d70f8b)
<blockquote>• Define the `DB` class in `gpt_engineer/project_metadata.py`.</blockquote>

- [X] `gpt_engineer/db.py` ❌ Failed
<blockquote>• Import the `DB` class from `gpt_engineer.project_metadata`.
• Modify the `DBs` class to include a `project_metadata` field of type `DB`.</blockquote>

- [X] `gpt_engineer/main.py` ❌ Failed
<blockquote>• Import the `DB` class from `gpt_engineer.project_metadata`.
• Instantiate the `project_metadata` field of `DBs` with the path `.gpteng`.</blockquote>

- [X] `gpt_engineer/main.py` ❌ Failed
<blockquote>• Move the `memory`, `archive`, and `file_list.txt` to the `project_metadata` directory.</blockquote>

</details>

**Comment by ATheorell** [comment]
Closing, since solved in #720, right @RareMojo ?
