### ISSUE TITLE
Make improve flag less intrusive by moving over files like "all_output.txt" and "file_list" to the .gpteng folder

### ISSUE THREAD

**Issue by AntonOsika** [AntonOsika/gpt-engineer#670]
This is done by simply using the new DB in #665 and writing to it

**Comment by Fato07** [comment]
Has a solution be implemented? Otherwise, i would like to take this up

**Comment by UmerHA** [comment]
> Has a solution be implemented? Otherwise, i would like to take this up

@Fato07 go for it! let me know if you have any questions :)

**Comment by pbharrin** [comment]
Some of this was merged this morning (GMT-8) in this PR: #720 

There is one script in: `evals/` that needs to be fixed.  [Here ](https://github.com/AntonOsika/gpt-engineer/blob/main/evals/evals_existing_code.py#L40)
