### ISSUE TITLE
Support for Vertex AI

### ISSUE THREAD

**Issue by haseeb-heaven** [AntonOsika/gpt-engineer#687]
## Policy and Info
- Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
- Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: [Sweep Documentation](https://docs.sweep.dev/)
- Consider adding the label "good first issue" for interesting, but easy features.

## Feature Description
Vertex AI offers a variety of generative models, such as Text Bison, Chat Bison, Code Generation, Code Chat, and Code Completion. These models are fine-tuned for code generation, code chat, and code completion. The pricing for Vertex AI generative models is very reasonable compared to OpenAI. You only pay for the input and output characters that you use, and the price per 1,000 characters is $0.0005 for most models.

## Motivation/Application
Why is this feature useful? 

- Vertex AI provides cost-effective generative models.
- Vertex AI models are specialized for code generation and completion.
- Pricing information is available at [Vertex AI Pricing](https://cloud.google.com/vertex-ai/pricing).
- Detailed documentation on Vertex AI code models can be found at [Vertex AI Code Models](https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-models-overview).
This [Medium Article](https://medium.com/google-cloud/generative-ai-pricing-openai-vs-google-cloud-8fe708a5636a) is found for reference now.

**Comment by ATheorell** [comment]
Hi, 
We have delegated incorporation of additional LLMs by using langchain. To keep maintenance low, we will not make specific code for LLMs not yet supported by langchain. The hope is that langchain will incorporate useful now models such as vertex.

**Comment by haseeb-heaven** [comment]
> Hi, We have delegated incorporation of additional LLMs by using langchain. To keep maintenance low, we will not make specific code for LLMs not yet supported by langchain. The hope is that langchain will incorporate useful now models such as vertex.

Yes LangChain supports Vertex AI i have added that into my project as well, so maybe inside .env file we can support for adding account for Vertex AI API keys.
