### ISSUE TITLE
Sweep: Add a continuous mode

### ISSUE THREAD

**Issue by meyerjohn1** [AntonOsika/gpt-engineer#688]
This new mode and capability will allow for autonomous and continuous code generation, debugging, and code running/testing by engineer. When this mode is enabled, only the user/operator can manually stop it by exiting the terminal window by hand. Otherwise, gpt-engineer should especially remember to keep running, even after executing code that it runs for tests in its coding>debugging>test running loop that never ends, allowing for infinite self improvement of code and similar projects. Ensure you add a new continous command that gpt-engineer recognizes (test this extensively). Sweep must use the gpt-4-32k model always. Run the code and fix errors and keep improving at least 20 times before stopping or shutting down.

<details open>
<summary>Checklist</summary>

- [X] `gpt_engineer/main_script.py` ✅ Commit [`921bf9c`](https://github.com/AntonOsika/gpt-engineer/commit/921bf9ceccaaea01566c07cf474ff96d5b4a41ac)
> • Add a new command 'continuous' in the command parser to trigger the continuous mode of operation.
> • Implement a continuous loop for code generation, debugging, and testing that only stops when the user manually interrupts it.
> • Ensure that the gpt-4-32k model is always used in the continuous mode.
> • Implement a mechanism to run the code, fix errors, and keep improving at least 20 times before stopping or shutting down in the continuous mode.

- [X] `gpt_engineer/steps_module.py` ✅ Commit [`921bf9c`](https://github.com/AntonOsika/gpt-engineer/commit/921bf9ceccaaea01566c07cf474ff96d5b4a41ac)
> • Modify the code generation, debugging, and testing steps to support continuous operation.

</details>

**Comment by ATheorell** [comment]
I like the attempt, but I'm afraid this is way beyond the capabilities of sweep atm. The first step of getting a continuous mode is solving issue  #650 . Any work on this is greatly needed @meyerjohn1
