### ISSUE TITLE
'pip install -e .' command not working on windows

### ISSUE THREAD

**Issue by bafna94** [AntonOsika/gpt-engineer#695]
I downloaded the repo and tghen trying to build on windows but it's not working.
Error:
(venv_gpt_engineer) PS gpt-engineer> pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\jiten\Desktop\Jack\Work\gpt-engineer
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.1.2; however, version 23.2.1 is available.
You should consider upgrading via the 'C:\Users\jiten\Desktop\Jack\Work\gpt-engineer\venv_gpt_engineer\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by ATheorell** [comment]
It should work if you remove the -e flag. Removing the -e flag means that you have to reinstall if you make changes inside gpt-engineer
