### ISSUE TITLE
Unable to complete the request. 

### ISSUE THREAD

**Issue by boringcommerce** [AntonOsika/gpt-engineer#7]
Can you help?

<img width="612" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/102703835/904bee02-a4f7-4246-ab81-b2749f51642c">

**Comment by Woahai321** [comment]
I am not sure, but I believe upgrading openai worked for me `pip install openai --upgrade`

**Comment by bdfsght345** [comment]
?

**Comment by patillacode** [comment]
That error is definitely because your `openai` package version is outdated, please make sure you are running the latest version.
