### ISSUE TITLE
Proposal: Adding CONTRIBUTING.md file and Contributing Guidelines

### ISSUE THREAD

**Issue by aroramrinaal** [AntonOsika/gpt-engineer#70]
### Summary
As a new student contributor to the project, I believe it would greatly benefit the community to have a CONTRIBUTING.md file and contributing guidelines. This document would provide clear instructions and expectations for contributing to the project, helping newcomers like myself navigate the codebase and participate effectively.

### Objectives

1. Onboard new contributors: The CONTRIBUTING.md file will serve as a comprehensive guide for newcomers, providing them with the necessary information to get started with the project. It will outline the project's structure, development workflow, and guidelines for contributing.
2. Streamline contributions: By clearly defining the contribution process, including steps to report issues, propose new features, and submit pull requests, the project can streamline the submission and review of contributions. This will enhance collaboration and ensure that contributions align with the project's standards.
3. Foster a welcoming environment: The CONTRIBUTING.md file will include a code of conduct, establishing a positive and inclusive environment for all contributors. This will promote respectful communication, professionalism, and empathy within the community.

### Proposed Content
The CONTRIBUTING.md file should cover the following key topics:

- Code formatting and style guidelines
- Branch naming conventions and Git workflow
- Testing requirements and procedures
- Documentation standards and contribution guidelines
- Issue reporting guidelines, including the required information and formatting
- Pull request submission guidelines, including the necessary steps and template
- Code review process and expectations
- Code licensing and copyright considerations

**Comment by patillacode** [comment]
I am adding a `CONTRIBUTING.md` file in #61 (merging shortly)

It might not be as complete as this suggests but please feel free to add on top of it.

**Comment by patillacode** [comment]
#61 has been merged @aroramrinaal 
We now have [CONTRIBUTING.md](https://github.com/AntonOsika/gpt-engineer/blob/main/.github/CONTRIBUTING.md)

If you are up for it, please pull `main` and add whatever you think could add value in a PR!

**Comment by patillacode** [comment]
Hi @aroramrinaal 

We now have a [`CONTRIBUTING`](https://github.com/AntonOsika/gpt-engineer/blob/main/.github/CONTRIBUTING.md) guideline and a [`CODE_OF_CONDUCT`](https://github.com/AntonOsika/gpt-engineer/blob/main/.github/CODE_OF_CONDUCT.md) file

Feel free to expand on those in a new PR.
