### ISSUE TITLE
Support for OpenAI Base API Integration

### ISSUE THREAD

**Issue by haseeb-heaven** [AntonOsika/gpt-engineer#710]
## Feature description
**Support for OpenAI Base API Integration:**  
This feature introduces the capability for users to integrate their own **OpenAI Base API**. Currently, our system is reliant on the OpenAI's primary API Base. Given the associated costs and the availability of different models such as _GPT 3.5 and GPT 4_, it's imperative to provide an alternative. By allowing users to supply their own base API, we can potentially offer more cost-effective or even complimentary access to **GPT** models. This can be configured through a dedicated settings file, enabling users to utilize the **GPT Engineer** with their preferred version of **GPT**.

## Motivation/Application
**Cost Efficiency and Flexibility:**  
The primary motivation behind this feature is to offer users greater flexibility and cost efficiency. With the rising costs associated with using OpenAI's primary API, providing an alternative where users can integrate their own API can lead to significant savings. Additionally, this feature can attract a broader user base, especially those looking for reduced costs or free access to GPT models. Furthermore, by allowing users to use their preferred version of GPT, we can cater to a wider range of user preferences and needs.

## Integration/Suggestions.
- **LiteLLM** supports OpenAI Proxy with custom API base which can be easily configured.
[Lite LLM OpenAI Proxy](https://docs.litellm.ai/docs/providers/custom_openai_proxy)
[Custom Base API - LiteLLM](https://openai-proxy.berriai.repl.co)

- **LangChain** supports LiteLLM so we can have integration with custom API using LangChain with LiteLLM without breaking existing codebase.
[LangChain - LiteLLM](https://python.langchain.com/docs/integrations/chat/litellm)

**PS**: I have created a new free **API** that supports _GPT 3.5, 3.5 Turbo, and 4_ versions using the repo below,
This is just to give people an idea of how to use their own custom API base for OpenAI and not to use it commercially for their application. 

Custom **GPT 3.5 Turbo** API base : https://heaven-gpt.haseebmir.repl.co
**_Note:_** - **Use it only for this repo for testing purposes only.**.

The command to Run GPT-Engineer using Custom base API.
```python
python -m gpt_engineer.cli.main projects/example 'gpt-4' --openai-api-base https://heaven-gpt.haseebmir.repl.co
```

Here is the PR for this issue [GPT Engineer - API Base Support](https://github.com/AntonOsika/gpt-engineer/pull/788)

- **_Test use cases for servers._**
**Custom** API servers can be of two types:

- **Authenticated**: These servers require users to authenticate themselves using a mechanism such as OAuth or API keys. This ensures that only authorized users can access the API.

- **Unauthenticated**: These servers do not require any authentication. This means that anyone can access the API, which can be a security risk.

I have only tested with **Unauthenticated** _server_ as i only have single server to test, and to make sure we cover all server we need to test the both server for our use case here.

**Comment by ATheorell** [comment]
I think this sounds like a great addition!

To ensure consistent responses of all LLMs now and over time, we are using langchain as an abstraction layer. Currently, models are created in ai.py, either on line 358, if an azure endpoint is provided or on line 371 for the regular OpenAI_API. Looking into langchain langchain/chat_models/openai.py , I see that the ChatOpenAI class that we are already using supports that we provide a custom api url on line 153. Do you think your API could be plugged there or in some similar way, keeping the close integration with langchain?

Would be cool with feedback from the people who know more about the philosophy of this in gpt-engineer @pbharrin @AntonOsika

**Comment by haseeb-heaven** [comment]
> I think this sounds like a great addition!
> 
> To ensure consistent responses of all LLMs now and over time, we are using langchain as an abstraction layer. Currently, models are created in ai.py, either on line 358, if an azure endpoint is provided or on line 371 for the regular OpenAI_API. Looking into langchain langchain/chat_models/openai.py , I see that the ChatOpenAI class that we are already using supports that we provide a custom api url on line 153. Do you think your API could be plugged there or in some similar way, keeping the close integration with langchain?
> 
> Would be cool with feedback from the people who know more about the philosophy of this in gpt-engineer @pbharrin @AntonOsika

One implementation i see it using LangChain and within that we can use LiteLLM to set openAI custom API base as shown here [LiteLLM - Custom OpenAI base](https://docs.litellm.ai/docs/providers/custom_openai_proxy).

But still i would need to test it first so that we can handle the response from server it should support both **Non-Stream** and **Stream** responses through this.

**Comment by ShinkoNet** [comment]
This already works.

set env OPENAI_API_BASE manually or add `os.environ["OPENAI_API_BASE"] = "https://xxx.com/v1"` before `import openai`

**Comment by ATheorell** [comment]
Sounds like what we need is testing through the current capabilities systematically (beyond liteLLM) and updating the documentation and potentially the README.

**Comment by haseeb-heaven** [comment]
> This already works.
> 
> set environment variable OPENAI_API_BASE manually or add `os.environ["OPENAI_API_BASE"] = "https://xxx.com/v1"` before `import openai`

Yes i know how to set the API base i have tested that but with LiteLLM when setting we need also to parse the data in same way as it does from other LLM which i found it to be not working with Streaming options set to True. The tokenizer needs to be adjusted

**Comment by ATheorell** [comment]
I understand that getting the parsing correct is challenging! Any progress on this @haseeb-heaven ?

**Comment by krrishdholakia** [comment]
Hi @haseeb-heaven can you help me understand the issue better - as i read it, there seems to be some gap between the expected and returned format for streaming. we try to 1:1 map to openai for all responses including streaming, happy to chat more on this issue or via discord.

**Comment by haseeb-heaven** [comment]
> Hi @haseeb-heaven can you help me understand the issue better - as i read it, there seems to be some gap between the expected and returned format for streaming. we try to 1:1 map to openai for all responses including streaming, happy to chat more on this issue or via discord.

I think the issue is with the tokenizer its not tokenizing all the words properly for both mode Stream and Non-stream

**Comment by krrishdholakia** [comment]
Tracking it here - https://github.com/BerriAI/litellm/issues/587. 

Can you give me a way to repro the problem? I'll push a fix for this asap.

**Comment by krrishdholakia** [comment]
FYI - openai doesn't return tokens for streamed responses - https://platform.openai.com/docs/api-reference/chat/create

**Comment by haseeb-heaven** [comment]
> FYI - openai doesn't return tokens for streamed responses - https://platform.openai.com/docs/api-reference/chat/create

![image](https://github.com/AntonOsika/gpt-engineer/assets/11544739/ca4caaa6-ad09-4f43-864d-546ca76c3c90)
Then how do you see this issue ?
This is clearly issue of Tokenizer the words are not getting separated here from Response.

And i have successfully changed base API now only this issue remaining

**Comment by haseeb-heaven** [comment]
Resonse from GPT-Engineer
![image](https://github.com/AntonOsika/gpt-engineer/assets/11544739/1ff245f3-6bcf-495c-924d-e241b8833810)


And response from my own Custom GPT is fine.

![image](https://github.com/AntonOsika/gpt-engineer/assets/11544739/90fd213f-c497-430f-bff4-4db9bdaeab5e)

**Comment by haseeb-heaven** [comment]
Update : I finally was able to get fully working project using my own custom API base,
The only issue left here Parsing of text with **Stream mode.**
I set **Streaming to false** so right now its working.

**Comment by haseeb-heaven** [comment]
**Attention @ATheorell:**

I kindly request your feedback on the following proposed adjustments:

**Current Configuration:**
1. The **API Base** is configured via the command line option `--openai-api-base`.
2. At present, the streaming functionality is *deactivated*.
3. It's mandatory to set the **API Key** using the `.env` (Environment) file.

**Proposed Enhancements:**
1. Implement a mechanism to modify the **API Base** for both streaming and non-streaming responses.
2. Allow the **API Key** to default to *Empty* when a specific base API is chosen. While this is feasible with LiteLLM, it presents challenges with LangChain and OpenAI. I am exploring more solutions to address this.

**Comment by TheoMcCabe** [comment]
This feature request only includes running against custom OpenAI models right? I was going to make a feature request for running against a local free model - like Mistral 7b (https://mistral.ai/news/announcing-mistral-7b/) which can be run locally . Just double checking that isnt covered here?

**Comment by haseeb-heaven** [comment]
> This feature request only includes running against custom OpenAI models right? I was going to make a feature request for running against a local free model - like Mistral 7b (https://mistral.ai/news/announcing-mistral-7b/) which can be run locally . Just double checking that isnt covered here?

Yes this is only for OpenAI models right now.
