### ISSUE TITLE
Ask to run code after improvement

### ISSUE THREAD

**Issue by UmerHA** [AntonOsika/gpt-engineer#722]
Unlike after code creation, after code improvement(i.e., the `-i` flag) gtp-engineer doesn't ask if the code should be run.

## Feature description
When using the `-i` flag and gpt-engineer has finished improving code, the use should be asked if they want to run the code.

## Motivation/Application
In my view, a good workflow for gpt-engineer would be:
1. I enter a prompt, gpte asks clarifying questions, I answer, gpte creates a codebase
2. With my consent, gpte runs the  code
3. I get asked if the code worked well. If not, I'm asked if I want to improve.
4. I enter an improvement prompt
5. gpte improves code
6. **With my consent, gpte runs the code** <- this issue
7. Repeat

**Comment by mahimairaja** [comment]
So you wish to add improvement on interactive mode? Am I right?

**Comment by UmerHA** [comment]
> So you wish to add improvement on interactive mode? Am I right?

Yes, I think I'd be good if that existed. Not sure if I can contribute though.

**Comment by UmerHA** [comment]
fyi: requires #721 to be merge

**Comment by Ruijian-Zha** [comment]
I concur with @UmerHA's points. Additionally, automating the environment setup to handle dependencies would be beneficial, saving users from manual installations, especially when new dependencies are introduced post-improvement. This would streamline the process, making the `-i` flag for code improvement more user-friendly and efficient.

**Comment by ATheorell** [comment]
@Ruijian-Zha I'm not sure if I understand. If successful, the generated run.sh script should create a virtual environment and install dependencies. Hypothetically, by including the run.sh/requirement.txt/whatever in the improvement prompt, the agent should already be able to suggest addition of new dependencies. I may be missing something here.
