### ISSUE TITLE
Chunking and longer context support (>8192 tokens or whatever under the hood limit)

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [AntonOsika/gpt-engineer#759]
## Feature description
I would like to use gpt-engineer to improve my project, currently all my files has 31418 tokens which well exceed the 8192 tokens limit. With this solved I see a practical application of this tool. We can use vector db integrations like AutoGPT.

## Motivation/Application

This makes the tool usable for real use cases.

**Comment by ATheorell** [comment]
This is really a needed feature, which I claim is already requested in #716 . If you think #716 (including its discussion) does not address this, let me know and I'll reopen.
