### ISSUE TITLE
Result was not saved to files into workspace.

### ISSUE THREAD

**Issue by kingzmedia** [AntonOsika/gpt-engineer#77]
I'm running on MAC, on GPT3.5, with Python 3.11.3
When i run the example main prompt (and a custom prompt too), that make the code in my terminal with success. 
But on the example/workspace folder, i have just a file named "python" (without ext), with just one file content here. Any other code file.

I have tried some other prompt and same results (same for other language).

I have followed the readme file for installation.

**Comment by holovka** [comment]
use gpt-3.5-turbo-16k instead ... had the same issue.

**Comment by patillacode** [comment]
Many issues are referring to the same problem, we have some faith in [this approach](https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594508297) to fix it

Please try to read existing issues in case they are related to your question before posting a new one.

**Comment by kingzmedia** [comment]
Okay, thanks you !
