### ISSUE TITLE
KeyError: "File 'roadmap' could not be found in  '/content/gpt-engineer/gpt_engineer/cli/preprompts'"

### ISSUE THREAD

**Issue by chrisivogt** [AntonOsika/gpt-engineer#771]
## Expected Behavior
gpt-engineer is reading the folder 'preprompt' from './gpt_engineer'.

## Current Behavior
gpt_engineer is expecting the folder 'preprompt' in './gpt_engineer/cli'. Most likely because main.py was earlier located in the same path as the folder preprompt.

## Failure Information
KeyError: "File 'roadmap' could not be found in 
'/content/gpt-engineer/gpt_engineer/cli/preprompts'"

### Steps to Reproduce
clone the developer edition and try to run the example prompt

**Comment by ATheorell** [comment]
This should be solved by #772
