### ISSUE TITLE
Prompt History Log

### ISSUE THREAD

**Issue by TheoMcCabe** [AntonOsika/gpt-engineer#793]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
I think with the improved --improve mode, we are in a place where we could generate a new project, and then run through multiple cycles of improvement to incrementally add new features. I think we should maintain a log of all prompts provided since the creation of the project. This would be useful for debugging and could be combined with a tool for rerunning a list of prompts from scratch - which would be useful for development and testing. 

Possibly also, after every run of gpt engineer, we should create a git commit on the project containing the change. Part of the prompt log can be the commit hash the prompt ran against. This would be useful because you can rerun a scenario by navigating to that commit hash and running the prompt from the prompt log.  It would also make the prompt log make sense if  gpt-engineer was contributing to a project alongside direct humans contributers who are also making commits. 

## Motivation/Application
It feels wrong that to improve the code base we have to overwrite the initial prompt we used to create that code base and that initial prompt is lost by the system. Having a log file would make it possible to review the history multiple executions of gpt-engineer, and build tools which can re run histories of multiple executions. If stored against commit hash it would also make easier to re run a particular improvement at a particular location in the git history.

**Comment by ATheorell** [comment]
This issue should be a sub-task of #655
