### ISSUE TITLE
Run against free local models 

### ISSUE THREAD

**Issue by TheoMcCabe** [AntonOsika/gpt-engineer#794]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
Feature request from a friend of mine who may contribute soon:  

I think given the cost of running gpt-engineer against open AI models, there should be an option to run offline against local models. A good option would be Mistral 7b (https://mistral.ai/news/announcing-mistral-7b/) which seems lightweight enough to run locally. 

This may have cross over with https://github.com/AntonOsika/gpt-engineer/issues/710 and is probably part of a general epic for greater interoperability with other models? 

## Motivation/Application
It will provide a totally free opensource way of running gpt-engineer. It would also provide a way of running gpt-engineer without internet access. It would also allow the entire system to be self hosted privately - which could be a security requirement for some users.

**Comment by TheoMcCabe** [comment]
I think this issue is resolved by https://github.com/AntonOsika/gpt-engineer/pull/787/files can you confirm @krrishdholakia ?

**Comment by krrishdholakia** [comment]
yea you could use litellm to use this with gpt-engineer, if you have a local mistral ollama/tgi running. 

you could also do this with fastchat/localai etc. which provide openai compatible endpoints.

**Comment by TheoMcCabe** [comment]
Ok nice thanks - will close this issue.
