### ISSUE TITLE
ask_for_files _tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by ArsSirek** [AntonOsika/gpt-engineer#809]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 
 Hi all, thanks for a great tool!
 This is probably is not a but with the gpt-engineer itsefl. That it is an unhanded exception thrown in process, so I hoped to collect here some general guidance that can latter be added to documentation.

## Expected Behavior
an option to skip `ask_for_files` and let the system pick randomly on its own would be great. I have tried to launch in docker container and not sure if this can work in container without additional configurations

## Current Behavior
ask_for_files doesn't work in docker container environment

GPT-engineer asked 
```
How do you want to select the files?
1. Use File explorer.
2. Use Command-Line.
```
If i pick 1. I'am receiving the following error
```
Traceback (most recent call last):
  File "/usr/local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/main.py", line 169, in main
    messages = step(ai, dbs)
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/core/steps.py", line 469, in set_improve_filelist
    ask_for_files(dbs.project_metadata, dbs.workspace)  # stores files as full paths.
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/file_selector.py", line 370, in ask_for_files
    file_path_list = gui_file_selector(workspace_db.path)
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/file_selector.py", line 392, in gui_file_selector
    root = tk.Tk()
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)

_tkinter.TclError: no display name and no $DISPLAY environment variable
```

## Failure Information

if I pick 2. it throws a different error
```

How do you want to select the files?

1. Use File explorer.
2. Use Command-Line.

Select option and press Enter (default=1): 
2
     1697667327127/

0.   └──  prompt

Select files by entering the numbers separated by commas/spaces or
specify range with a dash. 

Example: 1,2,3-5,7,9,13-15,18,20 (enter 'all' to select everything)


Select files:
1

Traceback (most recent call last):
  File "/usr/local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/main.py", line 169, in main
    messages = step(ai, dbs)
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/core/steps.py", line 469, in set_improve_filelist
    ask_for_files(dbs.project_metadata, dbs.workspace)  # stores files as full paths.
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/file_selector.py", line 373, in ask_for_files
    file_path_list = terminal_file_selector(workspace_db.path)
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/file_selector.py", line 410, in terminal_file_selector

    return file_selector.ask_for_selection()
  File "/usr/local/lib/python3.10/site-packages/gpt_engineer/cli/file_selector.py", line 298, in ask_for_selection
    selected_paths.append(str(self.selectable_file_paths[num]))

KeyError: 1
```

Information about the failure, including environment details, such as LLM used.

### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Any relevant log snippets or files here.

**Comment by ATheorell** [comment]
Thanks for submitting the bug. It should be mentioned that current devs are not the quickest at fixing docker things. Last time we had a fix by @pralad-p . Any chance you could look into this?

I don't see the point of having random selection. Regular file_selection should just work.

**Comment by pralad-p** [comment]
Ooops @ATheorell  I think you might have confused me with someone else, but I have experience with Docker as well. 
@ArsSirek let's look at both of your options you entered. 

**For Option 1**
You invoke the File Selector, which in turn launches a GUI tkinter window instance (or tries to). Docker is generally run in headless. Docker says it doesn't have a display and complains to tkinter. That's what you see here. If you really want to select with a file selector, then you need to enable X11 forwarding to your host (which in my opinion, defeats the purpose of using a Docker container). 

**For Option 2**
When you enter it, this is what you get.
```
Select option and press Enter (default=1): 
2
     1697667327127/

0.   └──  prompt
```
This is an incorrect usage of gpt-engineer. You need to run 
```
gpt-engineer <DIRECTORY THAT CONTAINS PROMPT FILE>
```
From what I see, it looks like you run it on the parent of the prompt, that screws everything up. I guess if you paste the tree command output here, it would shine more light.

**Comment by ArsSirek** [comment]
Hello [ATheorell](https://github.com/ATheorell) and [pralad-p](https://github.com/pralad-p), thank you both for your responses!

**Option 1:** I understand now, thanks for the explanation.

**Option 2:** I actually invoke the GPT-engineer using a folder containing the prompt file. In this case, `1697667327127/` is the name of the folder. The output might appear a bit deformed as I don't call the command directly from my terminal, but use a Node.js script to invoke it through an SSH connection. (https://github.com/ArsSirek/node-red-contrib-gpt-engineer-api/blob/main/logic/initialPrompt.js#L34)

I am still unsure about what could have triggered the `KeyError: 1` error.

Additionally, in this project, I attempted to interface a GPT-engineer installation with a Node-RED backed web UI chat using uibuilder. It's in a preliminary stage at the moment. Does GPT-engineer have any plans to implement an API or perhaps its own web-server variation? Or will the CLI remain the sole method of interaction for the foreseeable future?

**Comment by pralad-p** [comment]
Can't really talk about the future of gpt-engineer as I'm also just a fellow user helping out :) 
I'm not entirely confident with JS, so I really can't help you in this sector, but I'm curious what happens if you run the same experiment again. Same conditions. Same project folder but this time enter 0, not 1. Curious what happens. I'm also curious whether you observe the same deformation in the output.

**Comment by ArsSirek** [comment]
Unfortunately, I can't recall the exact prompt, and all my attempts have not led to a file select functionality now. However, your guess seems right; there probably was only one image in the suggestions, and 0 could have worked.

Anyway, thank you all once again. I believe we can close this issue as it's more of an installation misconfiguration rather than a bug.

**Comment by ATheorell** [comment]
@pralad-p thanks for going to the bottom with the issues.

@ArsSirek actually, its great that you raise this! We had http interfacing using the agent-protocol (https://agentprotocol.ai/) on the master for some time, but we removed it for now, because at the time being, the sdk that we used didn't seem mature yet. If this would be a high value feature for you we may consider looking into it again. Do you have any other suggestions for interfaces? Last but not least, if it would be easy for you to add some standardized interface to gpt-engineer, you are more than welcome to make a suggestion and a PR.

**Comment by ArsSirek** [comment]
Hi @ATheorell,

Apologies for my delayed reply, and thank you for sharing the link—it's new for me and interesting.
I was more playing around rather then trying to implement reliable interface, because the whole idea to execute commands through cli and build UI upon it doesn't seem solid to me.

I believe that if gpt-engineer begins to support an HTTP API, offering the same functionalities currently available via CLI, it wouldn't be long before we see a community-developed UI. This idea was inspired by my recent encounter with the [Ollama project, which utilizes an HTTP API](https://github.com/jmorganca/ollama/#rest-api) for its UI.

not sure how this image selection will work through API, but I think it's possible too, for example we could publish files to web server root so they became accessible through the same server that serves the API

**Comment by ATheorell** [comment]
Community UI is underway #834 !
Thanks for input, closing.
