### ISSUE TITLE
Interact with git?

### ISSUE THREAD

**Issue by Jiaming-Liu** [AntonOsika/gpt-engineer#821]
## Feature description
Add an option for improvement mode (-i) to automatically make a commit and its commit msg for the changes 

## Motivation/Application
This makes it easier to manage and revert changes.

**Comment by Jiaming-Liu** [comment]
right now i'm doing this.
```bash
#!/bin/bash

# Check if the file exists
if [ ! -f .gpteng/file_list.txt ]; then
    echo ".gpteng/file_list.txt does not exist."
    exit 1
fi

# Read each line from the file
while IFS= read -r line
do
    # Stage each file listed in file_list.txt
    git add "$line"
    echo "Staged: $line"
done < .gpteng/file_list.txt

# Output the staged changes
echo "Here are the staged changes:"
git status
git commit -m "$1"

**Comment by ATheorell** [comment]
Hi,

Yes, agree that git tracking of --improve would be great. It is mentioned in #793 which I think can be combined with #655 . Would you be interested in making a PR @Jiaming-Liu ?

**Comment by TheoMcCabe** [comment]
Ive been experimenting with a whole workflow that uses git from the begining and integrates with it into logs etc to add more tracecability. I have a lot going on though so any incremental improvement in this area would be great
