### ISSUE TITLE
vite+preact vercel issued ChatGPT like web interface on localhost

### ISSUE THREAD

**Issue by zdanl** [AntonOsika/gpt-engineer#834]
This issue is about creating a web interface on localhost, later potentially a cloud service, allowing for the creation of code bases off the CLI

**Comment by ATheorell** [comment]
Hi, are you on our discord https://discord.gg/8tcDQ89Ej2 @zdanl ?
I would love to discuss to have a less formal discussion on this.

**Comment by ATheorell** [comment]
Discussions on this are redirected to #505
