### ISSUE TITLE
ValueError: Got unexpected message type: AIMessageChunk

### ISSUE THREAD

**Issue by kachdi** [AntonOsika/gpt-engineer#859]
If I run gpt-engineer I am getting this error every time regardless of the prompt: ValueError: Got unexpected message type: AIMessageChunk

Python/3.9/lib/python/site-packages/langchain/schema/messages.py:403 in _message_from_dict

│ ❱ 403 │   │   raise ValueError(f"Got unexpected message type: {_type}")  

```
def _message_from_dict(message: dict) -> BaseMessage:
    _type = message["type"]
    if _type == "human":
        return HumanMessage(**message["data"])
    elif _type == "ai":
        return AIMessage(**message["data"])
    elif _type == "system":
        return SystemMessage(**message["data"])
    elif _type == "chat":
        return ChatMessage(**message["data"])
    elif _type == "function":
        return FunctionMessage(**message["data"])
    elif _type == "tool":
        return ToolMessage(**message["data"])
    else:
        raise ValueError(f"Got unexpected message type: {_type}")
```

I also tried Updating and upgrading everything

**Comment by ATheorell** [comment]
This issue has been reported before and is solved by restricting langchain to be in the version span >=0.0.240, <=0.0.312

Hopefully, it now also works with the latest langchain, though I have not tested that personally
