### ISSUE TITLE
Default launch command is too cumbersome

### ISSUE THREAD

**Issue by RukshanJS** [AntonOsika/gpt-engineer#872]
## Policy and info
 - good first issue

## Feature description
Currently, to use the tool `gpt-engineer` command has to be used. Although this can be resolved using an alias, would be nice to have a command such as `gpte` be available by default.

Can refer https://clig.dev/#naming for more details.

## Motivation/Application
This feature will make it very user friendly to use the command. Having to type dash (`-`) in `gpt-engineer` command is very cumbersome.

**Comment by captivus** [comment]
Thanks for the suggestion! We are working on a vast refactoring of the project, so please submit a PR on the [refactor branch](https://github.com/AntonOsika/gpt-engineer/tree/refactor). I suggest waiting until midweek as we are implementing Poetry for package and dependency management.

**Comment by captivus** [comment]
Okay, revisiting this now after having implemented Poetry in a PR on the [refactor-poetry branch](https://github.com/AntonOsika/gpt-engineer/tree/refactor-poetry).  That branch would be the best place to implement this.

**Comment by RukshanJS** [comment]
Is someone assigned to this? I think I can implement this. Studying the codebase right now.

**Comment by captivus** [comment]
Thanks for the contribution!On 4 Dec 2023, at 11:27, Rukshan J. Senanayaka ***@***.***> wrote:﻿
@captivus this is my first contribution here. Kindly let me know if anything is not correct.
#889
