### ISSUE TITLE
Could not locate file 'C:\\Python311\\Scripts\\tqdm.exe'

### ISSUE THREAD

**Issue by tomasantunes** [AntonOsika/gpt-engineer#874]
## Expected Behavior

Installing GPT Enginner through pip.

## Current Behavior

The installation fails.

## Failure Information

I get an error saying "Could not install packages due to an OSError: [WinError 2] The system couldn't locate the specified file: 'C:\\Python311\\Scripts\\tqdm.exe' -> 'C:\\Python311\\Scripts\\tqdm.exe.deleteme'"

This is happening with Python 3.11 on Windows 10.

### Steps to Reproduce

Run the command "pip install gpt-engineer".

### Failure Logs

![gpt-engineer-bug](https://github.com/AntonOsika/gpt-engineer/assets/12017352/2516edae-4fe0-45c0-bf76-93daaa777c2d)

**Comment by captivus** [comment]
Please update pip, as suggested in the error message, and feedback.

`python.exe -m pip install --upgrade pip`

**Comment by ReZeroE** [comment]
Aside from upgrading pip as mentioned, the command needs to be run with admin permission to work.

**Comment by ShubhodeepMukherjee123** [comment]
hmmmmmmmmmmmmmmm
