### ISSUE TITLE
No module named 'gpt_engineer'

### ISSUE THREAD

**Issue by avelev99** [AntonOsika/gpt-engineer#88]
I have attempted both using my folder and prompt and following the instructions word by word and in both cases I end up receiving the following error:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from gpt_engineer.chat_to_files import to_files
ModuleNotFoundError: No module named 'gpt_engineer'

**Comment by avelev99** [comment]
The issue is on a Windows 11 machine on both anaconda environment and regular Python. I am using a valid OpenAI key.

**Comment by ntua-el18406** [comment]
@avelev99 Try running the app from the project dir, not from the `gpt_engineer`.

**Comment by avelev99** [comment]
Thank you @ntua-el18406 moving "main.py" outside gpt-engineer folder fixes the issue for me
