### ISSUE TITLE
The term 'gpt-engineer' is not recognized

### ISSUE THREAD

**Issue by wp-coin** [AntonOsika/gpt-engineer#893]
hey guys i'm on windows 11 and I installed via python 'pip install gpt-engineer'

everything seems to install fine

but now I get this in PowerShell 
```
gpt-engineer : The term 'gpt-engineer' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

```
how do I add gpt-engineer in the path?

**Comment by captivus** [comment]
This seems like a PATH issue.  Best practice is to run Python packages from a Python virtual environment.  Here's a good reference on this: https://realpython.com/python-virtual-environments-a-primer/

Please reinstall in a Python virtual environment and feedback if you still have issues.

**Comment by captivus** [comment]
I'll close this, but reopen if you feedback with subsequent issues.
