### ISSUE TITLE
pip metadata problem in 0.2.0? (downgrades install to 0.1.0)

### ISSUE THREAD

**Issue by IanRogers** [AntonOsika/gpt-engineer#896]
## Expected Behavior

Using `python -m pip install gpt-engineer` should install version 0.2.0 by now. 

## Current Behavior

pip seems to reject 0.2.0 (as the package metadata is "0.0.0"???) and installs 0.1.0 instead.

## Failure Information

Running the below pip command shows a message:

```
Discarding https://files.pythonhosted.org/packages/17/d3/adbca4a7f982636fc8a57f41bd174105f5b78b557749fc1e5d19d6f89dea/gpt_engineer-0.2.0.tar.gz (from https://pypi.org/simple/gpt-engineer/) (requires-python:>=3.8.1,<3.12): Requested gpt-engineer from https://files.pythonhosted.org/packages/17/d3/adbca4a7f982636fc8a57f41bd174105f5b78b557749fc1e5d19d6f89dea/gpt_engineer-0.2.0.tar.gz has inconsistent version: expected '0.2.0', but metadata has '0.0.0'
  Downloading gpt_engineer-0.1.0-py3-none-any.whl.metadata (7.5 kB)
```

### Steps to Reproduce

Using an anaconda installation on MacOS

conda create -n gpt-engineer python=3.11.5
conda activate gpt-engineer
python -m pip install gpt-engineer

**Comment by captivus** [comment]
Thanks for raising this.  It does, indeed, seem to be an issue with the package on PyPI.

![image](https://github.com/AntonOsika/gpt-engineer/assets/366332/3b80463d-1335-4d4b-b6e0-744c2cfdd66d)

We're looking into it.

**Comment by ATheorell** [comment]
Thanks for reporting, this should now be fixed
