### ISSUE TITLE
gpt 3.5? 

### ISSUE THREAD

**Issue by maljefairi** [AntonOsika/gpt-engineer#9]
does it works on gpt 3.5

**Comment by maljefairi** [comment]
It looks like you're trying to use a model called `gpt-4` that isn't recognized. As of my training data (up to September 2021), OpenAI has released models up to `gpt-3`. If OpenAI has released a `gpt-4` model after September 2021, you should update the OpenAI Python package to the latest version, which should support it. 

You can update the OpenAI package using pip:

```bash
pip install --upgrade openai
```

If the error still persists, it may be that a `gpt-4` model is not yet available. In that case, you can try using the `gpt-3` model instead.

To do that, you would need to locate the part of the code where the `gpt-4` model is referenced, and change it to `gpt-3`. The error message indicates that this is happening in the file `ai.py` on line 27.

The code in `ai.py` around line 27 probably looks something like this:

```python
response = openai.ChatCompletion.create(
    model="gpt-4",
    messages=messages,
)
```

You can change the model to `gpt-3`:

```python
response = openai.ChatCompletion.create(
    model="gpt-3",
    messages=messages,
)
```

After making this change, try running the `main.py` script again and see if it works.

**Comment by maljefairi** [comment]
The AI model is indeed set in `main.py`. The `model` parameter in the `chat` function defaults to "gpt-4". You should change this to "gpt-3" or another valid model, like this:

```python
@app.command()
def chat(
    project_path: str = typer.Argument(None, help="path"),
    run_prefix: str = typer.Option("", help="run prefix, if you want to run multiple variants of the same project and later compare them"),
    model: str = "gpt-3",  # Change this line
    temperature: float = 0.1,
):
```

After making this change, save `main.py` and try running your script again. This should resolve the error you were encountering. 

Remember, though, that if OpenAI has released a `gpt-4` model after my training data was collected (up to September 2021), you should update the OpenAI Python package to the latest version to use it, with `pip install --upgrade openai`.

**Comment by maljefairi** [comment]
to make it work in 3.5 please replace the code in main.py with this following code:
=================CopyCodeUnderThisLine======================
import json
import os
import pathlib
from typing import Optional
import openai
from chat_to_files import to_files
from ai import AI
from steps import STEPS
from db import DB, DBs
import typer


app = typer.Typer()


@app.command()
def chat(
    project_path: str = typer.Argument(None, help="path"),
    run_prefix: str = typer.Option("", help="run prefix, if you want to run multiple variants of the same project and later compare them"),
    model: str = "gpt-3.5-turbo",
    temperature: float = 0.1,
):

    if project_path is None:
        project_path = str(pathlib.Path(__file__).parent / "example")

    input_path = project_path
    memory_path = pathlib.Path(project_path) / (run_prefix + "memory")
    workspace_path = pathlib.Path(project_path) / (run_prefix + "workspace")

    ai = AI(
        model=model,
        temperature=temperature,
    )

    dbs = DBs(
        memory=DB(memory_path),
        logs=DB(pathlib.Path(memory_path) / "logs"),
        input=DB(input_path),
        workspace=DB(workspace_path),
        identity=DB(pathlib.Path(__file__).parent / "identity"),
    )


    for step in STEPS:
        messages = step(ai, dbs)
        dbs.logs[step.__name__] = json.dumps(messages)


if __name__ == "__main__":
    app()

**Comment by iamlite** [comment]
no need for all that. just replace 

`model: str = "gpt-4",`
with 
`model: str = "gpt-3.5-turbo",`

**Comment by bdfsght345** [comment]
o

**Comment by adithyapaib** [comment]
How to change the OPENAI API end point to use 3rd party proxy API to use this ?

**Comment by offiub** [comment]
You really need to clear the issues and the errors

**Comment by RemkoDelsman** [comment]
I use the new gpt-3.5-turbo-16k without errors now. I had to change the string accordingly in both main.py and also in scripts/rerun_edited_message_logs.py.
