### ISSUE TITLE
No module named 'gpt-engineer'

### ISSUE THREAD

**Issue by brainshower** [AntonOsika/gpt-engineer#91]
Cloned and executed 'pip install .' per the README.  First run:
```
python3 gpt_engineer/main.py example/

Traceback (most recent call last):
  File "/home/matt/Documents/GPTEngineer/gpt-engineer2/gpt-engineer/gpt_engineer/main.py", line 6, in <module>
    from gpt_engineer.chat_to_files import to_files
ModuleNotFoundError: No module named 'gpt_engineer'
```

**Comment by jgerton** [comment]
same problem...
(gpt-eng) PS D:\Projects\gpt-engineer> python gpt_engineer\main.py example
Traceback (most recent call last):
  File "D:\Projects\gpt-engineer\gpt_engineer\main.py", line 6, in <module>
    from gpt_engineer.chat_to_files import to_files
ModuleNotFoundError: No module named 'gpt_engineer'

**Comment by RareMojo** [comment]
I'm not sure what the real solution is but, you can do this for now..

- Move all of the scripts out of ../gpt_engineer/ and into the main ../gpt-engineer-main/ directory.
- In `steps.py` and `main.py` change the following import lines to-

_steps.py_
```python
import json

from ai import AI
from chat_to_files import to_files
from db import DBs

# ..rest of code below
```

_main.py_
```python
import os
import json
import pathlib
import typer

from chat_to_files import to_files
from ai import AI
from steps import STEPS
from db import DB, DBs

# ..rest of code below
```
- Run gpt-engineer with `python .\main.py .\project_name\`

Sorry for the issues hope it helps!

**Comment by RogelioDaniel** [comment]
run, but i have this issue 
<img width="870" alt="image" src="https://github.com/AntonOsika/gpt-engineer/assets/55957565/e0a69996-13e0-4026-b86b-022faafc2710">

**Comment by patillacode** [comment]
Sorry, there was some confusion after a few changes, README has been edited to better explain how to run.

Please pull the latest version and follow the README
```markdown
pip install -r requirements.txt
export OPENAI_API_KEY=[your api key]
python -m gpt_engineer.main my-new-project
```

**Comment by jgerton** [comment]
i fixed this by updating vscode settings.json.  it still had the path to Python310 in "python.defaultInterpreterPath".  not sure why the update to Python 3.11.x didn't change that.  All I changed was Python310 to Python311 and everything worked fine directly from the cloned repo, no moving files around at all.
