### ISSUE TITLE
Placeholders and "will follow a similar structure, so I will not repeat them here for brevity."

### ISSUE THREAD

**Issue by h5kk** [AntonOsika/gpt-engineer#911]
## Expected Behavior
It should, or should have the option to, write full solutions without placeholders or omisssions. 

## Current Behavior
"// Add explicit instantiation for other types as needed"
" will follow a similar structure, so I will not repeat them here for brevity."

## Failure Information

Ask it to create a solution or project with more than a few classes.

**Comment by ATheorell** [comment]
We do ask it pretty explicitly not to use placeholders in the preprompts, but the LLM has a mind of its own and adds placeholders sometimes anyway. Unfortunately, this is not something we can change easily on the side of gpt-engineer. My advise is to think whether there is a way to break down your complex implementation in multiple calls
