### ISSUE TITLE
gpt-engineer keeps trying to background jobs when writing shell scripts

### ISSUE THREAD

**Issue by createthis** [AntonOsika/gpt-engineer#915]
## Expected Behavior

I expect gpt-engineer to be able to run my unit tests, analyze the results, modify the code, repeat, until successful

## Current Behavior

I'm executing:
```bash
gpte -i .
```

This is my prompt:

```
Prerequisites:
Do not use the & character when writing shell scripts.

Overview:
We have code in remove_duplicates.js and a unit test in remove_duplicates.test.js.
Currently, when we run `npm run test`, the unit test fails.
Ask me to run the unit test and give you the results. Do not assume you know what is going wrong.
Modify the code in remove_duplicates.js so the unit test passes.
Ask me to run the unit test again to confirm the changes were successful.
If they were, you're done. If not, prompt and try again.
```

gpt-engineer keeps trying to write and execute bash scripts with `&` characters. For example:
```bash
npm install
npm test &
node remove_duplicates.js &
```

In this case my code is in `remove_duplicates.js` and my unit tests are in `remove_duplicates.test.js`.

For some reason, gpt-engineer keeps trying to run this by backgrounding the processes, then complains when it can't read the output (at least, I assume that's what is going on):
<img width="1440" alt="Screenshot 2023-12-18 at 3 49 24 PM" src="https://github.com/AntonOsika/gpt-engineer/assets/1695880/08a24cdd-5b5c-447d-8d97-0b70eaea6e40">

I've tried adding this to the top of my prompt:
```
Prerequisites:
Do not use the & character when writing shell scripts.
```

... but it keeps doing it.

Am I doing something silly, or is this a bug?

Thanks!

**Comment by ATheorell** [comment]
Great issue here! 
First of all, its strange that the LLM doesn't get your hint about the & symbol, however, this is more of an LLM problem than a gpt-engineer problem. You could try to modify the prompt to not only refer to the & symbol, but being more explicit about not using sub processes or sub shells in the entrypoint script.
Secondly, your prompt suggests a non-standard work flow with multiple executions. This is not how gpt-engineer works atm. Currently, to do what you want to do, you have to make multiple calls to the command line (could be done in a script!). If you figure out something useful, feel free to suggest a feature request here on GH.
